"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { ArrowLeft, Plus, RefreshCw, ChevronDown, ChevronUp, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/layout/PageHeader";
import { EmptyState } from "@/components/shared/EmptyState";

interface RemainingItem {
  id: string;
  category: string;
  title: string;
  description: string;
  severity: string;
  scopeItemId: string | null;
  functionalArea: string | null;
  assignedTo: string | null;
  resolution: string | null;
  resolvedAt: string | null;
  resolvedBy: string | null;
  autoGenerated: boolean;
  sourceEntityType: string | null;
  sourceEntityId: string | null;
  createdAt: string;
  updatedAt: string;
}

interface Summary {
  total: number;
  bySeverity: Record<string, number>;
  byCategory: Record<string, number>;
  resolved: number;
  unresolved: number;
}

interface RemainingItemsClientProps {
  assessmentId: string;
  companyName: string;
  initialItems: RemainingItem[];
  summary: Summary;
}

const CATEGORY_LABELS: Record<string, string> = {
  unreviewed_step: "Unreviewed Step",
  maybe_scope: "Undecided Scope",
  excluded_recommended_config: "Excluded Config",
  out_of_scope_gap: "Deferred Gap",
  integration_point: "Integration Point",
  data_migration: "Data Migration",
  custom_requirement: "Custom Requirement",
};

const SEVERITY_CONFIG: Record<string, { color: string; bg: string; border: string }> = {
  critical: { color: "text-red-700", bg: "bg-red-50", border: "border-red-200" },
  high: { color: "text-orange-700", bg: "bg-orange-50", border: "border-orange-200" },
  medium: { color: "text-amber-700", bg: "bg-amber-50", border: "border-amber-200" },
  low: { color: "text-gray-600", bg: "bg-gray-50", border: "border-gray-200" },
};

export function RemainingItemsClient({
  assessmentId,
  companyName,
  initialItems,
  summary: initialSummary,
}: RemainingItemsClientProps) {
  const [items, setItems] = useState(initialItems);
  const [summary, setSummary] = useState(initialSummary);
  const [categoryFilter, setCategoryFilter] = useState<string>("all");
  const [severityFilter, setSeverityFilter] = useState<string>("all");
  const [resolvedFilter, setResolvedFilter] = useState<string>("all");
  const [searchTerm, setSearchTerm] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [showAddForm, setShowAddForm] = useState(false);
  const [addForm, setAddForm] = useState({
    category: "custom_requirement",
    title: "",
    description: "",
    severity: "medium",
    functionalArea: "",
    assignedTo: "",
  });

  const filteredItems = useMemo(() => {
    let result = items;
    if (categoryFilter !== "all") {
      result = result.filter((i) => i.category === categoryFilter);
    }
    if (severityFilter !== "all") {
      result = result.filter((i) => i.severity === severityFilter);
    }
    if (resolvedFilter === "resolved") {
      result = result.filter((i) => i.resolvedAt !== null);
    } else if (resolvedFilter === "unresolved") {
      result = result.filter((i) => i.resolvedAt === null);
    }
    if (searchTerm.trim()) {
      const term = searchTerm.toLowerCase();
      result = result.filter(
        (i) =>
          i.title.toLowerCase().includes(term) ||
          i.description.toLowerCase().includes(term),
      );
    }
    return result;
  }, [items, categoryFilter, severityFilter, resolvedFilter, searchTerm]);

  const handleAutoGenerate = async () => {
    setGenerating(true);
    try {
      const res = await fetch(`/api/assessments/${assessmentId}/remaining/auto-generate`, {
        method: "POST",
      });
      if (res.ok) {
        // Refresh items
        const listRes = await fetch(`/api/assessments/${assessmentId}/remaining`);
        if (listRes.ok) {
          const data = await listRes.json() as { data: RemainingItem[]; summary: Summary };
          setItems(data.data);
          setSummary(data.summary);
        }
      }
    } finally {
      setGenerating(false);
    }
  };

  const handleAddItem = async () => {
    if (!addForm.title || !addForm.description) return;

    const res = await fetch(`/api/assessments/${assessmentId}/remaining`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        category: addForm.category,
        title: addForm.title,
        description: addForm.description,
        severity: addForm.severity,
        functionalArea: addForm.functionalArea || undefined,
        assignedTo: addForm.assignedTo || undefined,
      }),
    });

    if (res.ok) {
      const data = await res.json() as { data: RemainingItem };
      setItems((prev) => [...prev, data.data]);
      setSummary((prev) => ({
        ...prev,
        total: prev.total + 1,
        unresolved: prev.unresolved + 1,
        bySeverity: {
          ...prev.bySeverity,
          [addForm.severity]: (prev.bySeverity[addForm.severity] ?? 0) + 1,
        },
        byCategory: {
          ...prev.byCategory,
          [addForm.category]: (prev.byCategory[addForm.category] ?? 0) + 1,
        },
      }));
      setShowAddForm(false);
      setAddForm({
        category: "custom_requirement",
        title: "",
        description: "",
        severity: "medium",
        functionalArea: "",
        assignedTo: "",
      });
    }
  };

  const handleExport = () => {
    window.open(`/api/assessments/${assessmentId}/report/remaining-register`, "_blank");
  };

  return (
    <div className="max-w-6xl mx-auto">
      <PageHeader
        title="Remaining Items"
        description={`${companyName} — items requiring post-assessment action`}
        actions={
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => void handleAutoGenerate()} disabled={generating}>
              <RefreshCw className={`w-4 h-4 mr-1.5 ${generating ? "animate-spin" : ""}`} />
              {generating ? "Scanning..." : "Auto-Detect"}
            </Button>
            <Button variant="outline" onClick={handleExport}>
              <Download className="w-4 h-4 mr-1.5" />
              Export XLSX
            </Button>
            <Button onClick={() => setShowAddForm(true)}>
              <Plus className="w-4 h-4 mr-1.5" />
              Add Item
            </Button>
          </div>
        }
      />

      {/* Summary cards */}
      <div className="grid grid-cols-4 gap-4 mb-6">
        <SummaryCard label="Total Items" value={summary.total} />
        <SummaryCard label="Critical" value={summary.bySeverity["critical"] ?? 0} variant="critical" />
        <SummaryCard label="High" value={summary.bySeverity["high"] ?? 0} variant="high" />
        <SummaryCard label="Resolved" value={summary.resolved} variant="resolved" />
      </div>

      {/* Filters */}
      <div className="flex gap-3 mb-4 flex-wrap">
        <select
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
          className="border rounded-md px-2 py-1.5 text-sm"
        >
          <option value="all">All Categories</option>
          {Object.entries(CATEGORY_LABELS).map(([key, label]) => (
            <option key={key} value={key}>{label}</option>
          ))}
        </select>
        <select
          value={severityFilter}
          onChange={(e) => setSeverityFilter(e.target.value)}
          className="border rounded-md px-2 py-1.5 text-sm"
        >
          <option value="all">All Severities</option>
          <option value="critical">Critical</option>
          <option value="high">High</option>
          <option value="medium">Medium</option>
          <option value="low">Low</option>
        </select>
        <select
          value={resolvedFilter}
          onChange={(e) => setResolvedFilter(e.target.value)}
          className="border rounded-md px-2 py-1.5 text-sm"
        >
          <option value="all">All Status</option>
          <option value="unresolved">Unresolved</option>
          <option value="resolved">Resolved</option>
        </select>
        <input
          type="text"
          placeholder="Search items..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="border rounded-md px-3 py-1.5 text-sm flex-1 min-w-[200px]"
        />
      </div>

      {/* Add item form */}
      {showAddForm && (
        <div className="bg-card border rounded-lg p-4 mb-4">
          <h3 className="text-sm font-medium text-foreground mb-3">Add Remaining Item</h3>
          <div className="grid grid-cols-2 gap-3 mb-3">
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Category</label>
              <select
                value={addForm.category}
                onChange={(e) => setAddForm((prev) => ({ ...prev, category: e.target.value }))}
                className="w-full border rounded px-2 py-1.5 text-sm"
              >
                <option value="integration_point">Integration Point</option>
                <option value="data_migration">Data Migration</option>
                <option value="custom_requirement">Custom Requirement</option>
              </select>
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Severity</label>
              <select
                value={addForm.severity}
                onChange={(e) => setAddForm((prev) => ({ ...prev, severity: e.target.value }))}
                className="w-full border rounded px-2 py-1.5 text-sm"
              >
                <option value="critical">Critical</option>
                <option value="high">High</option>
                <option value="medium">Medium</option>
                <option value="low">Low</option>
              </select>
            </div>
          </div>
          <div className="mb-3">
            <label className="block text-xs text-muted-foreground mb-1">Title</label>
            <input
              type="text"
              value={addForm.title}
              onChange={(e) => setAddForm((prev) => ({ ...prev, title: e.target.value }))}
              placeholder="Brief title (min 5 characters)"
              className="w-full border rounded px-2 py-1.5 text-sm"
            />
          </div>
          <div className="mb-3">
            <label className="block text-xs text-muted-foreground mb-1">Description</label>
            <textarea
              value={addForm.description}
              onChange={(e) => setAddForm((prev) => ({ ...prev, description: e.target.value }))}
              placeholder="Detailed description (min 10 characters)"
              rows={3}
              className="w-full border rounded px-2 py-1.5 text-sm"
            />
          </div>
          <div className="grid grid-cols-2 gap-3 mb-3">
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Functional Area (optional)</label>
              <input
                type="text"
                value={addForm.functionalArea}
                onChange={(e) => setAddForm((prev) => ({ ...prev, functionalArea: e.target.value }))}
                className="w-full border rounded px-2 py-1.5 text-sm"
              />
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">Assigned To (optional email)</label>
              <input
                type="email"
                value={addForm.assignedTo}
                onChange={(e) => setAddForm((prev) => ({ ...prev, assignedTo: e.target.value }))}
                className="w-full border rounded px-2 py-1.5 text-sm"
              />
            </div>
          </div>
          <div className="flex gap-2">
            <Button size="sm" onClick={() => void handleAddItem()} disabled={addForm.title.length < 5 || addForm.description.length < 10}>
              Add Item
            </Button>
            <Button size="sm" variant="outline" onClick={() => setShowAddForm(false)}>
              Cancel
            </Button>
          </div>
        </div>
      )}

      {/* Items table */}
      {filteredItems.length === 0 ? (
        <EmptyState
          title="No Remaining Items"
          description={items.length === 0
            ? "Use Auto-Detect to scan the assessment for items requiring attention, or add items manually."
            : "No items match the current filters."}
        />
      ) : (
        <div className="bg-card border rounded-lg overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-muted/40 border-b border text-left">
                <th className="px-4 py-2 font-medium text-muted-foreground w-8">#</th>
                <th className="px-4 py-2 font-medium text-muted-foreground">Category</th>
                <th className="px-4 py-2 font-medium text-muted-foreground">Title</th>
                <th className="px-4 py-2 font-medium text-muted-foreground">Severity</th>
                <th className="px-4 py-2 font-medium text-muted-foreground">Area</th>
                <th className="px-4 py-2 font-medium text-muted-foreground">Status</th>
                <th className="px-4 py-2 font-medium text-muted-foreground w-8" />
              </tr>
            </thead>
            <tbody>
              {filteredItems.map((item, idx) => {
                const isExpanded = expandedId === item.id;
                const severity = SEVERITY_CONFIG[item.severity] ?? SEVERITY_CONFIG["low"]!;
                return (
                  <>
                    <tr
                      key={item.id}
                      className={`border-b border hover:bg-accent cursor-pointer ${isExpanded ? "bg-muted/40" : ""}`}
                      onClick={() => setExpandedId(isExpanded ? null : item.id)}
                    >
                      <td className="px-4 py-2.5 text-muted-foreground/60">{idx + 1}</td>
                      <td className="px-4 py-2.5">
                        <Badge variant="outline" className="text-xs">
                          {CATEGORY_LABELS[item.category] ?? item.category}
                        </Badge>
                      </td>
                      <td className="px-4 py-2.5 font-medium text-foreground">{item.title}</td>
                      <td className="px-4 py-2.5">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${severity.bg} ${severity.color} ${severity.border} border`}>
                          {item.severity}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-muted-foreground">{item.functionalArea ?? "—"}</td>
                      <td className="px-4 py-2.5">
                        {item.resolvedAt ? (
                          <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200 text-xs">
                            Resolved
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="bg-amber-50 text-amber-700 border-amber-200 text-xs">
                            Open
                          </Badge>
                        )}
                      </td>
                      <td className="px-4 py-2.5">
                        {isExpanded ? (
                          <ChevronUp className="w-4 h-4 text-muted-foreground/60" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-muted-foreground/60" />
                        )}
                      </td>
                    </tr>
                    {isExpanded && (
                      <tr key={`${item.id}-detail`} className="bg-muted/40">
                        <td colSpan={7} className="px-4 py-3">
                          <div className="text-sm text-muted-foreground space-y-2">
                            <p>{item.description}</p>
                            <div className="flex gap-6 text-xs text-muted-foreground">
                              {item.assignedTo && <span>Assigned: {item.assignedTo}</span>}
                              {item.autoGenerated && <span>Auto-generated</span>}
                              <span>Created: {new Date(item.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}</span>
                              {item.resolvedAt && (
                                <span>Resolved: {new Date(item.resolvedAt).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })} by {item.resolvedBy ?? "—"}</span>
                              )}
                              {item.resolution && <span>Resolution: {item.resolution}</span>}
                            </div>
                          </div>
                        </td>
                      </tr>
                    )}
                  </>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      <p className="text-xs text-muted-foreground/60 mt-2">
        Showing {filteredItems.length} of {items.length} items
      </p>

      {/* Navigation */}
      <div className="flex items-center justify-between pt-6 mt-8 border-t border">
        <Link href={`/assessment/${assessmentId}/flows`}>
          <Button variant="outline">
            <ArrowLeft className="w-4 h-4 mr-1.5" />
            Flow Diagrams
          </Button>
        </Link>
        <Link href={`/assessment/${assessmentId}/report`}>
          <Button>
            Report &amp; Sign-Off
          </Button>
        </Link>
      </div>
    </div>
  );
}

function SummaryCard({
  label,
  value,
  variant,
}: {
  label: string;
  value: number;
  variant?: "critical" | "high" | "resolved" | undefined;
}) {
  const colorClass =
    variant === "critical"
      ? "text-red-600"
      : variant === "high"
        ? "text-orange-600"
        : variant === "resolved"
          ? "text-green-600"
          : "text-foreground";

  return (
    <div className="bg-card rounded-lg border p-4 text-center">
      <p className="text-xs text-muted-foreground/60 uppercase tracking-wider">{label}</p>
      <p className={`text-2xl font-bold mt-1 ${colorClass}`}>{value}</p>
    </div>
  );
}
