/**
 * The CoreEdge status vocabulary — the ONLY place a status becomes words.
 *
 * Generated by hand from `docs/coreedge/design/A5-CoreEdge-Status-Vocabulary.csv`
 * and section 5 of `docs/coreedge/design/CoreEdge Engineering Handoff.dc.html`.
 * Both are committed, so every value below can be checked against its source.
 *
 * WHY ONE MODULE. The audit found 87 distinct status literals across the
 * codebase, spelled in at least four conventions — SCREAMING_SNAKE enums,
 * lowercase strings, Title Case prose and severity words — and mapped to colour
 * in nine different components. A lane's status is the single most consequential
 * thing this console says, and it was being decided nine times. Everything the
 * new console renders resolves through this file, and
 * `tests/unit/coreedge/status-vocabulary.test.ts` fails if any of those 87
 * literals has no mapping, so a new backend status cannot reach a screen as an
 * unstyled raw string.
 *
 * WHAT IS DELIBERATELY ABSENT: a "checking" status. The handoff is explicit —
 * "there is no 'checking' status — that would be a nineteenth vocabulary entry
 * for a transient." A lane keeps its last known status while a re-check runs.
 */

/* ─────────────────────────────────────────────────────────────────────────────
 * Tokens and glyphs
 * ────────────────────────────────────────────────────────────────────────── */

/**
 * The five chip tokens. These are token NAMES, resolved by
 * `src/app/coreedge-tokens.css` — never colours.
 */
export const GATE_TOKENS = ["gate-ok", "gate-info", "gate-wait", "gate-bad", "gate-off"] as const;
export type GateToken = (typeof GATE_TOKENS)[number];

/**
 * THE GLYPH IS A CONTRACT, NOT DECORATION, and it hangs off the token rather
 * than off the status so that it cannot be omitted for one status and not
 * another.
 *
 * PR-1 measured the reason: in dark mode the fifteen pairwise contrasts between
 * the six status grounds all sit between 1.01:1 and 1.10:1
 * (`tests/unit/coreedge/token-contrast.test.ts`). Colour alone does not
 * distinguish them for anyone — not only for colour-blind users. The glyph is
 * what carries the meaning; the colour merely agrees with it.
 */
export const GATE_GLYPHS: Readonly<Record<GateToken, string>> = {
  "gate-ok": "✓",
  "gate-info": "i",
  "gate-wait": "…",
  "gate-bad": "✕",
  "gate-off": "–",
};

/* ─────────────────────────────────────────────────────────────────────────────
 * The six hops
 * ────────────────────────────────────────────────────────────────────────── */

/**
 * A lane is six hops, in this order. From A1 section 5: "Key → Access → Binding
 * → SAP metadata → SAP data read → App".
 */
export const LANE_HOPS = ["key", "access", "binding", "sapMetadata", "sapDataRead", "app"] as const;
export type LaneHop = (typeof LANE_HOPS)[number];

export const HOP_LABELS: Readonly<Record<LaneHop, string>> = {
  key: "Key",
  access: "Access",
  binding: "Binding",
  sapMetadata: "SAP metadata",
  sapDataRead: "SAP data read",
  app: "Your app",
};

/**
 * RECONCILIATION, RECORDED BECAUSE THE TWO SOURCES DISAGREE.
 *
 * A1 and the handoff's WhyTrace entry both name the same six hops. The handoff's
 * section 5 table, however, fills its "Broken hop" column with two labels that
 * are not among them — `Traffic` and `SAP system` — and uses `Binding` for a
 * third status that is plainly the same hop as the `SAP system` ones. So the
 * handoff carries two vocabularies and this file has to pick one.
 *
 * It picks the six, because they are what the trace renders and what A1 states
 * normatively. The two odd labels are resolved as:
 *
 *   · `SAP system`  → `binding`. The binding hop IS "is there exactly one usable
 *     SAP system for this environment". All four statuses the handoff files
 *     under `SAP system` (No SAP system, System off, Secret unreadable) plus the
 *     one it already files under `Binding` (Binding refused) are the same
 *     question failing for four different reasons, and share one owner:
 *     platform admin.
 *   · `Traffic`     → `null`. It appears once, on `No data`, whose own row says
 *     "SAP answered and had nothing to return. A success." Nothing is broken, so
 *     no hop is named. Recording `Traffic` as a broken hop would put a failure
 *     marker on a lane that worked.
 *
 * Each status keeps the handoff's verbatim column value in `handoffHopLabel`, so
 * the mapping is auditable and nothing from the source is silently discarded.
 */
export type HandoffHopLabel =
  | "—"
  | "Traffic"
  | "Access"
  | "Key"
  | "Binding"
  | "SAP system"
  | "SAP metadata"
  | "SAP data read";

/* ─────────────────────────────────────────────────────────────────────────────
 * Owners
 * ────────────────────────────────────────────────────────────────────────── */

/**
 * Who fixes it. The handoff's rule: "A status earns its own wording only when it
 * changes who fixes it — that is why 401 and 403 are separate". The owner is
 * therefore load-bearing, not annotation: it is the reason two statuses exist
 * where one colour would do.
 */
export const STATUS_OWNERS = [
  "appOwner",
  "reviewer",
  "platformAdmin",
  "clientSapAdmin",
  "clientBasisTeam",
  "operator",
] as const;
export type StatusOwner = (typeof STATUS_OWNERS)[number];

export const OWNER_LABELS: Readonly<Record<StatusOwner, string>> = {
  appOwner: "App owner",
  reviewer: "Reviewer",
  platformAdmin: "Platform admin",
  clientSapAdmin: "Client SAP admin",
  clientBasisTeam: "Client Basis team",
  operator: "Operator",
};

/* ─────────────────────────────────────────────────────────────────────────────
 * The eighteen lane statuses
 * ────────────────────────────────────────────────────────────────────────── */

export const LANE_STATUSES = [
  "live",
  "noData",
  "inReview",
  "noAccess",
  "accessEnded",
  "noKey",
  "keyNotValid",
  "rateLimited",
  "bindingRefused",
  "noSapSystem",
  "systemOff",
  "secretUnreadable",
  "signInRefused",
  "sapRefused",
  "sapUnavailable",
  "circuitOpen",
  "unknown",
  "notStarted",
] as const;
export type LaneStatus = (typeof LANE_STATUSES)[number];

export interface LaneStatusDefinition {
  /** The words on the chip. Never construct this — the label IS the status. */
  readonly label: string;
  readonly token: GateToken;
  /** The hop that failed, or null when nothing failed. See the reconciliation above. */
  readonly brokenHop: LaneHop | null;
  /** The handoff's own "Broken hop" column, verbatim, so the mapping is checkable. */
  readonly handoffHopLabel: HandoffHopLabel;
  /** Who fixes it. Null only where the handoff's Owner column is "—". */
  readonly owner: StatusOwner | null;
  /** The handoff's "Means" column, verbatim. Shown in WhyTrace and the ops legend. */
  readonly means: string;
}

/**
 * Transcribed row for row from the handoff's section 5 table. The `means` strings
 * are verbatim; changing one is changing what the console claims.
 */
export const LANE_STATUS_VOCABULARY: Readonly<Record<LaneStatus, LaneStatusDefinition>> = {
  live: {
    label: "Live",
    token: "gate-ok",
    brokenHop: null,
    handoffHopLabel: "—",
    owner: null,
    means: "Proven end to end, as of the age shown beside it.",
  },
  noData: {
    label: "No data",
    token: "gate-info",
    brokenHop: null,
    handoffHopLabel: "Traffic",
    owner: null,
    means: "SAP answered and had nothing to return. A success.",
  },
  inReview: {
    label: "In review",
    token: "gate-wait",
    brokenHop: "access",
    handoffHopLabel: "Access",
    owner: "reviewer",
    means: "Requested; a decision is pending.",
  },
  noAccess: {
    label: "No access",
    token: "gate-bad",
    brokenHop: "access",
    handoffHopLabel: "Access",
    owner: "reviewer",
    means: "No approved access for this feed in this environment.",
  },
  accessEnded: {
    label: "Access ended",
    token: "gate-bad",
    brokenHop: "access",
    handoffHopLabel: "Access",
    owner: "reviewer",
    means: "Reached its end date. The key survives; renewing keeps it.",
  },
  noKey: {
    label: "No key",
    token: "gate-wait",
    brokenHop: "key",
    handoffHopLabel: "Key",
    owner: "appOwner",
    means: "Access approved, no key collected — or it was revoked.",
  },
  keyNotValid: {
    label: "Key not valid",
    token: "gate-bad",
    brokenHop: "key",
    handoffHopLabel: "Key",
    owner: "appOwner",
    means: "Revoked, replaced, unknown, or the app is retired.",
  },
  rateLimited: {
    label: "Rate limited",
    token: "gate-wait",
    brokenHop: "key",
    handoffHopLabel: "Key",
    owner: "appOwner",
    means: "60 calls/min per key reached. Nothing sent to SAP.",
  },
  bindingRefused: {
    label: "Binding refused",
    token: "gate-bad",
    brokenHop: "binding",
    handoffHopLabel: "Binding",
    owner: "platformAdmin",
    means: "Two systems claim one environment; CoreEdge will not choose.",
  },
  noSapSystem: {
    label: "No SAP system",
    token: "gate-bad",
    brokenHop: "binding",
    handoffHopLabel: "SAP system",
    owner: "platformAdmin",
    means: "No system connected for this environment yet.",
  },
  systemOff: {
    label: "System off",
    token: "gate-wait",
    brokenHop: "binding",
    handoffHopLabel: "SAP system",
    owner: "platformAdmin",
    means: "Deactivated on purpose. Reversible; the reason is shown.",
  },
  secretUnreadable: {
    label: "Secret unreadable",
    token: "gate-bad",
    brokenHop: "binding",
    handoffHopLabel: "SAP system",
    owner: "platformAdmin",
    means: "CoreEdge cannot decrypt its own stored secret. Our fault.",
  },
  signInRefused: {
    // The handoff writes this label with a middot: "401 · could not sign in".
    label: "401 · could not sign in",
    token: "gate-bad",
    brokenHop: "sapMetadata",
    handoffHopLabel: "SAP metadata",
    owner: "platformAdmin",
    means: "SAP rejected our sign-in. Every lane on that system stops.",
  },
  sapRefused: {
    label: "SAP refused",
    token: "gate-bad",
    brokenHop: "sapDataRead",
    handoffHopLabel: "SAP data read",
    owner: "clientSapAdmin",
    means: "We signed in; SAP refused one entity (403). One lane stops.",
  },
  sapUnavailable: {
    label: "SAP unavailable",
    token: "gate-wait",
    brokenHop: "sapDataRead",
    handoffHopLabel: "SAP data read",
    owner: "clientBasisTeam",
    means: "Timeouts or 5xx. Nothing refused; we stopped calling.",
  },
  circuitOpen: {
    label: "Circuit open",
    token: "gate-wait",
    brokenHop: "sapDataRead",
    handoffHopLabel: "SAP data read",
    owner: "clientBasisTeam",
    means: "Calls refused fast while the system recovers. Retry time shown.",
  },
  unknown: {
    label: "Unknown",
    token: "gate-off",
    brokenHop: null,
    handoffHopLabel: "—",
    owner: "operator",
    means: "No check within 24 h. A claim about us, not the lane.",
  },
  notStarted: {
    label: "Not started",
    token: "gate-off",
    brokenHop: null,
    handoffHopLabel: "—",
    owner: "appOwner",
    means: "Nothing requested for this environment yet.",
  },
};

/** The glyph for a status. Derived from its token, so no status can lack one. */
export function glyphFor(status: LaneStatus): string {
  return GATE_GLYPHS[LANE_STATUS_VOCABULARY[status].token];
}

/** Glyph and label together, the way a chip reads aloud: "✕ No access". */
export function chipTextFor(status: LaneStatus): string {
  return `${glyphFor(status)} ${LANE_STATUS_VOCABULARY[status].label}`;
}

/* ─────────────────────────────────────────────────────────────────────────────
 * The 87 literals the codebase already speaks
 * ────────────────────────────────────────────────────────────────────────── */

/**
 * Which part of the system a literal comes from. Two literals can share a
 * spelling and mean different things — `NOT_FOUND` is a catalogue badge, a read
 * result and a write result — so the audit disambiguated them with a suffix and
 * that spelling is kept here verbatim.
 */
export type LiteralDomain =
  | "catalogueBadge"
  | "solutionStatus"
  | "interfaceStatus"
  | "grantDecision"
  | "connectionHealth"
  | "legacyHealthProse"
  | "signoffLifecycle"
  | "severityWord"
  | "importFreshness"
  | "readResult"
  | "writeResult"
  | "testResult"
  | "dataState"
  | "environment"
  | "operation"
  | "trigger"
  | "auditAction";

export interface StatusLiteralMapping {
  /** Exactly as the audit recorded it, suffix and all. */
  readonly literal: string;
  readonly domain: LiteralDomain;
  /**
   * The lane status this literal resolves to, or null when the literal is not a
   * lane status at all. `null` is never silent: `note` says why, and the test
   * refuses an entry whose note does not explain itself.
   */
  readonly lane: LaneStatus | null;
  readonly note: string;
}

/**
 * Every status literal the audit found, and what the new console does with it.
 *
 * WHY SO MANY RESOLVE TO `null`. A third of the 87 are not statuses in the lane
 * sense at all — four are environments, four are operations, three are trigger
 * kinds, five are audit action names, seven are assessment sign-off states from
 * presales, and nine are severity words (`good`, `bad`, `critical`, `minor`)
 * that encode a colour rather than a condition. Forcing `SANDBOX` or `cron` onto
 * one of the eighteen would put a false claim on a chip. `null` means "this
 * never becomes a lane chip", which is a mapping decision, not a missing one —
 * and the test holds a null entry to the same standard as any other.
 *
 * The severity words deserve their own note, because they are the habit this
 * file exists to end: the old console decided colour from a severity word passed
 * down from a caller. The new one derives colour from the status via its token,
 * so a severity word has nowhere to go and nothing to say.
 */
export const STATUS_LITERAL_MAP: readonly StatusLiteralMapping[] = [
  // ── Capability catalogue badges ───────────────────────────────────────────
  {
    literal: "ACTIVATED",
    domain: "catalogueBadge",
    lane: "live",
    note: "A5 renders this as 'Reachable (metadata) / Reads proven' — one badge for two conditions the lane vocabulary separates. Only the reads-proven half is Live; a metadata-only activation has not proven the SAP data read hop. The conflation is in the badge, not here: a lane resolves Live from its own read check.",
  },
  {
    literal: "NEEDS_SETUP",
    domain: "catalogueBadge",
    lane: "sapRefused",
    note: "A5's plain label for this badge is 'SAP refused'. The fix is in SAP authorisation, so the owner is the client SAP admin.",
  },
  {
    literal: "AVAILABLE",
    domain: "catalogueBadge",
    lane: null,
    note: "'Event — subscribe only' (A5). An event capability has no read lane to be a status of; there is nothing to prove end to end.",
  },
  {
    literal: "NOT_PROBEABLE",
    domain: "catalogueBadge",
    lane: "unknown",
    note: "'No OData endpoint' (A5). Nothing can be proven, which is exactly Unknown's meaning — 'a claim about us, not the lane'.",
  },
  {
    literal: "PROBE_FAILED",
    domain: "catalogueBadge",
    lane: "unknown",
    note: "Too coarse to place a blame: A5 resolves 'Probe failed' into UNAUTHORIZED, NOT_FOUND or TIMEOUT, which have three different owners. Without the specific health code the honest chip is Unknown; the connectionHealth entries below carry the real mappings.",
  },
  {
    literal: "REFERENCE",
    domain: "catalogueBadge",
    lane: null,
    note: "'Design-time content' (A5). Reference material is not served through a lane.",
  },
  {
    literal: "NOT_CHECKED",
    domain: "catalogueBadge",
    lane: "unknown",
    note: "A5 pairs NOT_CHECKED with STALE under 'Unknown · last proven <age>', TTL 30 d. The lane's Unknown is the same claim at 24 h.",
  },
  {
    literal: "NOT_FOUND",
    domain: "catalogueBadge",
    lane: null,
    note: "GAP. 'Not on this SAP system' (A5). The eighteen statuses have no entry for a dataset that does not exist — A6's Why? deck does ('{dataset} doesn't exist on {system}', owner Builder, action Choose another dataset), so the copy is written and the chip is not. Rendering this as SAP refused would send the user to their SAP admin over a 404 that a different dataset would fix. Needs a design decision.",
  },

  // ── Solution (App) status ─────────────────────────────────────────────────
  {
    literal: "DRAFT",
    domain: "solutionStatus",
    lane: "notStarted",
    note: "'Being set up' (A5). An app in draft has requested nothing for any environment.",
  },
  {
    literal: "ACTIVE",
    domain: "solutionStatus",
    lane: null,
    note: "An app being active says nothing about any one lane — every lane under an active app still resolves from its own six hops. This is an app-level chip, rendered from APP_STATUS_VOCABULARY below.",
  },
  {
    literal: "RESTRICTED",
    domain: "solutionStatus",
    lane: null,
    note: "DECISION D3: Restricted is an APP status and never a nineteenth lane status. No new access is requested or approved while it holds; existing lanes keep serving and keep their own statuses. Rendered once at app level as 'Restricted · no new access'.",
  },
  {
    literal: "RETIRED",
    domain: "solutionStatus",
    lane: "keyNotValid",
    note: "The handoff's own Means for Key not valid names this case: 'Revoked, replaced, unknown, or the app is retired.' Northbound refuses on both paths via checkSolutionRuntime.",
  },

  // ── Interface (data feed) status ──────────────────────────────────────────
  {
    literal: "DRAFT (interface)",
    domain: "interfaceStatus",
    lane: null,
    note: "'Served with DRAFT header' (A5) — the feed still serves, so the lane's status comes from its hops as usual. The draft-ness is a property of the feed, shown on the feed.",
  },
  {
    literal: "ACTIVE (interface)",
    domain: "interfaceStatus",
    lane: null,
    note: "A published feed is the ordinary case and adds nothing to the lane's status.",
  },
  {
    literal: "DEPRECATED",
    domain: "interfaceStatus",
    lane: null,
    note: "GAP. A5 gives the refusal copy ('Feed retired', 403 INTERFACE_DEPRECATED) but the eighteen statuses have no chip for it. The nearest, No access, reads 'No approved access for this feed in this environment' and its action is Request access — which would send the user to a reviewer who cannot help, for a feed that is gone. Needs a design decision rather than the closest wrong answer.",
  },

  // ── Grant (Access) decisions ──────────────────────────────────────────────
  {
    literal: "REQUESTED",
    domain: "grantDecision",
    lane: "inReview",
    note: "'Requested; a decision is pending.' Owner is the reviewer.",
  },
  {
    literal: "APPROVED",
    domain: "grantDecision",
    lane: null,
    note: "Approved access does not make a lane live — it clears the Access hop and leaves Key, Binding, SAP metadata and SAP data read still to prove. The lane resolves from the first hop still failing.",
  },
  {
    literal: "SANDBOX_ONLY",
    domain: "grantDecision",
    lane: null,
    note: "DECISION D2: kept so historical rows keep meaning what they meant, never offered again. Rendered 'Approved for Sandbox (historical)'. Like APPROVED it clears the Access hop for Sandbox only and determines no lane status by itself.",
  },
  {
    literal: "READ_ONLY",
    domain: "grantDecision",
    lane: null,
    note: "Clears the Access hop for reads. Like APPROVED, it is not itself a lane status; it constrains which operations the lane may carry.",
  },
  {
    literal: "REJECTED",
    domain: "grantDecision",
    lane: "noAccess",
    note: "A5 renders the decision as 'Declined' and notes the reason is not captured today — see the backend gap list. The lane chip is No access, whose action sends the builder back to the reviewer.",
  },
  {
    literal: "EXPIRED",
    domain: "grantDecision",
    lane: "accessEnded",
    note: "'Reached its end date. The key survives; renewing keeps it.' This is why Access ended and No access are separate statuses: renewal, not a new request.",
  },
  {
    literal: "REVOKED",
    domain: "grantDecision",
    lane: "noAccess",
    note: "A5: 'Access withdrawn', admin only. The lane has no approved access, and unlike EXPIRED there is nothing to renew.",
  },

  // ── Connection health (probe outcomes) ────────────────────────────────────
  {
    literal: "OK",
    domain: "connectionHealth",
    lane: null,
    note: "A5 is explicit that a health probe 'probes one service only' and means 'Metadata OK'. That clears the SAP metadata hop and says nothing about the SAP data read hop, which is the one that separates Live from SAP refused. Promoting a green probe to Live is precisely the overclaim the lane model exists to prevent.",
  },
  {
    literal: "UNAUTHORIZED",
    domain: "connectionHealth",
    lane: "signInRefused",
    note: "SAP rejected CoreEdge's sign-in. Owner is the platform admin and the blast radius is every lane on that system — which is why the vocabulary keeps 401 and 403 apart.",
  },
  {
    literal: "TIMEOUT",
    domain: "connectionHealth",
    lane: "sapUnavailable",
    note: "'No answer' (A5). Nothing was refused; the client Basis team owns it.",
  },
  {
    literal: "NOT_FOUND",
    domain: "connectionHealth",
    lane: null,
    note: "GAP, the same one as the catalogue badge: 'Probed service missing' (A5) has no chip among the eighteen. The audit records NOT_FOUND once because it deduplicated by spelling, but the literal is genuinely two things — a catalogue badge and a probe outcome (src/lib/studio/connection-health.ts:34) — so it is mapped once per domain and a fix has to cover both.",
  },
  {
    literal: "ERROR",
    domain: "connectionHealth",
    lane: "sapUnavailable",
    note: "The probe reached SAP and got an HTTP status it could not interpret (src/lib/studio/connection-health.ts:84,125). Grouped with TIMEOUT because the handoff's Means for SAP unavailable is 'Timeouts or 5xx' and both belong to the client Basis team. A5 omits this row from its Connection health block even though the enum has carried it all along — which is how it came to be the one literal missing from the first draft of this table.",
  },
  {
    literal: "NO_PROBE_PATH",
    domain: "connectionHealth",
    lane: "unknown",
    note: "'Nothing to probe' (A5). No check has run or can run, which is Unknown.",
  },
  {
    literal: "NEVER_TESTED",
    domain: "connectionHealth",
    lane: "unknown",
    note: "No check has ever returned. Unknown is a claim about our evidence, not about the SAP system.",
  },

  // ── Legacy health prose (Control Tower) ───────────────────────────────────
  {
    literal: "Healthy",
    domain: "legacyHealthProse",
    lane: "live",
    note: "Free-text health word from the existing Control Tower. Carried here so the old surfaces can be read through one vocabulary; the new console never emits it.",
  },
  {
    literal: "Needs attention",
    domain: "legacyHealthProse",
    lane: null,
    note: "Says something is wrong without saying which hop or whose job it is — the exact failure mode the eighteen statuses replace. It cannot be resolved to one of them without knowing what actually failed.",
  },
  {
    literal: "Unknown",
    domain: "legacyHealthProse",
    lane: "unknown",
    note: "The one legacy prose word that already means what the vocabulary means.",
  },
  {
    literal: "Reachable",
    domain: "legacyHealthProse",
    lane: null,
    note: "Same overclaim as connectionHealth OK: reachable is metadata, not a proven read.",
  },
  {
    literal: "never returned 200",
    domain: "legacyHealthProse",
    lane: "unknown",
    note: "A sentence rendered as a status by the existing UI. It states an absence of evidence, which is Unknown.",
  },

  // ── Assessment sign-off lifecycle (presales / affirm) ─────────────────────
  {
    literal: "draft",
    domain: "signoffLifecycle",
    lane: null,
    note: "An assessment sign-off state from presales. A different product surface with its own lifecycle; it shares no hop with a lane.",
  },
  {
    literal: "sent",
    domain: "signoffLifecycle",
    lane: null,
    note: "Assessment sign-off: issued to the customer. Not a lane.",
  },
  {
    literal: "awaiting_signoff",
    domain: "signoffLifecycle",
    lane: null,
    note: "Assessment sign-off: waiting on a customer signature. Not a lane, and deliberately not folded into In review, which is about an access decision by a colleague.",
  },
  {
    literal: "signed",
    domain: "signoffLifecycle",
    lane: null,
    note: "Assessment sign-off: countersigned. Not a lane.",
  },
  {
    literal: "expired",
    domain: "signoffLifecycle",
    lane: null,
    note: "Assessment sign-off link expiry. Shares a spelling with grant EXPIRED and means something unrelated — which is why domain is part of the key.",
  },
  {
    literal: "revoked",
    domain: "signoffLifecycle",
    lane: null,
    note: "Assessment sign-off withdrawn. Shares a spelling with grant REVOKED; unrelated.",
  },
  {
    literal: "superseded",
    domain: "signoffLifecycle",
    lane: null,
    note: "Replaced by a later assessment version. Not a lane.",
  },

  // ── Severity words ────────────────────────────────────────────────────────
  {
    literal: "good",
    domain: "severityWord",
    lane: null,
    note: "A severity, not a status: it names a colour and leaves the condition unsaid. The new console derives colour from the status via its gate token, so a severity word has nowhere to go — this is the habit the one-vocabulary rule exists to end.",
  },
  {
    literal: "attention",
    domain: "severityWord",
    lane: null,
    note: "Severity word. See `good`.",
  },
  {
    literal: "bad",
    domain: "severityWord",
    lane: null,
    note: "Severity word. See `good`.",
  },
  {
    literal: "neutral",
    domain: "severityWord",
    lane: null,
    note: "Severity word. See `good`.",
  },
  {
    literal: "info",
    domain: "severityWord",
    lane: null,
    note: "Severity word. See `good`. Not to be confused with the gate-info token, which is chosen by a status rather than passed in by a caller.",
  },
  {
    literal: "muted",
    domain: "severityWord",
    lane: null,
    note: "Severity word. See `good`.",
  },
  {
    literal: "critical",
    domain: "severityWord",
    lane: null,
    note: "Severity word from the findings surfaces. See `good`.",
  },
  {
    literal: "major",
    domain: "severityWord",
    lane: null,
    note: "Severity word from the findings surfaces. See `good`.",
  },
  {
    literal: "minor",
    domain: "severityWord",
    lane: null,
    note: "Severity word from the findings surfaces. See `good`.",
  },

  // ── SAP content import freshness ──────────────────────────────────────────
  {
    literal: "CURRENT",
    domain: "importFreshness",
    lane: null,
    note: "The imported SAP content catalogue is up to date. A property of our copy of SAP's catalogue, not of any lane through it.",
  },
  {
    literal: "STALE",
    domain: "importFreshness",
    lane: "unknown",
    note: "A5 pairs STALE with NOT_CHECKED under 'Unknown · last proven <age>'. Where a lane depends on stale imported content, what we can claim about it is Unknown.",
  },
  {
    literal: "NEVER_IMPORTED",
    domain: "importFreshness",
    lane: "notStarted",
    note: "Nothing has been imported for this system, so no lane through it has been started.",
  },

  // ── Read results ──────────────────────────────────────────────────────────
  {
    literal: "OK (read)",
    domain: "readResult",
    lane: "live",
    note: "A proven read — the only evidence that makes a lane Live, and the reason connectionHealth OK does not.",
  },
  {
    literal: "EMPTY",
    domain: "readResult",
    lane: "noData",
    note: "'SAP answered and had nothing to return. A success.' A5 says the same in its own words: 'No records (not an error)'. The one status whose token is gate-info, because it is neither a failure nor proof of data.",
  },
  {
    literal: "NEEDS_SETUP (read)",
    domain: "readResult",
    lane: "sapRefused",
    note: "SAP refused the read (403) after we signed in. One entity, one lane, and the fix is in SAP.",
  },
  {
    literal: "NOT_FOUND (read)",
    domain: "readResult",
    lane: null,
    note: "GAP, third domain. A 404 on the dataset. See the catalogueBadge NOT_FOUND note — same missing chip, and the one place A6 already has the copy for it.",
  },
  {
    literal: "TIMEOUT (read)",
    domain: "readResult",
    lane: "sapUnavailable",
    note: "'SAP too slow' (A5, 504). Nothing refused; we stopped calling.",
  },
  {
    literal: "ERROR (read)",
    domain: "readResult",
    lane: "sapUnavailable",
    note: "'SAP error' (A5, 502). Grouped with timeouts because the handoff's Means for SAP unavailable is 'Timeouts or 5xx', and both are the client Basis team's.",
  },

  // ── Write results ─────────────────────────────────────────────────────────
  {
    literal: "CREATED",
    domain: "writeResult",
    lane: "live",
    note: "A proven write. The lane model is written around reads; a successful write is the same claim — the six hops held end to end.",
  },
  {
    literal: "NEEDS_SETUP (write)",
    domain: "writeResult",
    lane: "sapRefused",
    note: "SAP refused the write (403). Same hop, same owner as the read case.",
  },
  {
    literal: "NOT_FOUND (write)",
    domain: "writeResult",
    lane: null,
    note: "GAP, fourth domain. See the catalogueBadge NOT_FOUND note.",
  },
  {
    literal: "REJECTED (write)",
    domain: "writeResult",
    lane: null,
    note: "GAP. SAP accepted the call and refused the CONTENT — a business-rule rejection, not an authorisation one. The eighteen statuses have no entry for it, and the nearest, SAP refused, would send the user to their SAP admin to fix a payload the app sent. Needs a design decision.",
  },
  {
    literal: "TIMEOUT (write)",
    domain: "writeResult",
    lane: "sapUnavailable",
    note: "Same as the read case: nothing refused, the client Basis team owns it.",
  },
  {
    literal: "ERROR (write)",
    domain: "writeResult",
    lane: "sapUnavailable",
    note: "Same as the read case.",
  },

  // ── Test Console run outcomes ─────────────────────────────────────────────
  {
    literal: "PASS",
    domain: "testResult",
    lane: null,
    note: "The outcome of one run someone triggered, not the state of the lane. A lane's status comes from its checks; a green run is evidence feeding them, and conflating the two would let a stale manual run keep a broken lane looking Live.",
  },
  {
    literal: "FAIL",
    domain: "testResult",
    lane: null,
    note: "See PASS. Which status a failed run produces depends on the hop it failed at, which the run result carries separately.",
  },
  {
    literal: "NOT_RUN",
    domain: "testResult",
    lane: null,
    note: "See PASS. A lane with no manual run is not thereby Unknown — its scheduled checks may be current.",
  },

  // ── Lowercase data states (Test Console / Try it) ─────────────────────────
  {
    literal: "data",
    domain: "dataState",
    lane: "live",
    note: "Lowercase spelling of a proven read, used by the Try-it panel.",
  },
  {
    literal: "empty",
    domain: "dataState",
    lane: "noData",
    note: "Lowercase spelling of EMPTY. A6: 'No records. SAP answered successfully and had nothing to return.'",
  },
  {
    literal: "needs_setup",
    domain: "dataState",
    lane: "sapRefused",
    note: "Lowercase spelling of the 403 case.",
  },
  {
    literal: "error",
    domain: "dataState",
    lane: "sapUnavailable",
    note: "Lowercase spelling of the 5xx case.",
  },

  // ── Not statuses at all ───────────────────────────────────────────────────
  {
    literal: "SANDBOX",
    domain: "environment",
    lane: null,
    note: "An environment. A lane is one app × one feed × one environment, so this is a coordinate of the lane, not a state of it.",
  },
  {
    literal: "DEV",
    domain: "environment",
    lane: null,
    note: "An environment. See SANDBOX.",
  },
  {
    literal: "TEST",
    domain: "environment",
    lane: null,
    note: "An environment. See SANDBOX.",
  },
  {
    literal: "PROD",
    domain: "environment",
    lane: null,
    note: "An environment. See SANDBOX.",
  },
  {
    literal: "READ",
    domain: "operation",
    lane: null,
    note: "An operation the lane may carry. What a lane does, not how it is.",
  },
  {
    literal: "CREATE",
    domain: "operation",
    lane: null,
    note: "An operation. See READ.",
  },
  {
    literal: "UPDATE",
    domain: "operation",
    lane: null,
    note: "An operation. See READ.",
  },
  {
    literal: "WRITE",
    domain: "operation",
    lane: null,
    note: "An operation. See READ.",
  },
  {
    literal: "cron",
    domain: "trigger",
    lane: null,
    note: "What started a check. Provenance, not a status — though it is why an Unknown lane can be Unknown: the cron did not run.",
  },
  {
    literal: "manual",
    domain: "trigger",
    lane: null,
    note: "What started a check. See cron.",
  },
  {
    literal: "test",
    domain: "trigger",
    lane: null,
    note: "What started a check. See cron.",
  },
  {
    literal: "CREATE (audit)",
    domain: "auditAction",
    lane: null,
    note: "An audit action name. Describes something a person did, not the state of anything.",
  },
  {
    literal: "UPDATE (audit)",
    domain: "auditAction",
    lane: null,
    note: "An audit action name. See CREATE (audit).",
  },
  {
    literal: "PROMOTE",
    domain: "auditAction",
    lane: null,
    note: "An audit action name: a lane was promoted to the next environment. The resulting lane status is In review, recorded under grantDecision REQUESTED.",
  },
  {
    literal: "DECISION",
    domain: "auditAction",
    lane: null,
    note: "An audit action name: a reviewer decided. The decision itself is a grantDecision literal.",
  },
  {
    literal: "TEST_CONNECT",
    domain: "auditAction",
    lane: null,
    note: "An audit action name: someone probed a connection. The probe's outcome is a connectionHealth literal.",
  },
];

/**
 * Resolve a literal to a lane status.
 *
 * Returns `undefined` for a literal this file has never heard of — deliberately
 * distinct from `null`, which means "known, and deliberately not a lane chip".
 * A caller that cannot tell those apart would render an unmapped status as if it
 * had been considered.
 */
export function laneStatusForLiteral(
  literal: string,
  domain?: LiteralDomain,
): LaneStatus | null | undefined {
  const match = STATUS_LITERAL_MAP.find(
    (m) => m.literal === literal && (domain === undefined || m.domain === domain),
  );
  return match === undefined ? undefined : match.lane;
}

/* ─────────────────────────────────────────────────────────────────────────────
 * App-level status (DECISION D3)
 * ────────────────────────────────────────────────────────────────────────── */

export const APP_STATUSES = ["draft", "active", "restricted", "retired"] as const;
export type AppStatus = (typeof APP_STATUSES)[number];

/**
 * App chips can also carry `status-expired`, which A5 assigns to RETIRED. It is
 * a real A2 token (`--status-expired-bg/-fg`, declared in both themes and
 * shipped in `src/app/coreedge-tokens.css`) but deliberately NOT one of the five
 * gate tokens: gate tokens describe a hop's condition, and a retired app has no
 * hops left to describe. The type is widened rather than the value cast, so the
 * distinction survives.
 */
export type AppChipToken = GateToken | "status-expired";

/**
 * INVENTED, AND FLAGGED AS SUCH. The design specifies glyphs for the five gate
 * tokens only (✓ i … ✕ –); `status-expired` has none anywhere in the bundle.
 * Since "every status carries a glyph" is a contract rather than a preference,
 * an app chip could not ship without one.
 *
 * `✕` is the choice: a retired app's calls are refused outright by
 * checkSolutionRuntime, so the chip makes the same hard-stop claim gate-bad
 * makes. The alternative considered was `–` (gate-off's "nothing here"), which
 * would understate it — a retired app is not dormant, it actively refuses.
 */
export const APP_CHIP_GLYPHS: Readonly<Record<AppChipToken, string>> = {
  ...GATE_GLYPHS,
  "status-expired": "✕",
};

export interface AppStatusDefinition {
  readonly label: string;
  readonly token: AppChipToken;
  readonly owner: StatusOwner | null;
  readonly means: string;
}

/**
 * App statuses render ONE chip at app level. They are not lane statuses and
 * never appear on a lane cell.
 *
 * DECISION D3, implemented as stated: Restricted means no new access is
 * requested or approved; existing lanes keep serving and keep their own
 * statuses. Its chip reads "Restricted · no new access", with the gate-wait
 * token and the platform admin as owner.
 *
 * This diverges from A5, which gives RESTRICTED the plain label "Needs an owner"
 * and the note "Lost an owner; still served". The divergence is deliberate and
 * settled: "Needs an owner" describes the cause, "no new access" describes the
 * consequence, and the consequence is what the person reading the chip has to
 * act on. A5's row is left intact in the bundle so the two can be compared.
 */
export const APP_STATUS_VOCABULARY: Readonly<Record<AppStatus, AppStatusDefinition>> = {
  draft: {
    label: "Draft",
    token: "gate-off",
    owner: "appOwner",
    means: "Being set up. Nothing is served yet.",
  },
  active: {
    label: "Active",
    token: "gate-ok",
    owner: null,
    means: "Owners assigned. Lanes serve according to their own statuses.",
  },
  restricted: {
    label: "Restricted · no new access",
    token: "gate-wait",
    owner: "platformAdmin",
    means: "No new access can be requested or approved. Existing lanes keep serving.",
  },
  retired: {
    label: "Retired",
    token: "status-expired",
    owner: "appOwner",
    means: "Northbound refuses every call. Existing keys stop working.",
  },
};

/** The glyph for an app status. Like lanes, derived from the token. */
export function appGlyphFor(status: AppStatus): string {
  return APP_CHIP_GLYPHS[APP_STATUS_VOCABULARY[status].token];
}

/** Glyph and label together: "✕ Retired". */
export function appChipTextFor(status: AppStatus): string {
  return `${appGlyphFor(status)} ${APP_STATUS_VOCABULARY[status].label}`;
}
