/** Report branding — loads org branding config for PDF generation */

import { prisma } from "@/lib/db/prisma";

export interface BrandingConfig {
  logoUrl: string | null;
  primaryColor: string;
  secondaryColor: string;
  footerText: string;
  companyName: string | null;
}

export const DEFAULT_BRANDING: BrandingConfig = {
  logoUrl: null,
  primaryColor: "#1a1a2e",
  secondaryColor: "#16213e",
  footerText: "Generated by aptus Assessment Platform",
  companyName: null,
};

export async function loadBranding(organizationId: string): Promise<BrandingConfig> {
  const branding = await prisma.reportBranding.findUnique({
    where: { organizationId },
  });

  if (!branding || !branding.isActive) return { ...DEFAULT_BRANDING };

  return {
    logoUrl: branding.logoUrl ?? null,
    primaryColor: branding.primaryColor ?? DEFAULT_BRANDING.primaryColor,
    secondaryColor: branding.secondaryColor ?? DEFAULT_BRANDING.secondaryColor,
    footerText: branding.footerText ?? DEFAULT_BRANDING.footerText,
    companyName: branding.companyName ?? null,
  };
}

export function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace(/^#/, "");
  const num = parseInt(clean, 16);
  return {
    r: (num >> 16) & 255,
    g: (num >> 8) & 255,
    b: num & 255,
  };
}
