/** Report branding — loads org-level branding config + per-assessment client
 * accent for PDF / XLSX generation.
 *
 * Two scopes:
 *   - **Org-level** (ABeam, the consulting firm using Aptus): logo, footer text,
 *     company name. Configured once per organization in `ReportBranding`.
 *   - **Per-assessment** (Bursa, the client of the engagement): a single
 *     client-accent color stored on `Assessment.clientAccent`. Used only for
 *     chart accents in the report bundle. Spec §5.7.
 *
 * The Aptus solution brand identity (mark, cover band, table headers) is
 * **locked** to `APTUS_BRAND` regardless of any override. */

import { prisma } from "@/lib/db/prisma";

/** The Aptus solution brand color. NEVER overridden — see spec §5.7. */
export const APTUS_BRAND = "#0B0B0F" as const;

/** White used as the foreground on Aptus brand-filled surfaces. */
export const APTUS_BRAND_TEXT = "#FFFFFF" as const;

export interface BrandingConfig {
  // Org-level (consulting firm):
  logoUrl: string | null;
  primaryColor: string;
  secondaryColor: string;
  footerText: string;
  companyName: string | null;

  // Per-assessment (client) — null when no override is configured.
  // Hex color (e.g. "#003DA5"). Applied ONLY to chart accents.
  clientAccent: string | null;
}

export const DEFAULT_BRANDING: BrandingConfig = {
  logoUrl: null,
  primaryColor: "#1a1a2e",
  secondaryColor: "#16213e",
  footerText: "Generated by Aptus Assessment Platform",
  companyName: null,
  clientAccent: null,
};

/** Load org-level branding only. Use `loadAssessmentBranding` if you need the
 * per-assessment client accent layered on top. */
export async function loadBranding(organizationId: string): Promise<BrandingConfig> {
  const branding = await prisma.reportBranding.findUnique({
    where: { organizationId },
  });

  if (!branding || !branding.isActive) return { ...DEFAULT_BRANDING };

  return {
    logoUrl: branding.logoUrl ?? null,
    primaryColor: branding.primaryColor ?? DEFAULT_BRANDING.primaryColor,
    secondaryColor: branding.secondaryColor ?? DEFAULT_BRANDING.secondaryColor,
    footerText: branding.footerText ?? DEFAULT_BRANDING.footerText,
    companyName: branding.companyName ?? null,
    clientAccent: null, // org-level loader doesn't expose per-assessment accent
  };
}

/** Load org branding for the assessment's organization, then layer the
 * per-assessment client accent on top. This is what the report bundle uses. */
export async function loadAssessmentBranding(assessmentId: string): Promise<BrandingConfig> {
  const assessment = await prisma.assessment.findUnique({
    where: { id: assessmentId },
    select: { organizationId: true, clientAccent: true },
  });
  if (!assessment) return { ...DEFAULT_BRANDING };

  const orgBranding = await loadBranding(assessment.organizationId);
  return { ...orgBranding, clientAccent: assessment.clientAccent ?? null };
}

export function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace(/^#/, "");
  const num = parseInt(clean, 16);
  return {
    r: (num >> 16) & 255,
    g: (num >> 8) & 255,
    b: num & 255,
  };
}

// ── Brand-role helpers (spec §5.7) ───────────────────────────────────────────

/** Surface roles where brand color is applied. Encoded so a future role can't
 * silently inherit either Aptus or the override — adding to this union forces
 * an exhaustiveness check in `brandColor()`. */
export type BrandRole =
  // LOCKED — always Aptus brand identity, never inherits client override:
  | "aptus-mark"
  | "cover-band"
  | "table-header"
  | "thumbnail-band"
  // OPTIONAL ACCENT — uses client override if present, else Aptus brand:
  | "score-ring"
  | "chart-accent"
  | "phase-segment"
  | "secondary-rule";

/** Resolve the hex color for a given brand role. */
export function brandColor(branding: BrandingConfig, role: BrandRole): string {
  switch (role) {
    case "aptus-mark":
    case "cover-band":
    case "table-header":
    case "thumbnail-band":
      return APTUS_BRAND;
    case "score-ring":
    case "chart-accent":
    case "phase-segment":
    case "secondary-rule":
      return branding.clientAccent ?? APTUS_BRAND;
    default: {
      // Exhaustiveness check — future BrandRole additions force a switch update.
      const _exhaustive: never = role;
      void _exhaustive;
      return APTUS_BRAND;
    }
  }
}

/** RGB tuple form (jsPDF needs three numbers, not a hex string). */
export function brandColorRgb(branding: BrandingConfig, role: BrandRole): [number, number, number] {
  const { r, g, b } = hexToRgb(brandColor(branding, role));
  return [r, g, b];
}

/** Returns the client-accent override if configured, else null. Useful when
 * the caller wants to skip rendering an accent entirely (vs. falling back to
 * Aptus brand). */
export function clientAccentOrNull(branding: BrandingConfig): string | null {
  return branding.clientAccent;
}

/** Validate a hex color string. Accepts #RRGGBB only (no shorthand, no alpha). */
export function isValidHex(value: string): boolean {
  return /^#[0-9A-Fa-f]{6}$/.test(value);
}
