/**
 * Scaffold artifacts — what a developer downloads and takes to their own repo.
 *
 * THE POINT OF THE WHOLE CONSOLE: the solution's application code lives in the
 * developer's own repository, in whatever stack they use. Studio governs the
 * integration edge and hands over a contract. There is no in-browser editor and
 * there never should be.
 *
 * v1 renders TEMPLATES from the interface's stored config. It is deliberately not
 * a codegen engine: real generation from a live $metadata document is a later
 * phase, and the honest thing is to produce something small and accurate rather
 * than something elaborate and approximately right. Every artifact says which it
 * is, in the file itself, so nobody mistakes a template for a guarantee.
 *
 * Pure functions: no I/O, no framework, fully testable.
 */

import { isCapturedSchema } from "@/lib/studio/schema-capture";

export interface ScaffoldInterface {
  id: string;
  name: string;
  externalId: string;
  sapProduct: string;
  operation: string;
  entitySet: string | null;
  version: number;
  solutionName: string;
  /**
   * A schema inferred from rows this tenant actually returned, when one has been
   * captured. Absent → the document keeps the open shape and says why, rather
   * than describing fields nobody has seen.
   */
  responseSchema?: unknown;
}

/** A conservative identifier for generated TypeScript. */
export function toTypeName(raw: string): string {
  const cleaned = raw
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const safe = /^[0-9]/.test(cleaned) ? `X${cleaned}` : cleaned;
  return safe.length > 0 ? safe : "CoreEdgeResource";
}

/**
 * OpenAPI 3.1 for this interface as the NORTHBOUND API exposes it.
 *
 * It describes the CoreEdge endpoint the developer's app will call — not SAP's
 * own API. That is the whole value: they code against a stable contract we own,
 * rather than against a tenant-specific SAP surface.
 *
 * All four honest states are documented as responses. An OpenAPI that only
 * describes the happy path teaches consumers to treat everything else as a
 * crash, which is exactly the confusion the honest-status contract exists to
 * prevent.
 */
export function buildOpenApi(iface: ScaffoldInterface, baseUrl = "https://coreedge.example/api/northbound"): string {
  const typeName = toTypeName(iface.entitySet ?? iface.name);
  const doc = {
    openapi: "3.1.0",
    info: {
      title: `${iface.name} — CoreEdge northbound`,
      version: `1.${iface.version}.0`,
      description: [
        `Contract for the CoreEdge interface "${iface.name}" (${iface.externalId}) of solution "${iface.solutionName}".`,
        "",
        "Generated by CoreEdge Developer Studio from the interface's governed configuration.",
        "This describes the CoreEdge northbound endpoint your application calls — not SAP's own API.",
        "",
        "Honest status: an empty result is a 200 with an empty array and MUST be treated as",
        "'no records', which is different from 'not set up' (403) and from an error (5xx).",
      ].join("\n"),
    },
    servers: [{ url: baseUrl }],
    security: [{ bearerAuth: [] }],
    paths: {
      [`/interfaces/${iface.id}/data`]: {
        get: {
          operationId: `read${typeName}`,
          summary: `Read ${iface.entitySet ?? iface.name}`,
          parameters: [
            {
              name: "limit",
              in: "query",
              required: false,
              schema: { type: "integer", minimum: 1, maximum: 100, default: 10 },
            },
          ],
          responses: {
            "200": {
              description: "Records, or an empty array meaning 'no records' — not an error.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    required: ["data"],
                    properties: {
                      data: {
                        type: "object",
                        required: ["records"],
                        properties: {
                          records: { type: "array", items: { $ref: `#/components/schemas/${typeName}` } },
                          count: { type: "integer" },
                        },
                      },
                    },
                  },
                },
              },
            },
            "401": { description: "Missing, revoked or expired client token.", content: errorContent() },
            "403": {
              description:
                "Not set up: no approved access grant for this interface in this environment, or the communication arrangement is missing.",
              content: errorContent(),
            },
            "429": { description: "Rate limited — this endpoint reaches a live SAP tenant.", content: errorContent() },
            "5XX": { description: "The tenant or the broker failed. Distinct from an empty result.", content: errorContent() },
          },
        },
      },
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          description: "Per-solution client token issued in Developer Studio.",
        },
      },
      schemas: {
        // Precise WHEN WE HAVE SEEN THE DATA, open when we have not. A captured
        // schema describes fields this tenant actually returned; without one the
        // document says so rather than describing fields nobody has observed,
        // because a confident lie inside a contract file is worse than a gap.
        [typeName]: describeRecord(iface.responseSchema),
        Error: {
          type: "object",
          required: ["error"],
          properties: {
            error: {
              type: "object",
              required: ["code", "message", "correlationId"],
              properties: {
                code: { type: "string" },
                message: { type: "string" },
                correlationId: { type: "string" },
              },
            },
          },
        },
      },
    },
  };
  return JSON.stringify(doc, null, 2);
}

function errorContent() {
  return { "application/json": { schema: { $ref: "#/components/schemas/Error" } } };
}

/**
 * The record schema: what this tenant actually returned, or an honest blank.
 *
 * A captured schema is emitted as-is (it already carries its own provenance in
 * `x-captured`). Without one, the document keeps `additionalProperties: true`
 * and states plainly that no run has happened — a reader can then tell the
 * difference between "this entity has no fields" and "nobody has looked yet".
 */
function describeRecord(responseSchema: unknown): Record<string, unknown> {
  if (isCapturedSchema(responseSchema)) {
    return {
      ...responseSchema,
      description:
        "Fields observed in a live response from this tenant. Additional fields may exist on records outside the sample.",
    };
  }
  return {
    type: "object",
    description:
      "No live response has been captured for this interface yet, so its fields are not described. Run it in the Test Console and regenerate to get a precise contract.",
    additionalProperties: true,
  };
}

/** Map a captured JSON-schema type to its TypeScript equivalent. */
function tsTypeOf(prop: { type?: string; nullable?: boolean }): string {
  const base =
    prop.type === "integer" || prop.type === "number"
      ? "number"
      : prop.type === "boolean"
        ? "boolean"
        : prop.type === "array"
          ? "unknown[]"
          : prop.type === "object"
            ? "Record<string, unknown>"
            : prop.type === "string"
              ? "string"
              : // No consistent type was observed. `unknown` forces the consumer to
                // narrow it themselves, which is correct — we genuinely do not know.
                "unknown";
  return prop.nullable ? `${base} | null` : base;
}

/**
 * The record interface body.
 *
 * With a captured schema this emits the real fields, with optional markers for
 * the ones that did not appear in every sampled row. The index signature stays
 * either way: the sample is not a census, and a consumer meeting an unlisted
 * field should get a value, not a type error.
 */
function buildRecordBody(responseSchema: unknown): string {
  if (!isCapturedSchema(responseSchema)) {
    return "  [field: string]: unknown;";
  }
  const required = new Set(responseSchema.required);
  const lines = Object.entries(responseSchema.properties).map(([name, prop]) => {
    const optional = required.has(name) ? "" : "?";
    // Quote anything that is not a plain identifier (SAP emits names like
    // `to_Partner` — fine — but also `@odata.x` on occasion).
    const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
    return `  ${key}${optional}: ${tsTypeOf(prop)};`;
  });
  // Always keep the index signature — see the doc comment above.
  lines.push("  /** Fields outside the captured sample. */");
  lines.push("  [field: string]: unknown;");
  return lines.join("\n");
}

/** TypeScript types + a tiny typed client. Any language can be generated from the OpenAPI. */
export function buildTypeScriptClient(iface: ScaffoldInterface): string {
  const typeName = toTypeName(iface.entitySet ?? iface.name);
  return `/**
 * ${iface.name} — CoreEdge northbound client
 *
 * Generated by CoreEdge Developer Studio from governed interface configuration
 * (${iface.externalId}, v${iface.version}).
 *
 * This is a TEMPLATE, not generated from a live $metadata document. The record
 * shape is intentionally open — run the interface in the Test Console to see the
 * fields this tenant actually returns, then narrow the type yourself.
 *
 * Not using TypeScript? Generate a client in your language from the OpenAPI
 * document shipped alongside this file:
 *
 *   openapi-generator-cli generate -i openapi.json -g <your-language> -o ./client
 */

/** A record as this tenant exposes it. */
export interface ${typeName} {
${buildRecordBody(iface.responseSchema)}
}

/** The error envelope every CoreEdge endpoint returns. */
export interface CoreEdgeErrorBody {
  error: { code: string; message: string; correlationId: string };
}

export interface ReadResult {
  records: ${typeName}[];
  count?: number;
}

export interface CoreEdgeClientOptions {
  /** e.g. https://coreedge.example/api/northbound — or your local mock. */
  baseUrl: string;
  /** Per-solution client token issued in Developer Studio. Keep it server-side. */
  token: string;
  fetchImpl?: typeof fetch;
}

export class CoreEdgeError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly code: string,
    readonly correlationId: string,
  ) {
    super(message);
    this.name = "CoreEdgeError";
  }
}

export function createClient(options: CoreEdgeClientOptions) {
  const doFetch = options.fetchImpl ?? fetch;
  const interfaceId = ${JSON.stringify(iface.id)};

  return {
    /**
     * Read records.
     *
     * An empty array means NO RECORDS — it is a successful read of a resource
     * that has nothing in it, and is not the same as "not set up" (403) or a
     * failure (5xx). Treat it as data.
     */
    async read(limit = 10): Promise<ReadResult> {
      const res = await doFetch(
        \`\${options.baseUrl}/interfaces/\${interfaceId}/data?limit=\${limit}\`,
        { headers: { Authorization: \`Bearer \${options.token}\`, Accept: "application/json" } },
      );
      const json = (await res.json()) as { data?: ReadResult } & Partial<CoreEdgeErrorBody>;
      if (!res.ok) {
        throw new CoreEdgeError(
          json.error?.message ?? "Request failed",
          res.status,
          json.error?.code ?? "UNKNOWN",
          json.error?.correlationId ?? "",
        );
      }
      return json.data ?? { records: [] };
    },
  };
}
`;
}

/** The runnable starter kit's README — the file that sets expectations. */
export function buildReadme(iface: ScaffoldInterface): string {
  return `# ${iface.solutionName} — ${iface.name}

Starter kit generated by CoreEdge Developer Studio.

## What this is, and is not

**Your application code lives in YOUR repository, in whatever stack you use.**
CoreEdge governs the integration edge — which SAP capability you consume, who
approved it, and what the contract looks like. It is not an IDE and does not want
to be. This kit only shows the CoreEdge call; everything around it is yours.

Your database, your framework, your language: untouched by any of this.

## Files

| File | What it is |
|---|---|
| \`openapi.json\` | OpenAPI 3.1 for the northbound endpoint. **This is the portable artifact** — generate a client in any language from it. |
| \`client.ts\` | A small typed TypeScript client, if that is your stack. |
| \`.env.example\` | The two values you need. |

## Run it

\`\`\`bash
cp .env.example .env     # then fill in COREEDGE_TOKEN
npm run demo
\`\`\`

Point \`COREEDGE_BASE_URL\` at the live broker or at a local mock — **that one
variable is the only difference**, so your tests can run offline against the mock
and the same code path runs against the real tenant.

## Not a TypeScript shop?

The OpenAPI document is the contract. Python, Go, Java, C# and the rest:

\`\`\`bash
openapi-generator-cli generate -i openapi.json -g python -o ./client
\`\`\`

## Honest status — the one thing to get right

| Response | Means | Do |
|---|---|---|
| \`200\` with records | Data | Use it |
| \`200\` with \`records: []\` | **No records** | Treat as data, not failure |
| \`403\` | Not set up, or no approved grant | Fix access — do not retry |
| \`5xx\` | Tenant or broker failed | Retry or escalate |

An empty result is **not** an error. Conflating the two is the single most common
way an integration lies to its users.

## Interface

- Service: \`${iface.externalId}\` (${iface.sapProduct})
- Operation: ${iface.operation}${iface.entitySet ? `\n- Entity set: \`${iface.entitySet}\`` : ""}
- Contract version: v${iface.version}
`;
}

export function buildEnvExample(): string {
  return `# The CoreEdge northbound base URL.
# Point at the live broker, or at your local mock to develop offline.
COREEDGE_BASE_URL=https://coreedge.example/api/northbound

# Per-solution client token, issued in Developer Studio.
# Treat it like a password: server-side only, never in a browser bundle or git.
COREEDGE_TOKEN=
`;
}

export interface ScaffoldFile {
  path: string;
  contents: string;
}

/** Everything the developer takes away, as plain files. */
export function buildScaffold(iface: ScaffoldInterface, baseUrl?: string): ScaffoldFile[] {
  return [
    { path: "README.md", contents: buildReadme(iface) },
    { path: "openapi.json", contents: buildOpenApi(iface, baseUrl) },
    { path: "client.ts", contents: buildTypeScriptClient(iface) },
    { path: ".env.example", contents: buildEnvExample() },
  ];
}
