/**
 * Scaffold artifacts — what a developer downloads and takes to their own repo.
 *
 * THE POINT OF THE WHOLE CONSOLE: the solution's application code lives in the
 * developer's own repository, in whatever stack they use. Studio governs the
 * integration edge and hands over a contract. There is no in-browser editor and
 * there never should be.
 *
 * v1 renders TEMPLATES from the interface's stored config. It is deliberately not
 * a codegen engine: real generation from a live $metadata document is a later
 * phase, and the honest thing is to produce something small and accurate rather
 * than something elaborate and approximately right. Every artifact says which it
 * is, in the file itself, so nobody mistakes a template for a guarantee.
 *
 * Pure functions: no I/O, no framework, fully testable.
 */

import { isCapturedSchema } from "@/lib/studio/schema-capture";

export interface ScaffoldInterface {
  id: string;
  name: string;
  externalId: string;
  sapProduct: string;
  operation: string;
  entitySet: string | null;
  version: number;
  solutionName: string;
  /**
   * A schema inferred from rows this tenant actually returned, when one has been
   * captured. Absent → the document keeps the open shape and says why, rather
   * than describing fields nobody has seen.
   */
  responseSchema?: unknown;
}

/** A conservative identifier for generated TypeScript. */
export function toTypeName(raw: string): string {
  const cleaned = raw
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const safe = /^[0-9]/.test(cleaned) ? `X${cleaned}` : cleaned;
  return safe.length > 0 ? safe : "CoreEdgeResource";
}

/**
 * OpenAPI 3.1 for this interface as the NORTHBOUND API exposes it.
 *
 * It describes the CoreEdge endpoint the developer's app will call — not SAP's
 * own API. That is the whole value: they code against a stable contract we own,
 * rather than against a tenant-specific SAP surface.
 *
 * All four honest states are documented as responses. An OpenAPI that only
 * describes the happy path teaches consumers to treat everything else as a
 * crash, which is exactly the confusion the honest-status contract exists to
 * prevent.
 */
export function buildOpenApi(iface: ScaffoldInterface, baseUrl = "https://coreedge.example/api/northbound"): string {
  const typeName = toTypeName(iface.entitySet ?? iface.name);
  const doc = {
    openapi: "3.1.0",
    info: {
      title: `${safeName(iface.name)} — CoreEdge northbound`,
      version: `1.${iface.version}.0`,
      description: [
        `Contract for the CoreEdge interface "${safeName(iface.name)}" (${iface.externalId}) of solution "${safeName(iface.solutionName)}".`,
        "",
        "Generated by CoreEdge Developer Studio from the interface's governed configuration.",
        "This describes the CoreEdge northbound endpoint your application calls — not SAP's own API.",
        "",
        "Honest status: an empty result is a 200 with an empty array and MUST be treated as",
        "'no records', which is different from 'not set up' (403) and from an error (5xx).",
      ].join("\n"),
    },
    servers: [{ url: baseUrl }],
    security: [{ bearerAuth: [] }],
    paths: {
      [`/interfaces/${iface.id}/data`]: {
        get: {
          operationId: `read${typeName}`,
          summary: `Read ${safeName(iface.entitySet ?? iface.name)}`,
          parameters: [
            {
              name: "limit",
              in: "query",
              required: false,
              schema: { type: "integer", minimum: 1, maximum: 100, default: 10 },
            },
          ],
          responses: {
            "200": {
              description: "Records, or an empty array meaning 'no records' — not an error.",
              headers: {
                "x-correlation-id": {
                  description: "Quote this when raising a support request; it identifies the audit row for this call.",
                  schema: { type: "string" },
                },
                "x-coreedge-interface-status": {
                  description:
                    "Present, with the value DRAFT, when the interface is still a draft in Developer Studio. A draft is served — premature is not wrong — but its contract may still change. Absent once the interface is ACTIVE.",
                  schema: { type: "string", enum: ["DRAFT"] },
                },
              },
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    required: ["data"],
                    properties: {
                      data: {
                        type: "object",
                        // Every field the broker sends on a 200, named. `empty`
                        // is the one that tells a successful read of nothing
                        // apart from a failure, and it was not in the contract.
                        required: ["records", "count", "empty", "note", "interface"],
                        properties: {
                          records: { type: "array", items: { $ref: `#/components/schemas/${typeName}` } },
                          count: { type: "integer", description: "records.length." },
                          empty: {
                            type: "boolean",
                            description: "True when the service answered successfully and had nothing to return. This is data, not a failure.",
                          },
                          note: { type: "string", description: "A one-line, human-readable account of what came back." },
                          interface: {
                            type: "object",
                            required: ["id", "name", "version"],
                            properties: {
                              id: { type: "string" },
                              name: { type: "string" },
                              version: { type: "integer", description: "The governed contract version that served this call." },
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
            "400": {
              description:
                "The interface cannot be read as configured: it has no entity set (set one in Studio, or pass ?entity=), or its catalogue service could not be resolved. Fix the configuration — do not retry.",
              content: errorContent(),
            },
            "401": { description: "Missing, revoked or expired client token.", content: errorContent() },
            "403": {
              description:
                "Not set up: no approved access grant for this interface in this environment, or the communication arrangement is missing.",
              content: errorContent(),
            },
            "404": {
              description: "No interface with this id belongs to the solution this token was issued for.",
              content: errorContent(),
            },
            "429": { description: "Rate limited — this endpoint reaches a live SAP tenant.", content: errorContent() },
            "5XX": { description: "The tenant or the broker failed. Distinct from an empty result.", content: errorContent() },
          },
        },
      },
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          description: "Per-solution client token issued in Developer Studio.",
        },
      },
      schemas: {
        // Precise WHEN WE HAVE SEEN THE DATA, open when we have not. A captured
        // schema describes fields this tenant actually returned; without one the
        // document says so rather than describing fields nobody has observed,
        // because a confident lie inside a contract file is worse than a gap.
        [typeName]: describeRecord(iface.responseSchema),
        Error: {
          type: "object",
          required: ["error"],
          properties: {
            error: {
              type: "object",
              required: ["code", "message", "correlationId"],
              properties: {
                code: { type: "string" },
                message: { type: "string" },
                correlationId: { type: "string" },
              },
            },
          },
        },
      },
    },
  };
  return JSON.stringify(doc, null, 2);
}

function errorContent() {
  return { "application/json": { schema: { $ref: "#/components/schemas/Error" } } };
}

/**
 * The record schema: what this tenant actually returned, or an honest blank.
 *
 * A captured schema is emitted as-is (it already carries its own provenance in
 * `x-captured`). Without one, the document keeps `additionalProperties: true`
 * and states plainly that no run has happened — a reader can then tell the
 * difference between "this entity has no fields" and "nobody has looked yet".
 */
function describeRecord(responseSchema: unknown): Record<string, unknown> {
  if (isCapturedSchema(responseSchema)) {
    return {
      ...responseSchema,
      properties: Object.fromEntries(
        Object.entries(responseSchema.properties).map(([name, prop]) => [name, toOpenApi31Property(prop)]),
      ),
      description:
        "Fields observed in a live response from this tenant. Additional fields may exist on records outside the sample.",
    };
  }
  return {
    type: "object",
    description:
      "No live response has been captured for this interface yet, so its fields are not described. Run it in the Test Console and regenerate to get a precise contract.",
    additionalProperties: true,
  };
}

/**
 * THE DOCUMENT SAYS 3.1.0, SO IT MUST SPEAK 3.1. The captured schema records a
 * null it saw as `nullable: true` — the OpenAPI 3.0 keyword, which 3.1 dropped
 * for JSON Schema's `type: [T, "null"]`. Generators reading a 3.1 document
 * ignore `nullable` silently, so every nullable date came out untyped in the
 * developer's client. The stored form is unchanged (the TypeScript emitter
 * reads it); the translation happens here, at the sink that claims 3.1.
 */
function toOpenApi31Property(prop: { type?: string; format?: string; nullable?: boolean }): Record<string, unknown> {
  const { nullable, type, ...rest } = prop;
  if (!nullable) return type ? { ...rest, type } : rest;
  // No consistent type observed AND a null: the value may be anything or null.
  // JSON Schema has no way to say "unknown-or-null" narrower than no type at
  // all, so the null is recorded in the description rather than invented.
  if (!type) return { ...rest, description: "Observed as null in the sample; no consistent type otherwise." };
  return { ...rest, type: [type, "null"] };
}

/** Map a captured JSON-schema type to its TypeScript equivalent. */
function tsTypeOf(prop: { type?: string; nullable?: boolean }): string {
  const base =
    prop.type === "integer" || prop.type === "number"
      ? "number"
      : prop.type === "boolean"
        ? "boolean"
        : prop.type === "array"
          ? "unknown[]"
          : prop.type === "object"
            ? "Record<string, unknown>"
            : prop.type === "string"
              ? "string"
              : // No consistent type was observed. `unknown` forces the consumer to
                // narrow it themselves, which is correct — we genuinely do not know.
                "unknown";
  return prop.nullable ? `${base} | null` : base;
}

/**
 * The record interface body.
 *
 * With a captured schema this emits the real fields, with optional markers for
 * the ones that did not appear in every sampled row. The index signature stays
 * either way: the sample is not a census, and a consumer meeting an unlisted
 * field should get a value, not a type error.
 */
function buildRecordBody(responseSchema: unknown): string {
  if (!isCapturedSchema(responseSchema)) {
    return "  [field: string]: unknown;";
  }
  const required = new Set(responseSchema.required);
  const lines = Object.entries(responseSchema.properties).map(([name, prop]) => {
    const optional = required.has(name) ? "" : "?";
    // Quote anything that is not a plain identifier (SAP emits names like
    // `to_Partner` — fine — but also `@odata.x` on occasion).
    const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
    return `  ${key}${optional}: ${tsTypeOf(prop)};`;
  });
  // Always keep the index signature — see the doc comment above.
  lines.push("  /** Fields outside the captured sample. */");
  lines.push("  [field: string]: unknown;");
  return lines.join("\n");
}

/** TypeScript types + a tiny typed client. Any language can be generated from the OpenAPI. */
export function buildTypeScriptClient(
  iface: ScaffoldInterface,
  baseUrl = "https://coreedge.example/api/northbound",
): string {
  const typeName = toTypeName(iface.entitySet ?? iface.name);
  /*
   * THE HEADER FOLLOWS THE SCHEMA. It said "This is a TEMPLATE … the record
   * shape is intentionally open" unconditionally — directly above 54 typed
   * fields, once a schema had been captured. The sentence was true the day it
   * was written and the capture feature did not update it.
   */
  const shapeNote = isCapturedSchema(iface.responseSchema)
    ? ` * The record type below was CAPTURED from ${iface.responseSchema["x-captured"].sampleSize} live row${
        iface.responseSchema["x-captured"].sampleSize === 1 ? "" : "s"
      } this tenant returned
 * (${iface.responseSchema["x-captured"].capturedAt}). It describes what was observed, not
 * SAP's full $metadata: fields outside the sample are not listed, and the index
 * signature keeps them reachable. Fields are optional unless the sample was
 * large enough to assert otherwise — see x-captured in openapi.json.`
    : ` * This is a TEMPLATE, not generated from a live $metadata document. The record
 * shape is intentionally open — run the interface in the Test Console, use
 * Capture schema, and regenerate to get the fields this tenant actually returns.`;
  return `/**
 * ${safeName(iface.name)} — CoreEdge northbound client
 *
 * Generated by CoreEdge Developer Studio from governed interface configuration
 * (${safeComment(iface.externalId)}, v${iface.version}).
 *
${shapeNote}
 *
 * Not using TypeScript? Generate a client in your language from the OpenAPI
 * document shipped alongside this file:
 *
 *   openapi-generator-cli generate -i openapi.json -g <your-language> -o ./client
 */

/** A record as this tenant exposes it. */
export interface ${typeName} {
${buildRecordBody(iface.responseSchema)}
}

/** The error envelope every CoreEdge endpoint returns. */
export interface CoreEdgeErrorBody {
  error: { code: string; message: string; correlationId: string };
}

/** What a 200 carries — every field the broker sends, not only the records. */
export interface ReadResult {
  records: ${typeName}[];
  /** records.length. */
  count: number;
  /**
   * True when the service answered successfully and had nothing to return.
   * THIS IS DATA, NOT A FAILURE — the one field that tells an empty read apart
   * from a refusal, and the reason a consumer must not key on records.length.
   */
  empty: boolean;
  /** A one-line, human-readable account of what came back. */
  note: string;
  /** The governed interface (and contract version) that served the call. */
  interface: { id: string; name: string; version: number };
  /**
   * True when the broker sent x-coreedge-interface-status: DRAFT — the
   * interface is served but its builder has not marked it ACTIVE, so this
   * contract may still change.
   */
  draft: boolean;
}

export interface CoreEdgeClientOptions {
  /** e.g. ${baseUrl} — or your local mock. */
  baseUrl: string;
  /** Per-solution client token issued in Developer Studio. Keep it server-side. */
  token: string;
  fetchImpl?: typeof fetch;
}

export class CoreEdgeError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly code: string,
    readonly correlationId: string,
  ) {
    super(message);
    this.name = "CoreEdgeError";
  }
}

export function createClient(options: CoreEdgeClientOptions) {
  const doFetch = options.fetchImpl ?? fetch;
  const interfaceId = ${JSON.stringify(iface.id)};

  return {
    /**
     * Read records.
     *
     * An empty array means NO RECORDS — it is a successful read of a resource
     * that has nothing in it, and is not the same as "not set up" (403) or a
     * failure (5xx). Treat it as data.
     */
    async read(limit = 10): Promise<ReadResult> {
      const res = await doFetch(
        \`\${options.baseUrl}/interfaces/\${interfaceId}/data?limit=\${limit}\`,
        { headers: { Authorization: \`Bearer \${options.token}\`, Accept: "application/json" } },
      );
      /*
       * PARSE DEFENSIVELY, AND LET THE STATUS DECIDE.
       *
       * A failure does not always arrive as CoreEdge JSON: a proxy 502, an edge
       * 429 and a gateway timeout are commonly HTML or empty. Calling
       * res.json() first threw a SyntaxError on those, which replaced a usable
       * status and correlation id with a parse error — the client hid the one
       * fact the developer needed at exactly the moment it mattered.
       */
      const body = await res.text().catch(() => "");
      let json: ({ data?: Omit<ReadResult, "draft"> } & Partial<CoreEdgeErrorBody>) | null = null;
      try {
        json = body ? (JSON.parse(body) as typeof json) : null;
      } catch {
        json = null;
      }
      if (!res.ok) {
        throw new CoreEdgeError(
          json?.error?.message ?? \`Request failed with HTTP \${res.status}\`,
          res.status,
          json?.error?.code ?? "UNKNOWN",
          json?.error?.correlationId ?? res.headers.get("x-correlation-id") ?? "",
        );
      }
      if (!json?.data) {
        // A 2xx without the data envelope is not "no records" — it is a
        // response this client does not understand, and saying so beats
        // inventing an empty result.
        throw new CoreEdgeError(
          "Response carried no data envelope",
          res.status,
          "MALFORMED_RESPONSE",
          res.headers.get("x-correlation-id") ?? "",
        );
      }
      return { ...json.data, draft: res.headers.get("x-coreedge-interface-status") === "DRAFT" };
    },
  };
}
`;
}

/** The runnable starter kit's README — the file that sets expectations. */
export function buildReadme(
  iface: ScaffoldInterface,
  fixtures: readonly ScaffoldFixture[] = [],
  baseUrl = "https://coreedge.example/api/northbound",
): string {
  const captured = fixtures.map((f) => f.scenario);
  const missing = ["data", "empty", "needs_setup", "error"].filter((s) => !captured.includes(s));
  const fixtureSection =
    captured.length === 0
      ? `## Offline mock — nothing captured yet

\`npm run mock\` will start, but it has no recorded responses to serve. Open this
interface in the Test Console, run it, and use **Capture fixture** — then
regenerate this kit. Until then your tests cannot run offline.
`
      : `## Offline mock

\`\`\`bash
npm run mock          # http://localhost:4010, serving recorded responses
\`\`\`

Captured scenarios: **${captured.join(", ")}**${
          missing.length > 0
            ? `\n\nNot captured yet: **${missing.join(", ")}** — capture them from the Test
Console so your tests can exercise those paths too. A suite that only proves your
code works when everything is fine is proving the easy half.`
            : "\n\nAll four honest states are recorded, so your tests can exercise every path."
        }

Choose one per request with \`?scenario=empty\`, or for the whole process with
\`COREEDGE_SCENARIO=empty\`.
`;

  return `# ${safeName(iface.solutionName)} — ${safeName(iface.name)}

Starter kit generated by CoreEdge Developer Studio.

## What this is, and is not

**Your application code lives in YOUR repository, in whatever stack you use.**
CoreEdge governs the integration edge — which SAP capability you consume, who
approved it, and what the contract looks like. It is not an IDE and does not want
to be. This kit only shows the CoreEdge call; everything around it is yours.

Your database, your framework, your language: untouched by any of this.

## Files

| File | What it is |
|---|---|
| \`openapi.json\` | OpenAPI 3.1 for the northbound endpoint. **This is the portable artifact** — generate a client in any language from it. |
| \`client.ts\` | A small typed TypeScript client, if that is your stack. |
| \`demo.mjs\` | A runnable read. Proves the loop end to end. |
| \`mock.mjs\` + \`fixtures.json\` | An offline CoreEdge, serving responses recorded from real runs. No dependencies. |
| \`.env.example\` | The two values you need. |
| \`.gitignore\` | Keeps \`.env\` (your token) and \`fixtures.json\` (your customer's records) out of your repository by default. |

## Run it

Needs Node 20.12 or newer — the scripts load \`.env\` for you.

\`\`\`bash
cp .env.example .env     # COREEDGE_BASE_URL is already filled in for you
                         # add your COREEDGE_TOKEN
npm run demo
\`\`\`

No \`.env\`? Pass them inline — both scripts work either way:

\`\`\`bash
COREEDGE_BASE_URL=${baseUrl} COREEDGE_TOKEN=ce_… npm run demo
\`\`\`

${fixtureSection}

Point \`COREEDGE_BASE_URL\` at the live broker or at a local mock — **that one
variable is the only difference**, so your tests can run offline against the mock
and the same code path runs against the real tenant.

## The fixture file holds your customer's data — treat it that way

\`fixtures.json\` is recorded from **real reads of a real tenant**. A \`data\`
fixture carries live master data — supplier numbers, user IDs, company codes,
whatever the entity set returned. It is truncated to a sample, never redacted.

- It is listed in \`.gitignore\`, so it stays out of your repository unless you
  choose otherwise. Keep it that way, or redact it first.
- Do not share this kit with anyone who is not cleared to see the tenant's data.
- The other scenarios (\`empty\`, \`needs_setup\`, \`error\`) carry no records
  and are safe to commit; split them out if your suite needs them in CI.

## Not a TypeScript shop?

The OpenAPI document is the contract. Python, Go, Java, C# and the rest:

\`\`\`bash
openapi-generator-cli generate -i openapi.json -g python -o ./client
\`\`\`

## Honest status — the one thing to get right

| Response | Means | Do |
|---|---|---|
| \`200\` with records | Data | Use it |
| \`200\` with \`records: []\` | **No records** | Treat as data, not failure |
| \`403\` | Not set up, or no approved grant | Fix access — do not retry |
| \`5xx\` | Tenant or broker failed | Retry or escalate |

An empty result is **not** an error. Conflating the two is the single most common
way an integration lies to its users.

## Interface

- Service: ${inlineCode(iface.externalId)} (${safeName(iface.sapProduct)})
- Operation: ${safeName(iface.operation)}${iface.entitySet ? `\n- Entity set: ${inlineCode(iface.entitySet)}` : ""}
- Contract version: v${iface.version}
`;
}

/**
 * .env.example — pre-filled with THIS deployment's base URL.
 *
 * IT USED TO HARDCODE `https://coreedge.example/api/northbound` while
 * openapi.json (three files away, same download) carried the real origin the
 * route derives. So the one file the README tells you to copy was the one file
 * that could not work, and `npm run demo` failed against a domain that does not
 * resolve — after the developer had already filled in a real token. The base URL
 * is a parameter here for the same reason it is one in buildOpenApi: the kit is
 * generated per request and knows where it came from.
 */
export function buildEnvExample(baseUrl = "https://coreedge.example/api/northbound"): string {
  return `# The CoreEdge northbound base URL, pre-filled for the deployment that
# generated this kit. Point it at your local mock to develop offline.
COREEDGE_BASE_URL=${baseUrl}

# Per-solution client token, issued in Developer Studio.
# Treat it like a password: server-side only, never in a browser bundle or git.
COREEDGE_TOKEN=
`;
}

/**
 * fixtures.json — and the one sentence in it that has to be earned.
 *
 * THE NOTE USED TO READ "Recorded from real runs in CoreEdge Developer Studio"
 * UNCONDITIONALLY. It was written into every download, including over fixtures
 * captured while the Test Console was reporting a tenant's 403 as a successful
 * empty read. So the file asserted provenance for records that had none, a
 * developer took it into their own repository, and `npm run mock` served an
 * invented 200 for a call that really refuses.
 *
 * A fixture can now say where it came from. One that cannot — because it
 * predates `sourceStatus` — is not silently dropped and not silently blessed:
 * it is shipped, flagged, and the note stops claiming what it cannot support.
 * That is the same rule the product applies to a probe it has not run.
 */
function buildFixturesJson(
  iface: { id: string; name: string },
  fixtures: readonly ScaffoldFixture[],
): string {
  const unproven = fixtures.filter((f) => f.sourceStatus === null || f.sourceStatus === undefined);
  const dataFixtures = fixtures.filter((f) => f.scenario === "data");

  return JSON.stringify(
    {
      interfaceId: iface.id,
      interfaceName: safeName(iface.name),
      // First key in the file, so it is the first line anyone opening it reads.
      warning: dataFixtures.length > 0
        ? `CUSTOMER DATA. ${dataFixtures.length === 1 ? "The data fixture carries" : `${dataFixtures.length} fixtures carry`} live records read from a real tenant — master data, identifiers, amounts. ` +
          "This file is listed in the kit's .gitignore; do not commit it to a shared repository or hand it to anyone not cleared to see the tenant's data. Redact before sharing."
        : "No data fixture is captured, so this file carries no tenant records. A data capture will; see the README.",
      note:
        unproven.length === 0
          ? "Recorded from real runs in CoreEdge Developer Studio, each carrying the status the tenant returned. Serve them with `npm run mock`."
          : `Recorded in CoreEdge Developer Studio. ${unproven.length} of ${fixtures.length} ` +
            "fixtures predate provenance recording and carry no sourceStatus, so what the " +
            "tenant actually answered when they were captured cannot be established — they " +
            "are marked unverified below. Re-run those scenarios in the Test Console and " +
            "capture again to replace them. Serve with `npm run mock`.",
      fixtures: fixtures.map((f) => ({
        scenario: f.scenario,
        status: f.status,
        // Named for what it is, so a reader who never opens the docs still sees
        // the difference between "the tenant said 200" and "nobody recorded it".
        sourceStatus: f.sourceStatus ?? null,
        capturedAt: f.capturedAt ?? null,
        ...(f.sourceStatus === null || f.sourceStatus === undefined
          ? { unverified: "Captured before CoreEdge recorded provenance; origin unknown." }
          : {}),
        body: f.body,
      })),
    },
    null,
    2,
  );
}


/**
 * A name, made safe to embed in a file someone else will open.
 *
 * SOLUTION AND INTERFACE NAMES ARE FREE TEXT AND THEY LEAVE THE BROWSER. React
 * escapes them on screen, which is where everyone looked; the scaffold writes
 * them into README.md and openapi.json and hands those to a developer. A stored
 * `QA-<script>alert(1)</script>-XSS` arrived VERBATIM in both:
 *
 *     "Contract for the CoreEdge interface … of solution
 *      "QA-<script>alert(1)</script>-XSS"."
 *
 * An OpenAPI `description` is rendered as markdown or HTML by Swagger UI, Redoc
 * and every API portal worth the name, and a README is rendered by the forge and
 * the IDE. The payload executes in the viewer, not here — which is exactly why
 * it was invisible to a check that only opened the product.
 *
 * ESCAPED AT THE SINK, NOT REJECTED AT THE SOURCE. Refusing angle brackets in a
 * solution name would be a second, weaker control in a different place, would
 * not help the records that already carry one, and would tell a consultant their
 * perfectly reasonable name is forbidden because of how one downstream file is
 * generated. The generator is what knows it is writing a document.
 *
 * Angle brackets and ampersand only: this must stay readable. A name is still a
 * name after it goes through here.
 */
function safeName(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/**
 * The same "escape at the sink" rule as safeName, for the two OTHER sinks the
 * kit writes into — because safeName covers the HTML-ish ones and nothing
 * covered these.
 *
 * A field like externalId reaches a file as three different things: a JSON
 * string (escaped by JSON.stringify), a TypeScript block comment, and a
 * markdown code span. The last two were interpolated raw. A comment terminator
 * inside an externalId ends client.ts's header comment early and the rest of
 * the line becomes code; a backtick inside one closes the README's code span
 * and the rest of the line becomes markdown. Neither is exotic input in a field
 * a consultant types, and neither is the record's fault — the generator is what
 * knows which document it is writing.
 */
function safeComment(value: string): string {
  // A space through the terminator: visible, lossless enough to read back, and
  // no longer able to end the comment it sits in.
  return value.replace(/\*\//g, "* /");
}

/**
 * A markdown code span holding `value`, fenced so nothing inside can close it.
 *
 * Markdown's own rule rather than an escape: a span may be delimited by any run
 * of backticks longer than the longest run inside it, so the value travels
 * whole — no character is substituted and no homoglyph is smuggled into a
 * service name a developer may paste back.
 */
function inlineCode(value: string): string {
  const longest = Math.max(0, ...[...value.matchAll(/`+/g)].map((m) => m[0].length));
  const fence = "`".repeat(longest + 1);
  // A span whose content starts or ends with a backtick needs the padding
  // spaces, which markdown strips again on render.
  const pad = longest > 0 ? " " : "";
  return `${fence}${pad}${value}${pad}${fence}`;
}

/** A recorded response, as captured from a real run. */
export interface ScaffoldFixture {
  scenario: string;
  status: number;
  body: unknown;
  /**
   * The status the tenant returned when this was recorded, and when.
   *
   * Both optional, because fixtures captured before provenance existed have
   * neither — and that absence is carried into the file rather than smoothed
   * over. See `buildFixturesJson`.
   */
  sourceStatus?: number | null;
  capturedAt?: string | null;
}

/**
 * The offline mock.
 *
 * Deliberately a ~60-line Node script with no dependencies rather than a mock
 * framework: the developer already has enough tooling opinions of their own, and
 * a fixture server that needs installing is a fixture server that does not get
 * used. It reads the same fixtures.json the Studio captured and serves the same
 * shape the real broker returns, so the ONLY difference between mock and live is
 * COREEDGE_BASE_URL.
 *
 * SCENARIO SELECTION is explicit — `?scenario=empty`, or the COREEDGE_SCENARIO
 * env var. A mock that always returns the happy path lets a test suite prove
 * only that the code works when everything is fine, which is exactly when it
 * does not matter.
 */
export function buildMockServer(iface: ScaffoldInterface): string {
  return `#!/usr/bin/env node
/**
 * Offline CoreEdge mock for "${safeName(iface.name)}".
 *
 * Serves the recorded responses in fixtures.json in exactly the shape the real
 * northbound API returns. No dependencies — node mock.mjs and you are running.
 *
 *   npm run mock                       # http://localhost:4010
 *   COREEDGE_SCENARIO=empty npm run mock
 *
 * Pick a scenario per request with ?scenario=…, or for the whole process with
 * COREEDGE_SCENARIO. Available scenarios are whatever was captured:
 * data, empty, needs_setup, error.
 *
 * Point your app at it by changing ONE variable:
 *   COREEDGE_BASE_URL=http://localhost:4010
 */
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(readFileSync(join(here, "fixtures.json"), "utf8"));
${loadEnvPrelude()}
const PORT = Number(process.env.PORT ?? 4010);
const DEFAULT_SCENARIO = process.env.COREEDGE_SCENARIO ?? "data";
// The broker's own bounds, so ?limit behaves here exactly as it will there.
const DEFAULT_LIMIT = 10;
const MAX_LIMIT = 100;
const INTERFACE_ID = ${JSON.stringify(iface.id)};
const INTERFACE = ${JSON.stringify({ id: iface.id, name: safeName(iface.name), version: iface.version })};

function pick(scenario) {
  const found = fixtures.fixtures.find((f) => f.scenario === scenario);
  if (found) return found;
  // Say what IS available rather than silently serving something else — a mock
  // that quietly substitutes a different scenario is worse than one that fails.
  return {
    scenario,
    status: 404,
    body: {
      error: {
        code: "FIXTURE_NOT_CAPTURED",
        message:
          \`No "\${scenario}" fixture was captured for this interface. Available: \` +
          fixtures.fixtures.map((f) => f.scenario).join(", ") +
          ". Capture it from the Test Console in Developer Studio.",
        correlationId: "mock",
      },
    },
  };
}

/**
 * ?limit=N, honoured — the broker clamps it to 1…100 and returns at most that
 * many rows.
 *
 * The mock used to ignore it and serve the whole fixture, so read(1) came back
 * with every recorded row and code written against the mock broke on the first
 * real call. count and empty are recomputed from what is actually served,
 * because an envelope whose count disagrees with its own array is the kind of
 * lie this kit exists to argue against.
 */
function applyLimit(body, raw) {
  if (!body || !Array.isArray(body.records)) return body;
  const parsed = Number.parseInt(raw ?? "", 10);
  const limit = Number.isFinite(parsed) ? Math.min(Math.max(parsed, 1), MAX_LIMIT) : DEFAULT_LIMIT;
  if (body.records.length <= limit) return body;
  const records = body.records.slice(0, limit);
  return {
    ...body,
    records,
    count: records.length,
    empty: records.length === 0,
    note: \`\${records.length} record(s) — the mock truncated \${body.records.length} recorded rows to ?limit=\${limit}.\`,
  };
}

createServer((req, res) => {
  const url = new URL(req.url ?? "/", \`http://localhost:\${PORT}\`);

  // The mock does not check the token — it is a local stand-in, not a security
  // boundary. It DOES require one, so code that forgets the header fails here
  // rather than in production.
  const auth = req.headers.authorization ?? "";
  if (!auth.toLowerCase().startsWith("bearer ")) {
    res.writeHead(401, { "content-type": "application/json" });
    res.end(JSON.stringify({ error: { code: "UNAUTHENTICATED", message: "Missing bearer token.", correlationId: "mock" } }));
    return;
  }

  if (!url.pathname.startsWith(\`/interfaces/\${INTERFACE_ID}/data\`)) {
    res.writeHead(404, { "content-type": "application/json" });
    res.end(JSON.stringify({ error: { code: "NOT_FOUND", message: \`This mock only serves /interfaces/\${INTERFACE_ID}/data\`, correlationId: "mock" } }));
    return;
  }

  const fixture = pick(url.searchParams.get("scenario") ?? DEFAULT_SCENARIO);
  // The same envelope the broker sends, "interface" included: the fixture body
  // is what the run returned; which interface served it is the mock's to add.
  const payload =
    fixture.status < 400
      ? { data: { interface: INTERFACE, ...applyLimit(fixture.body, url.searchParams.get("limit")) } }
      : fixture.body;
  res.writeHead(fixture.status, { "content-type": "application/json", "x-correlation-id": "mock" });
  res.end(JSON.stringify(payload, null, 2));
}).listen(PORT, () => {
  const names = fixtures.fixtures.map((f) => f.scenario).join(", ") || "(none captured)";
  console.log(\`CoreEdge mock on http://localhost:\${PORT}\`);
  console.log(\`  scenarios: \${names}\`);
  console.log(\`  default:   \${DEFAULT_SCENARIO}\`);
});
`;
}

/**
 * package.json for the starter kit — the two scripts that matter.
 *
 * PLAIN `node`, because loading .env is the SCRIPT'S job now (see loadEnvPrelude).
 *
 * This briefly ran `node --env-file-if-exists=.env`, with `engines: >=22.9` to
 * declare the flag's floor. That floor was the problem: npm treats `engines` as
 * ADVISORY unless engine-strict is set, so a developer on Node 22.5 — a version
 * that looks entirely current — gets a warning they may not read and then
 * `node: bad option: --env-file-if-exists`. Cryptic, and landing on exactly the
 * "the documented first run works" promise this kit exists to keep. The floor
 * also excluded all of 22.0–22.8, not just older majors.
 */
export function buildPackageJson(iface: ScaffoldInterface): string {
  return JSON.stringify(
    {
      name: `coreedge-${iface.id.toLowerCase()}`,
      private: true,
      type: "module",
      description: `CoreEdge starter kit for ${safeName(iface.name)}`,
      scripts: {
        mock: "node mock.mjs",
        demo: "node demo.mjs",
      },
    },
    null,
    2,
  );
}

/**
 * Load .env with NODE'S OWN PARSER, and shrug if there isn't one.
 *
 * THE DEFECT THIS CLOSES. The README has always said `cp .env.example .env` then
 * `npm run demo`. Nothing ever loaded that file, so the documented first run
 * exited 1 with "Set COREEDGE_BASE_URL and COREEDGE_TOKEN (see .env.example)"
 * while the developer was looking at a .env holding exactly those two values.
 * The first thing the kit did was tell them they had not done the thing they
 * had just done.
 *
 * `process.loadEnvFile` (Node 20.12+) is the built-in parser — comments and
 * quoting handled by Node, not by a hand-rolled splitter that would eventually
 * mangle a token containing "=". It THROWS on a missing file, so the catch is
 * what makes the inline form (`COREEDGE_BASE_URL=… npm run demo`, and the mock
 * walkthrough) keep working: both paths in the README have to run.
 *
 * The typeof guard costs one line and means a genuinely ancient Node still
 * reaches the script's own "set these two variables" message rather than dying
 * on an unknown method.
 */
function loadEnvPrelude(): string {
  return `// Load .env if present — Node's own parser; absent file is fine (inline env vars).
if (typeof process.loadEnvFile === "function") {
  try {
    process.loadEnvFile(".env");
  } catch {
    /* no .env — variables may come from the environment instead */
  }
}
`;
}

/** A runnable demo — the thing that proves the loop works end to end. */
export function buildDemo(iface: ScaffoldInterface): string {
  return `#!/usr/bin/env node
/**
 * Reads through CoreEdge and prints what came back.
 *
 * Run it against the mock or against the live broker — the ONLY difference is
 * COREEDGE_BASE_URL:
 *
 *   npm run mock &                 # terminal 1
 *   COREEDGE_BASE_URL=http://localhost:4010 COREEDGE_TOKEN=anything npm run demo
 *
 *   COREEDGE_BASE_URL=https://…/api/northbound COREEDGE_TOKEN=ce_… npm run demo
 */
${loadEnvPrelude()}
const baseUrl = process.env.COREEDGE_BASE_URL;
const token = process.env.COREEDGE_TOKEN;

if (!baseUrl || !token) {
  console.error("Set COREEDGE_BASE_URL and COREEDGE_TOKEN (see .env.example).");
  process.exit(1);
}

const res = await fetch(\`\${baseUrl}/interfaces/${iface.id}/data?limit=5\`, {
  headers: { Authorization: \`Bearer \${token}\`, Accept: "application/json" },
});
// The status first: a 502 from a proxy is usually HTML, and parsing it before
// looking at res.ok turns a readable failure into a SyntaxError.
const body = await res.text().catch(() => "");
let json = null;
try {
  json = body ? JSON.parse(body) : null;
} catch {
  json = null;
}

if (!res.ok) {
  // 403 means "not set up" — an access problem to fix, not an outage to retry.
  console.error(\`HTTP \${res.status}\`, json?.error?.code ?? "", "-", json?.error?.message ?? body.slice(0, 200));
  console.error("correlationId:", json?.error?.correlationId ?? res.headers.get("x-correlation-id") ?? "");
  process.exit(1);
}

const { records = [], empty, note } = json?.data ?? {};
if (empty) {
  // The single most important line in this file: an empty result is DATA. Your
  // application should render "nothing here", not an error page.
  console.log("No records — the service answered successfully and had nothing to return.");
} else {
  console.log(\`\${records.length} record(s):\`);
  for (const r of records.slice(0, 5)) console.log(" ", JSON.stringify(r).slice(0, 160));
}
if (note) console.log("note:", note);
`;
}

/**
 * .gitignore — the one line that stops customer data reaching a repository.
 *
 * The kit's premise is that you take it to your own repository, and the default
 * path did exactly that with fixtures.json inside it: supplier numbers, SAP
 * user IDs and company codes, recorded from a real tenant and described in the
 * README as "responses recorded from real runs", walked into a developer's git
 * history on the first commit. The token in .env was one `git add .` from the
 * same fate. Both are ignored by default; un-ignoring is a decision.
 */
export function buildGitignore(): string {
  return `# Your per-solution client token. Never commit it.
.env

# Recorded responses from a REAL tenant. The data fixture carries live customer
# records (master data, identifiers, amounts) — truncated, never redacted.
# Keep it out of shared history; redact it first if your suite must have it.
fixtures.json
`;
}

export interface ScaffoldFile {
  path: string;
  contents: string;
}

/**
 * Everything the developer takes away, as plain files.
 *
 * With fixtures, the kit is runnable offline: `npm run mock` then `npm run demo`
 * exercises the same code path the live broker serves. Without them it still
 * ships, and the README says which scenarios are missing rather than pretending
 * the mock is complete.
 */
export function buildScaffold(
  iface: ScaffoldInterface,
  baseUrl?: string,
  fixtures: readonly ScaffoldFixture[] = [],
): ScaffoldFile[] {
  return [
    { path: "README.md", contents: buildReadme(iface, fixtures, baseUrl) },
    { path: "openapi.json", contents: buildOpenApi(iface, baseUrl) },
    { path: "client.ts", contents: buildTypeScriptClient(iface, baseUrl) },
    { path: ".env.example", contents: buildEnvExample(baseUrl) },
    { path: ".gitignore", contents: buildGitignore() },
    { path: "package.json", contents: buildPackageJson(iface) },
    { path: "demo.mjs", contents: buildDemo(iface) },
    { path: "mock.mjs", contents: buildMockServer(iface) },
    {
      path: "fixtures.json",
      contents: buildFixturesJson(iface, fixtures),
    },
  ];
}
