/**
 * Server-side PDF embedding for the canonical Aptus mark.
 *
 * Reads the regenerated PNG (derived from `public/icons/aptus-mark.svg`
 * by `scripts/regenerate-brand-pngs.ts`) synchronously at module load and
 * exposes it as a `data:` URL ready for `doc.addImage` (jsPDF). This
 * guarantees every PDF cover renders the exact same artwork that appears
 * in the web app, the favicon, and the OG card — single source of truth.
 */

import { readFileSync } from "node:fs";
import path from "node:path";

const PUBLIC_ICONS = path.join(process.cwd(), "public", "icons");

function readAsDataUrl(file: string, mime = "image/png"): string {
  const buf = readFileSync(path.join(PUBLIC_ICONS, file));
  return `data:${mime};base64,${buf.toString("base64")}`;
}

/** 512×512 PNG of the Aptus mark, dark fill — for light backgrounds. */
export const APTUS_MARK_PNG_DATA_URL: string = readAsDataUrl("icon-512x512.png");

/** 512×512 PNG of the Aptus mark, white fill — for dark backgrounds (PDF
 * cover band, OG image). Generated by `scripts/regenerate-brand-pngs.ts`. */
export const APTUS_MARK_WHITE_PNG_DATA_URL: string = readAsDataUrl("aptus-mark-white.png");

export const APTUS_MARK_PNG_WIDTH = 512;
export const APTUS_MARK_PNG_HEIGHT = 512;
