export const COUNTRY_NAMES: Record<string, string> = {
  MY: "Malaysia",
  SG: "Singapore",
  ID: "Indonesia",
  TH: "Thailand",
  PH: "Philippines",
  VN: "Vietnam",
  US: "United States",
  GB: "United Kingdom",
  DE: "Germany",
  FR: "France",
  IT: "Italy",
  ES: "Spain",
  NL: "Netherlands",
  BE: "Belgium",
  AT: "Austria",
  CH: "Switzerland",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  AU: "Australia",
  NZ: "New Zealand",
  JP: "Japan",
  KR: "South Korea",
  CN: "China",
  IN: "India",
  AE: "United Arab Emirates",
  SA: "Saudi Arabia",
  BR: "Brazil",
  MX: "Mexico",
  CA: "Canada",
  ZA: "South Africa",
  KE: "Kenya",
  NG: "Nigeria",
  EG: "Egypt",
  LU: "Luxembourg",
  IE: "Ireland",
  PT: "Portugal",
  PL: "Poland",
  CZ: "Czech Republic",
  HU: "Hungary",
  RO: "Romania",
  HR: "Croatia",
  BG: "Bulgaria",
  TW: "Taiwan",
  HK: "Hong Kong",
  LK: "Sri Lanka",
  BD: "Bangladesh",
  PK: "Pakistan",
  CL: "Chile",
  CO: "Colombia",
  AR: "Argentina",
  PE: "Peru",
};

export function getCountryName(code: string): string {
  return COUNTRY_NAMES[code.toUpperCase()] ?? code;
}

export function getCountryLabel(code: string): string {
  const name = COUNTRY_NAMES[code.toUpperCase()];
  return name ? `${code.toUpperCase()} — ${name}` : code.toUpperCase();
}
