export const COUNTRY_DEFAULT_CURRENCY: Record<string, string> = {
  MY: "MYR",
  SG: "SGD",
  US: "USD",
  GB: "GBP",
  DE: "EUR",
  FR: "EUR",
  JP: "JPY",
  IN: "INR",
  AU: "AUD",
  CN: "CNY",
  KR: "KRW",
  TH: "THB",
  ID: "IDR",
  PH: "PHP",
  VN: "VND",
  AE: "AED",
  SA: "SAR",
  BR: "BRL",
  CA: "CAD",
  IT: "EUR",
  ES: "EUR",
  NL: "EUR",
  BE: "EUR",
  AT: "EUR",
  CH: "CHF",
  SE: "SEK",
  NO: "NOK",
  DK: "DKK",
  FI: "EUR",
  NZ: "NZD",
  ZA: "ZAR",
  MX: "MXN",
  PL: "PLN",
  CZ: "CZK",
  HU: "HUF",
  LU: "EUR",
  IE: "EUR",
  PT: "EUR",
};

export function getDefaultCurrency(countryCode: string): string {
  return COUNTRY_DEFAULT_CURRENCY[countryCode.toUpperCase()] ?? "USD";
}
