export const COUNTRY_REGULATORY_FRAMEWORKS: Record<string, string[]> = {
  MY: ["IFRS", "PDPA", "GST"],
  SG: ["IFRS", "PDPA", "GST"],
  US: ["SOX", "US-GAAP", "HIPAA", "CCPA"],
  GB: ["IFRS", "GDPR"],
  DE: ["IFRS", "GDPR"],
  FR: ["IFRS", "GDPR"],
  IN: ["IFRS", "GST"],
  AU: ["IFRS"],
  JP: ["IFRS", "SOX"],
  IT: ["IFRS", "GDPR"],
  ES: ["IFRS", "GDPR"],
  NL: ["IFRS", "GDPR"],
  BE: ["IFRS", "GDPR"],
  AT: ["IFRS", "GDPR"],
  CH: ["IFRS"],
  SE: ["IFRS", "GDPR"],
  NO: ["IFRS", "GDPR"],
  DK: ["IFRS", "GDPR"],
  FI: ["IFRS", "GDPR"],
  BR: ["IFRS", "LGPD"],
  CN: ["IFRS", "PIPL"],
  KR: ["IFRS"],
  CA: ["IFRS", "SOX"],
  ZA: ["IFRS"],
  AE: ["IFRS", "VAT"],
  SA: ["IFRS", "VAT"],
  ID: ["IFRS", "GST"],
  TH: ["IFRS", "PDPA"],
  PH: ["IFRS"],
  VN: ["IFRS"],
  MX: ["IFRS"],
  PL: ["IFRS", "GDPR"],
  CZ: ["IFRS", "GDPR"],
  HU: ["IFRS", "GDPR"],
};

export function getRelevantFrameworks(countryCode: string): string[] {
  return COUNTRY_REGULATORY_FRAMEWORKS[countryCode.toUpperCase()] ?? [];
}

export const COUNTRY_LANGUAGES: Record<string, string[]> = {
  MY: ["EN", "MS"],
  SG: ["EN", "ZH", "MS"],
  US: ["EN", "ES"],
  GB: ["EN"],
  DE: ["DE", "EN"],
  FR: ["FR", "EN"],
  JP: ["JA", "EN"],
  IN: ["EN", "HI"],
  AU: ["EN"],
  CN: ["ZH", "EN"],
  KR: ["KO", "EN"],
  BR: ["PT", "EN"],
  IT: ["IT", "EN"],
  ES: ["ES", "EN"],
  NL: ["NL", "EN"],
  BE: ["NL", "FR", "EN"],
  AT: ["DE", "EN"],
  CH: ["DE", "FR", "EN"],
  SE: ["SV", "EN"],
  NO: ["NO", "EN"],
  DK: ["DA", "EN"],
  FI: ["FI", "EN"],
  CA: ["EN", "FR"],
  TH: ["TH", "EN"],
  ID: ["ID", "EN"],
  PH: ["EN"],
  VN: ["VI", "EN"],
  MX: ["ES", "EN"],
  PL: ["PL", "EN"],
  SA: ["AR", "EN"],
  AE: ["AR", "EN"],
};

export function getRelevantLanguages(countryCode: string): string[] {
  return COUNTRY_LANGUAGES[countryCode.toUpperCase()] ?? [];
}
