/**
 * Curated business context metadata for scope items.
 *
 * Maps SAP scope item IDs to business-friendly descriptions,
 * affected SAP modules, key configuration areas, master data
 * requirements, and cross-scope dependencies.
 *
 * This data was manually curated from SAP Best Practices 2508
 * documentation analysis. It is NOT auto-generated.
 *
 * Used by:
 * - BusinessQuestionCard (activity-level business questions)
 * - ImplicationsPanel (classification impact display)
 * - Enhanced sidebar (process chain context)
 */

// --- Types ---

export interface ScopeItemModuleInfo {
  code: string;
  name: string;
}

export interface ScopeItemMasterData {
  objectName: string;
  sapCode?: string | undefined;
  description: string;
}

export interface ScopeItemDependency {
  scopeItemId: string;
  name: string;
  reason: string;
  type: "required" | "recommended" | "optional";
}

export interface ActivityMetadata {
  activityTitlePattern: string;
  businessQuestion: string;
  thinkAbout: string;
  modules: string[];
  configAreas: string[];
  masterDataNeeded: string[];
  effortCategory: "low" | "medium" | "high";
}

export interface ClassificationImplication {
  fitDescription: string;
  configureDescription: string;
  gapDescription: string;
  naDescription: string;
  naImpact: string;
}

export interface ScopeItemMetadata {
  id: string;
  businessName: string;
  businessDescription: string;
  modules: ScopeItemModuleInfo[];
  masterData: ScopeItemMasterData[];
  dependencies: ScopeItemDependency[];
  activityMetadata: ActivityMetadata[];
  defaultImplications: ClassificationImplication;
}

// --- Data ---

export const SCOPE_ITEM_METADATA: Record<string, ScopeItemMetadata> = {
  // =====================================================================
  // J60 — Accounts Payable
  // =====================================================================
  J60: {
    id: "J60",
    businessName: "Accounts Payable",
    businessDescription:
      "Manage supplier invoices, payments, and related financial operations including payment approval, down payments, and reporting.",
    modules: [
      { code: "FI-AP", name: "Accounts Payable" },
      { code: "FI-GL", name: "General Ledger" },
      { code: "FI-BL", name: "Cash Management" },
      { code: "FI-AR", name: "Accounts Receivable" },
    ],
    masterData: [
      { objectName: "Supplier Master", sapCode: "BND", description: "Vendors with payment terms, bank details, and tax information" },
      { objectName: "G/L Account Master", sapCode: "BNG", description: "Expense and balance sheet accounts for AP postings" },
      { objectName: "House Bank Master", description: "Bank accounts used for outgoing payments" },
      { objectName: "Cost Center", sapCode: "BNM", description: "Cost centers for expense allocation" },
      { objectName: "Profit Center", sapCode: "BNH", description: "Profit centers for management reporting" },
    ],
    dependencies: [
      { scopeItemId: "J58", name: "Accounting & Financial Close", reason: "Posting periods must be open for invoice and payment postings", type: "required" },
      { scopeItemId: "J45", name: "Procurement of Direct Materials", reason: "PO-based invoices reference purchase orders from procurement", type: "recommended" },
      { scopeItemId: "BFB", name: "Basic Cash Operations", reason: "Bank statement processing for payment reconciliation", type: "required" },
      { scopeItemId: "1EG", name: "Bank Statement Integration", reason: "Electronic bank statement import and matching", type: "recommended" },
      { scopeItemId: "J77", name: "Advanced Bank Account Management", reason: "Payment approval workflows and bank integration", type: "optional" },
    ],
    activityMetadata: [
      // --- Preliminary / Additional Information ---
      {
        activityTitlePattern: "Additional Information",
        businessQuestion: "Does your implementation team need to configure system-level settings for accounts payable?",
        thinkAbout: "Think about: these are technical setup activities handled by your SAP consultant during implementation. You typically only need to review if you have specific requirements.",
        modules: ["FI-AP"],
        configAreas: ["BRF+ rules", "eDocument settings", "Output determination"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Preliminary Steps",
        businessQuestion: "Does your implementation team need to configure system-level settings for accounts payable?",
        thinkAbout: "Think about: these are technical setup activities handled by your SAP consultant during implementation. You typically only need to review if you have specific requirements.",
        modules: ["FI-AP"],
        configAreas: ["BRF+ rules", "eDocument settings", "Output determination"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Test Procedures",
        businessQuestion: "Does your team need to validate the accounts payable process through testing?",
        thinkAbout: "Think about: this is SAP test documentation. Your implementation team will use these procedures during user acceptance testing.",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      // --- Preparation of Payments ---
      {
        activityTitlePattern: "Maintain Business Partner",
        businessQuestion: "How do you manage your supplier records?",
        thinkAbout: "Think about: who creates and maintains supplier records in your company? What information do you track for each supplier (bank details, payment terms, tax IDs)?",
        modules: ["FI-AP"],
        configAreas: ["Business partner roles", "Number ranges", "Account groups"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Display Supplier List",
        businessQuestion: "Do you need a centralized view of all your suppliers?",
        thinkAbout: "Think about: how does your AP team currently look up supplier information? Do you need to search by name, location, or payment terms?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Netting",
        businessQuestion: "Does your company offset receivables against payables for the same business partner?",
        thinkAbout: "Think about: do any of your business partners act as both a customer and a supplier? If so, do you net the amounts before paying?",
        modules: ["FI-AP", "FI-AR"],
        configAreas: ["Netting agreements", "Clearing rules"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Available Amounts",
        businessQuestion: "Do you need to check available cash before processing payments?",
        thinkAbout: "Think about: does your finance team check bank balances or cash availability before scheduling payment runs?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Cash position", "Liquidity forecast"],
        masterDataNeeded: ["House Bank Master"],
        effortCategory: "low",
      },
      // --- Invoice Entry ---
      {
        activityTitlePattern: "Invoice Entry without Purchase Order",
        businessQuestion: "Do you receive invoices that don't reference a purchase order?",
        thinkAbout: "Think about: do you get invoices for services, utilities, rent, or other expenses that aren't tied to a purchase order? How do you currently process these?",
        modules: ["FI-AP", "FI-GL"],
        configAreas: ["Tolerance groups", "Tax codes", "G/L account determination"],
        masterDataNeeded: ["Supplier Master", "G/L Account Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Invoice Entry for One-Time Supplier",
        businessQuestion: "Do you occasionally pay suppliers you don't have a permanent record for?",
        thinkAbout: "Think about: do you receive invoices from one-off suppliers? How do you handle their bank details and tax information?",
        modules: ["FI-AP"],
        configAreas: ["One-time account settings"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      // --- Park and Post ---
      {
        activityTitlePattern: "Park",
        businessQuestion: "Do invoices go through a parking/approval step before posting?",
        thinkAbout: "Think about: can your AP clerks post invoices directly, or do they need to be reviewed and approved first? What are your approval limits?",
        modules: ["FI-AP"],
        configAreas: ["Parking workflow", "Approval rules", "Authorization limits"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Post Invoice",
        businessQuestion: "How do you finalize and post supplier invoices?",
        thinkAbout: "Think about: what checks happen before an invoice is posted? Do you verify amounts, tax calculations, and account assignments?",
        modules: ["FI-AP", "FI-GL"],
        configAreas: ["Posting rules", "Tax determination"],
        masterDataNeeded: ["Supplier Master", "G/L Account Master"],
        effortCategory: "low",
      },
      // --- Recurring Invoices ---
      {
        activityTitlePattern: "Recurring",
        businessQuestion: "Do you have recurring supplier invoices (e.g., rent, subscriptions, maintenance contracts)?",
        thinkAbout: "Think about: do you receive the same invoice amount from certain suppliers every month? How do you handle these today - manually or automatically?",
        modules: ["FI-AP"],
        configAreas: ["Recurring entry templates", "Schedule parameters"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      // --- Mass Upload ---
      {
        activityTitlePattern: "Mass Import",
        businessQuestion: "Do you need to upload large batches of supplier invoices from external systems?",
        thinkAbout: "Think about: do you receive invoice files from other systems, scanning solutions, or EDI? How many invoices per month do you process?",
        modules: ["FI-AP"],
        configAreas: ["Upload templates", "Mapping rules", "Error handling"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      // --- Invoice Payment Preparation ---
      {
        activityTitlePattern: "View Supplier Line Items",
        businessQuestion: "How does your AP team review open supplier invoices?",
        thinkAbout: "Think about: how do you currently check what you owe to each supplier? Do you need to filter by due date, amount, or aging?",
        modules: ["FI-AP"],
        configAreas: ["Line item display variants"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Payment Block",
        businessQuestion: "Do you sometimes block invoices from being paid?",
        thinkAbout: "Think about: are there situations where you hold payment on an invoice (disputes, quality issues, missing documentation)? Who can block and unblock payments?",
        modules: ["FI-AP"],
        configAreas: ["Block reasons", "Release procedures"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "View Supplier Balance",
        businessQuestion: "Do you need to see the total balance owed to each supplier?",
        thinkAbout: "Think about: how does your finance team check the overall position with a supplier, including open items and cleared items?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      // --- Payment Run ---
      {
        activityTitlePattern: "Payment Run",
        businessQuestion: "How do you batch-process payments to suppliers?",
        thinkAbout: "Think about: how often do you run payments (daily, weekly, monthly)? What payment methods do you use (bank transfer, check, direct debit)?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Payment methods", "Bank determination", "Payment batches", "House bank selection"],
        masterDataNeeded: ["House Bank Master", "Supplier Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Schedule Proposal",
        businessQuestion: "How do you schedule and review payment proposals before execution?",
        thinkAbout: "Think about: who reviews the list of payments before they are sent to the bank? Can they add or remove items from the run?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Proposal scheduling", "Payment terms"],
        masterDataNeeded: ["Supplier Master", "House Bank Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Revise Proposal",
        businessQuestion: "Do you need to modify payment proposals before releasing them?",
        thinkAbout: "Think about: after the system generates a payment proposal, does your team need to adjust amounts, remove certain invoices, or change payment dates?",
        modules: ["FI-AP"],
        configAreas: ["Proposal editing rules"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Release Proposal",
        businessQuestion: "Who authorizes the final payment run?",
        thinkAbout: "Think about: what approval is needed before payments are actually executed? Is there a dual-approval requirement?",
        modules: ["FI-AP"],
        configAreas: ["Release procedures", "Authorization levels"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Mass Reverse",
        businessQuestion: "Do you sometimes need to reverse an entire payment run?",
        thinkAbout: "Think about: has there ever been a situation where you needed to undo an entire payment batch? How did you handle it?",
        modules: ["FI-AP"],
        configAreas: ["Reversal reasons"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Payment List",
        businessQuestion: "Do you need to track and report on completed payment runs?",
        thinkAbout: "Think about: how do you currently confirm which payments were made? Do you need a record for audit purposes?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Payment Plan",
        businessQuestion: "Do you use payment plans for large supplier invoices?",
        thinkAbout: "Think about: do you ever split a large invoice into multiple installment payments? How do you track the payment schedule?",
        modules: ["FI-AP"],
        configAreas: ["Installment plans", "Payment terms"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      // --- Single Outgoing Payment ---
      {
        activityTitlePattern: "Single Outgoing Payment",
        businessQuestion: "Do you make individual ad-hoc payments outside of the regular payment run?",
        thinkAbout: "Think about: are there urgent payments that can't wait for the next batch run? How do you handle emergency supplier payments?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Manual payment methods", "Bank account selection"],
        masterDataNeeded: ["House Bank Master", "Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Single Payment",
        businessQuestion: "Do you make individual ad-hoc payments outside of the regular payment run?",
        thinkAbout: "Think about: are there urgent payments that can't wait for the next batch run? How do you handle emergency supplier payments?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Manual payment methods", "Bank account selection"],
        masterDataNeeded: ["House Bank Master", "Supplier Master"],
        effortCategory: "low",
      },
      // --- Online Payments ---
      {
        activityTitlePattern: "Free Form Payment",
        businessQuestion: "Do you process online payments that aren't linked to a specific invoice?",
        thinkAbout: "Think about: do you make payments directly from your bank portal for one-off expenses, refunds, or transfers?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Online payment settings"],
        masterDataNeeded: ["House Bank Master"],
        effortCategory: "low",
      },
      // --- Manual Payment ---
      {
        activityTitlePattern: "Post Outgoing Payment",
        businessQuestion: "Do you manually record outgoing payments?",
        thinkAbout: "Think about: do you sometimes post payments manually (e.g., for cash payments or payments made outside the system)?",
        modules: ["FI-AP"],
        configAreas: ["Payment posting rules"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      // --- Payment Approval ---
      {
        activityTitlePattern: "Payment Approval",
        businessQuestion: "Do outgoing payments require manager approval before release?",
        thinkAbout: "Think about: what are your approval thresholds? Who can approve payments of different amounts? Do you need dual signatures?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Approval thresholds", "Signatory assignments", "Multi-level approval"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Bank Payment Approval",
        businessQuestion: "Does your bank require additional approval for certain payments?",
        thinkAbout: "Think about: does your bank have threshold-based approval requirements? Do you use bank-side authorization tokens?",
        modules: ["FI-BL"],
        configAreas: ["Bank approval integration"],
        masterDataNeeded: ["House Bank Master"],
        effortCategory: "medium",
      },
      // --- Payment Media ---
      {
        activityTitlePattern: "Payment Media",
        businessQuestion: "How do you generate payment files for your bank?",
        thinkAbout: "Think about: what file format does your bank require (ISO 20022, local format)? Do you generate check prints or electronic files?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: ["Payment media formats", "Bank file specifications"],
        masterDataNeeded: ["House Bank Master"],
        effortCategory: "medium",
      },
      // --- Payment Advices ---
      {
        activityTitlePattern: "Payment Advice",
        businessQuestion: "Do you send payment notifications to your suppliers?",
        thinkAbout: "Think about: do your suppliers expect a remittance advice when you pay them? By email or printed letter?",
        modules: ["FI-AP"],
        configAreas: ["Advice output channels", "Email templates"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      // --- Correspondence ---
      {
        activityTitlePattern: "Correspondence",
        businessQuestion: "Do you send formal correspondence to suppliers (account statements, balance confirmations)?",
        thinkAbout: "Think about: do you send periodic statements to suppliers? Do auditors require supplier balance confirmations?",
        modules: ["FI-AP"],
        configAreas: ["Correspondence types", "Output templates"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      // --- Incorrect Posting ---
      {
        activityTitlePattern: "Reset Cleared Items",
        businessQuestion: "Do you sometimes need to reverse or correct payment postings?",
        thinkAbout: "Think about: how do you handle situations where a payment was applied to the wrong invoice or needs to be reversed?",
        modules: ["FI-AP"],
        configAreas: ["Reversal reasons", "Clearing reset procedures"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Reset and Reverse",
        businessQuestion: "Do you need to both reset and reverse cleared items?",
        thinkAbout: "Think about: do you need to not only undo the clearing but also reverse the original document?",
        modules: ["FI-AP"],
        configAreas: ["Reversal reasons"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      // --- Down Payments ---
      {
        activityTitlePattern: "Down Payment",
        businessQuestion: "Does your company make advance payments to suppliers before receiving goods or services?",
        thinkAbout: "Think about: do you pay deposits or advances for large purchases? How do you track these against final invoices?",
        modules: ["FI-AP", "FI-GL"],
        configAreas: ["Down payment account determination", "Clearing rules", "Workflow for approval"],
        masterDataNeeded: ["Supplier Master", "G/L Account Master"],
        effortCategory: "medium",
      },
      // --- Interest Calculation ---
      {
        activityTitlePattern: "Interest",
        businessQuestion: "Do you calculate interest on overdue supplier balances?",
        thinkAbout: "Think about: do your supplier contracts include late payment interest clauses? Do you need to calculate interest for tax or legal compliance?",
        modules: ["FI-AP"],
        configAreas: ["Interest calculation rules", "Interest rates", "Job scheduling"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      // --- Guarantees ---
      {
        activityTitlePattern: "Guarantees Received",
        businessQuestion: "Do you receive bank guarantees or letters of credit from suppliers?",
        thinkAbout: "Think about: do your contracts require suppliers to provide performance guarantees? How do you track guarantee validity dates?",
        modules: ["FI-AP"],
        configAreas: ["Guarantee types", "Validity tracking"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      // --- Periodic Activities ---
      {
        activityTitlePattern: "Periodic Activities",
        businessQuestion: "What month-end activities do you perform for accounts payable?",
        thinkAbout: "Think about: what closing tasks does your AP team do at month-end? Do you send balance confirmations? Do you check open item aging?",
        modules: ["FI-AP", "FI-GL"],
        configAreas: ["Balance confirmation", "Reconciliation procedures"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Check Open Balances",
        businessQuestion: "Do you regularly reconcile open supplier balances?",
        thinkAbout: "Think about: how does your team verify that all open invoices are accounted for at period end?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Balance Confirmation",
        businessQuestion: "Do you send balance confirmation requests to your suppliers?",
        thinkAbout: "Think about: do you need to confirm balances with suppliers for audit or reconciliation purposes?",
        modules: ["FI-AP"],
        configAreas: ["Confirmation templates", "Scheduling"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      // --- Reporting ---
      {
        activityTitlePattern: "Invoice Management Reporting",
        businessQuestion: "What reports do you need for monitoring payables?",
        thinkAbout: "Think about: what information does your management need? Overdue payables, aging analysis, cash discount utilization, payment forecasts?",
        modules: ["FI-AP"],
        configAreas: ["Report variants", "Dashboard layouts"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "AP Overview",
        businessQuestion: "Do you need a dashboard view of your accounts payable status?",
        thinkAbout: "Think about: who needs to see the overall AP position? What key metrics matter to your finance team?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Days Payable Outstanding",
        businessQuestion: "Do you track days payable outstanding (DPO) as a key metric?",
        thinkAbout: "Think about: does your management monitor how long you take to pay suppliers? Is DPO a KPI for your finance team?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Overdue Payables",
        businessQuestion: "Do you monitor overdue supplier invoices?",
        thinkAbout: "Think about: how do you track which invoices are past their payment due date? What action is taken on overdue items?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Future Payables",
        businessQuestion: "Do you forecast upcoming payment obligations?",
        thinkAbout: "Think about: does your treasury team need to know what payments are coming due in the next weeks or months?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Cash Discount",
        businessQuestion: "Do you track and optimize early payment discounts?",
        thinkAbout: "Think about: do your suppliers offer discounts for early payment? Do you have a strategy to maximize discount capture?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Invoice Processing",
        businessQuestion: "Do you monitor invoice processing efficiency?",
        thinkAbout: "Think about: do you track how long it takes to process invoices from receipt to posting? Is processing time a KPI?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Aging",
        businessQuestion: "Do you use aging analysis for your payables?",
        thinkAbout: "Think about: do you categorize open invoices by how long they've been outstanding (30/60/90 days)?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Payments Analysis",
        businessQuestion: "Do you analyze your payment patterns?",
        thinkAbout: "Think about: do you review which payment methods are most used? Do you compare automatic vs. manual payment volumes?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Item Change Log",
        businessQuestion: "Do you need an audit trail of changes to AP line items?",
        thinkAbout: "Think about: does your audit or compliance team need to track who changed what on supplier invoices and payments?",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      // --- eDocument ---
      {
        activityTitlePattern: "eDocument",
        businessQuestion: "Do you process electronic invoices (e-invoicing)?",
        thinkAbout: "Think about: does your country require electronic invoicing? Do you receive invoices in electronic formats (XML, EDI, Peppol)?",
        modules: ["FI-AP"],
        configAreas: ["eDocument framework", "Electronic format mapping"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      // --- Appendix ---
      {
        activityTitlePattern: "Display Process Flow",
        businessQuestion: "Do you need a visual overview of the accounts payable process flow?",
        thinkAbout: "Think about: this is a reference diagram showing how the AP process is structured in SAP.",
        modules: ["FI-AP"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      // --- Monitor Payments ---
      {
        activityTitlePattern: "Monitor Payments",
        businessQuestion: "Do you need to monitor payment status in real time?",
        thinkAbout: "Think about: does your treasury team need to track whether payments have been sent and received by the bank?",
        modules: ["FI-AP", "FI-BL"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
    ],
    defaultImplications: {
      fitDescription: "SAP standard accounts payable processing will be configured as-is. Your AP team will follow SAP best practice workflows for invoice entry, payment processing, and reporting.",
      configureDescription: "Your accounts payable process will use SAP standard with configuration adjustments. This typically involves modifying payment terms, approval thresholds, tolerance groups, or output formats to match your specific requirements.",
      gapDescription: "Your accounts payable process differs significantly from SAP standard. This will require a gap resolution workshop to determine the best approach: custom development, a third-party solution, or adapting your process to align closer with SAP.",
      naDescription: "This accounts payable capability is not needed for your organization.",
      naImpact: "Excluding AP capabilities may affect your ability to process supplier invoices, make payments, and generate AP reports within SAP. Verify that an alternative system or process will handle these functions.",
    },
  },

  // =====================================================================
  // J59 — Accounts Receivable
  // =====================================================================
  J59: {
    id: "J59",
    businessName: "Accounts Receivable",
    businessDescription:
      "Manage customer invoices, incoming payments, dunning, credit memos, and receivables reporting.",
    modules: [
      { code: "FI-AR", name: "Accounts Receivable" },
      { code: "FI-GL", name: "General Ledger" },
      { code: "FI-BL", name: "Cash Management" },
    ],
    masterData: [
      { objectName: "Customer Master", sapCode: "BND", description: "Customers with payment terms, credit limits, and dunning procedures" },
      { objectName: "G/L Account Master", sapCode: "BNG", description: "Revenue and balance sheet accounts for AR postings" },
      { objectName: "House Bank Master", description: "Bank accounts used for incoming payments" },
    ],
    dependencies: [
      { scopeItemId: "J58", name: "Accounting & Financial Close", reason: "Posting periods must be open for invoice and payment postings", type: "required" },
      { scopeItemId: "BKP", name: "Sales Order Processing", reason: "Sales invoices originate from sales order billing", type: "recommended" },
      { scopeItemId: "1EG", name: "Bank Statement Integration", reason: "Electronic bank statement for incoming payment matching", type: "recommended" },
      { scopeItemId: "1EZ", name: "Credit Memo Processing", reason: "Handles customer returns and credit adjustments", type: "optional" },
    ],
    activityMetadata: [
      {
        activityTitlePattern: "Additional Information",
        businessQuestion: "Does your implementation team need to configure system-level settings for accounts receivable?",
        thinkAbout: "Think about: these are technical setup activities handled by your SAP consultant during implementation.",
        modules: ["FI-AR"],
        configAreas: ["BRF+ rules", "eDocument settings", "Dunning output templates"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Preliminary Steps",
        businessQuestion: "Does your implementation team need to configure system-level settings for accounts receivable?",
        thinkAbout: "Think about: these are technical setup activities such as accounting clerk assignments, BRF+ rules, and output settings.",
        modules: ["FI-AR"],
        configAreas: ["Accounting clerk", "BRF+ settings", "Situation types"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Test Procedures",
        businessQuestion: "Does your team need to validate the accounts receivable process through testing?",
        thinkAbout: "Think about: this is SAP test documentation used during user acceptance testing.",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Maintain Business Partner",
        businessQuestion: "How do you manage your customer records?",
        thinkAbout: "Think about: who creates and maintains customer records? What customer information is critical (credit terms, contact details, payment methods)?",
        modules: ["FI-AR"],
        configAreas: ["Business partner roles", "Account groups"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Display Customer List",
        businessQuestion: "Do you need a centralized view of all your customers?",
        thinkAbout: "Think about: how does your AR team currently look up customer information?",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Enter Invoice Without Sales Order",
        businessQuestion: "Do you create customer invoices that are not linked to a sales order?",
        thinkAbout: "Think about: do you invoice for consulting, one-off services, or other items not managed through the sales order process?",
        modules: ["FI-AR", "FI-GL"],
        configAreas: ["Invoice types", "Tax codes", "G/L account determination"],
        masterDataNeeded: ["Customer Master", "G/L Account Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Mass Import of Customer Invoices",
        businessQuestion: "Do you need to upload large batches of customer invoices?",
        thinkAbout: "Think about: do you generate invoices in bulk from external systems that need to be imported into SAP?",
        modules: ["FI-AR"],
        configAreas: ["Upload templates", "Mapping rules"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Invoice Reporting",
        businessQuestion: "Do you need reports on customer invoicing activity?",
        thinkAbout: "Think about: what invoice-related reports does your team need? Volume, trends, aging?",
        modules: ["FI-AR"],
        configAreas: ["Report variants"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Dunning",
        businessQuestion: "Do you send payment reminders to customers who haven't paid on time?",
        thinkAbout: "Think about: how many dunning levels do you use? Do you send letters, emails, or both? What escalation path do you follow?",
        modules: ["FI-AR"],
        configAreas: ["Dunning procedures", "Dunning levels", "Output templates", "Dunning areas"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Correspondence",
        businessQuestion: "Do you send formal correspondence to customers (statements, confirmations)?",
        thinkAbout: "Think about: do you send account statements or other correspondence to customers regularly?",
        modules: ["FI-AR"],
        configAreas: ["Correspondence types", "Output channels"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Invoice Management Reporting",
        businessQuestion: "What reports do you need for monitoring receivables?",
        thinkAbout: "Think about: what metrics matter to your AR team? Overdue receivables, DSO, aging analysis, collection tracking?",
        modules: ["FI-AR"],
        configAreas: ["Report variants"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Accounts Receivable Overview",
        businessQuestion: "Do you need a dashboard view of your receivables status?",
        thinkAbout: "Think about: who needs to see the overall AR position?",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Overdue Receivables",
        businessQuestion: "Do you monitor overdue customer invoices?",
        thinkAbout: "Think about: how do you track which customers are past due? Do you categorize by risk class?",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Days Sales Outstanding",
        businessQuestion: "Do you track days sales outstanding (DSO) as a key metric?",
        thinkAbout: "Think about: is DSO a KPI for your finance team? How do you benchmark it?",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Cash Collection Tracker",
        businessQuestion: "Do you track cash collection performance?",
        thinkAbout: "Think about: does your team monitor collection rates and forecast incoming cash?",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Down Payment",
        businessQuestion: "Does your company receive advance payments from customers before delivering goods or services?",
        thinkAbout: "Think about: do customers pay deposits? How do you track and clear these against final invoices?",
        modules: ["FI-AR", "FI-GL"],
        configAreas: ["Down payment account determination", "Clearing rules"],
        masterDataNeeded: ["Customer Master", "G/L Account Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Electronic Bank Statement",
        businessQuestion: "Do you receive electronic bank statements for matching incoming payments?",
        thinkAbout: "Think about: does your bank provide daily electronic statements? How do you match bank transactions to open invoices?",
        modules: ["FI-AR", "FI-BL"],
        configAreas: ["Bank statement processing rules", "Matching algorithms", "Cash application"],
        masterDataNeeded: ["House Bank Master", "Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Cash Application",
        businessQuestion: "Do you use automated cash application for incoming payments?",
        thinkAbout: "Think about: how do you match incoming bank payments to open invoices? Manually or with automated rules?",
        modules: ["FI-AR", "FI-BL"],
        configAreas: ["Cash application rules", "AI matching"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Reprocess Bank Statement",
        businessQuestion: "Do you need to reprocess failed bank statement items?",
        thinkAbout: "Think about: what happens when an incoming payment can't be automatically matched?",
        modules: ["FI-AR", "FI-BL"],
        configAreas: ["Reprocessing rules"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Payment Advice",
        businessQuestion: "Do your customers send payment advices with their payments?",
        thinkAbout: "Think about: do customers tell you which invoices they're paying? Do you process remittance advices?",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Clear Open Items",
        businessQuestion: "How do you manually clear open customer items?",
        thinkAbout: "Think about: when automatic clearing fails, how does your team manually match payments to invoices?",
        modules: ["FI-AR"],
        configAreas: ["Clearing tolerance"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Post Incoming Payment",
        businessQuestion: "How do you record incoming payments without electronic bank statements?",
        thinkAbout: "Think about: do you receive payments by check, cash, or manual bank transfer that need to be recorded individually?",
        modules: ["FI-AR"],
        configAreas: ["Payment methods"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Incorrect Posting",
        businessQuestion: "Do you sometimes need to reverse or correct payment postings?",
        thinkAbout: "Think about: how do you handle situations where a payment was applied incorrectly?",
        modules: ["FI-AR"],
        configAreas: ["Reversal reasons"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Reverse",
        businessQuestion: "Do you need to reverse individual financial documents?",
        thinkAbout: "Think about: how do you handle posting errors that need complete reversal?",
        modules: ["FI-AR"],
        configAreas: ["Reversal reasons"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Customer Line Items",
        businessQuestion: "How does your AR team review open customer items?",
        thinkAbout: "Think about: how do you currently check what customers owe? Do you need aging views, filtering by amount or date?",
        modules: ["FI-AR"],
        configAreas: ["Line item display variants"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Interest Calculation",
        businessQuestion: "Do you calculate interest on overdue customer balances?",
        thinkAbout: "Think about: do you charge late payment interest? Is this required by law or contract in your markets?",
        modules: ["FI-AR"],
        configAreas: ["Interest rates", "Calculation rules", "Job scheduling"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Guarantees Made",
        businessQuestion: "Do you issue bank guarantees or letters of credit for customers?",
        thinkAbout: "Think about: do you provide performance guarantees or letters of credit to your customers?",
        modules: ["FI-AR"],
        configAreas: ["Guarantee types"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Periodic Activities",
        businessQuestion: "What month-end activities do you perform for accounts receivable?",
        thinkAbout: "Think about: what closing tasks does your AR team do? Balance confirmations, bad debt write-offs, reconciliation?",
        modules: ["FI-AR", "FI-GL"],
        configAreas: ["Balance confirmation", "Write-off reasons"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Bad Debt",
        businessQuestion: "Do you write off uncollectible customer debts?",
        thinkAbout: "Think about: how do you handle customers who can't or won't pay? What is your write-off policy and approval process?",
        modules: ["FI-AR", "FI-GL"],
        configAreas: ["Write-off reasons", "Approval workflow"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "eInvoice",
        businessQuestion: "Do you process electronic invoices for customers?",
        thinkAbout: "Think about: does your country require electronic invoicing? Do you send invoices in electronic formats?",
        modules: ["FI-AR"],
        configAreas: ["eDocument framework"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "eDocument Cockpit",
        businessQuestion: "Do you need to monitor electronic document processing?",
        thinkAbout: "Think about: if you use e-invoicing, do you need a central dashboard to track document status?",
        modules: ["FI-AR"],
        configAreas: ["eDocument monitoring"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Display Process Flow",
        businessQuestion: "Do you need a visual overview of the accounts receivable process flow?",
        thinkAbout: "Think about: this is a reference diagram showing how the AR process is structured in SAP.",
        modules: ["FI-AR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
    ],
    defaultImplications: {
      fitDescription: "SAP standard accounts receivable processing will be configured as-is. Your AR team will follow SAP best practice workflows for invoicing, payment collection, dunning, and reporting.",
      configureDescription: "Your accounts receivable process will use SAP standard with configuration adjustments. This typically involves modifying dunning procedures, payment terms, credit limits, or output formats.",
      gapDescription: "Your accounts receivable process differs significantly from SAP standard. This will require a gap resolution workshop to determine the best approach.",
      naDescription: "This accounts receivable capability is not needed for your organization.",
      naImpact: "Excluding AR capabilities may affect your ability to invoice customers, collect payments, and generate receivables reports within SAP.",
    },
  },

  // =====================================================================
  // J45 — Procurement of Direct Materials
  // =====================================================================
  J45: {
    id: "J45",
    businessName: "Procurement of Direct Materials",
    businessDescription:
      "End-to-end procurement from purchase requisition through purchase order, goods receipt, invoice verification, and payment.",
    modules: [
      { code: "MM-PUR", name: "Purchasing" },
      { code: "MM-IM", name: "Inventory Management" },
      { code: "FI-AP", name: "Accounts Payable" },
      { code: "FI-GL", name: "General Ledger" },
    ],
    masterData: [
      { objectName: "Material Master", description: "Materials with procurement and valuation data" },
      { objectName: "Supplier Master", sapCode: "BND", description: "Vendors with purchasing organization data" },
      { objectName: "Purchasing Info Record", description: "Material-supplier price and conditions" },
      { objectName: "Source List", description: "Approved suppliers per material" },
    ],
    dependencies: [
      { scopeItemId: "J60", name: "Accounts Payable", reason: "Invoice verification and payment processing", type: "required" },
      { scopeItemId: "J58", name: "Accounting & Financial Close", reason: "GR/IR clearing and period-end postings", type: "required" },
      { scopeItemId: "1YB", name: "Basic Warehouse Management", reason: "Goods receipt processing in warehouse", type: "recommended" },
    ],
    activityMetadata: [
      {
        activityTitlePattern: "Additional Information",
        businessQuestion: "Does your implementation team need to configure procurement system settings?",
        thinkAbout: "Think about: these are technical setup activities handled by your SAP consultant during implementation.",
        modules: ["MM-PUR"],
        configAreas: ["Purchasing info records", "Source lists", "Workflow settings", "eDocument setup"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Preliminary Steps",
        businessQuestion: "Does your implementation team need to configure procurement system settings?",
        thinkAbout: "Think about: these include creating purchasing info records, setting up workflows, and configuring BRF+ rules.",
        modules: ["MM-PUR"],
        configAreas: ["Flexible workflow", "Approval conditions"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Test Procedures",
        businessQuestion: "Does your team need to validate the procurement process through testing?",
        thinkAbout: "Think about: this is SAP test documentation used during user acceptance testing.",
        modules: ["MM-PUR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Purchase Requisition",
        businessQuestion: "How do your employees request materials to be purchased?",
        thinkAbout: "Think about: who creates purchase requests? Is there an approval workflow? Do you have spending limits by department?",
        modules: ["MM-PUR"],
        configAreas: ["Requisition types", "Approval workflow", "Spending limits"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Convert Purchase Requisition",
        businessQuestion: "Do you convert approved purchase requisitions into purchase orders?",
        thinkAbout: "Think about: is this conversion manual or automatic? Can one requisition become multiple POs for different suppliers?",
        modules: ["MM-PUR"],
        configAreas: ["Conversion rules", "Supplier assignment"],
        masterDataNeeded: ["Supplier Master", "Material Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Create Purchase Order",
        businessQuestion: "How are purchase orders created in your company?",
        thinkAbout: "Think about: do you create POs manually, from requisitions, or from contracts? What information must be on each PO?",
        modules: ["MM-PUR"],
        configAreas: ["PO types", "Number ranges", "Output determination"],
        masterDataNeeded: ["Supplier Master", "Material Master", "Purchasing Info Record"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Approve Purchase Order",
        businessQuestion: "Do purchase orders require approval before being sent to suppliers?",
        thinkAbout: "Think about: what are your approval thresholds? Who can approve POs of different amounts? Is there a multi-level approval process?",
        modules: ["MM-PUR"],
        configAreas: ["Flexible workflow", "Approval thresholds", "Multi-level approval"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Preview Purchase Order",
        businessQuestion: "Do you preview purchase orders before sending them to suppliers?",
        thinkAbout: "Think about: do you need to review the PO document format before it goes to the supplier?",
        modules: ["MM-PUR"],
        configAreas: ["PO output formats"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Change Purchase Order",
        businessQuestion: "Do you frequently need to modify purchase orders after creation?",
        thinkAbout: "Think about: how often do you change quantities, delivery dates, or prices on existing POs?",
        modules: ["MM-PUR"],
        configAreas: ["Change authorization"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Monitor Purchase Order",
        businessQuestion: "How do you track and monitor open purchase orders?",
        thinkAbout: "Think about: how does your procurement team check PO status, delivery dates, and outstanding quantities?",
        modules: ["MM-PUR"],
        configAreas: ["Monitoring views"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Mass Changes",
        businessQuestion: "Do you need to update multiple purchase orders at once?",
        thinkAbout: "Think about: do you ever need to change delivery dates, prices, or other fields across many POs simultaneously?",
        modules: ["MM-PUR"],
        configAreas: ["Mass change authorization"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Post Goods Receipt",
        businessQuestion: "How do you record when purchased materials arrive?",
        thinkAbout: "Think about: who confirms goods receipt? Do you check quantities and quality against the PO? Do you use barcode scanning?",
        modules: ["MM-IM"],
        configAreas: ["GR processing", "Movement types", "Tolerance checks"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Goods Receipt Slip",
        businessQuestion: "Do you print goods receipt slips or labels for received materials?",
        thinkAbout: "Think about: do you need printed labels for warehouse storage or tracking purposes?",
        modules: ["MM-IM"],
        configAreas: ["GR slip format", "Label printing"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Reverse Goods Receipt",
        businessQuestion: "Do you sometimes need to reverse a goods receipt?",
        thinkAbout: "Think about: how do you handle situations where materials are returned or a goods receipt was posted in error?",
        modules: ["MM-IM"],
        configAreas: ["Reversal movement types"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Stock Overview",
        businessQuestion: "Do you need to check current stock levels?",
        thinkAbout: "Think about: how does your team check what's in stock? Do you need to see stock by warehouse, batch, or valuation type?",
        modules: ["MM-IM"],
        configAreas: ["Stock display variants"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Manage Stock",
        businessQuestion: "How do you manage and adjust inventory?",
        thinkAbout: "Think about: do you perform stock transfers, adjustments, or scrapping? How are these authorized?",
        modules: ["MM-IM"],
        configAreas: ["Movement types", "Authorization"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Create Supplier Invoice",
        businessQuestion: "How do you process supplier invoices for purchased materials?",
        thinkAbout: "Think about: do you match invoices against POs and goods receipts (3-way match)? What tolerance levels do you use?",
        modules: ["FI-AP", "MM-PUR"],
        configAreas: ["Invoice verification", "Tolerance groups", "Tax codes", "3-way matching"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Invoice Reduction",
        businessQuestion: "Do you reduce invoice amounts when they don't match the PO?",
        thinkAbout: "Think about: what happens when a supplier invoices more than the PO amount? Do you automatically reduce or reject?",
        modules: ["FI-AP"],
        configAreas: ["Invoice reduction rules"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Credit Memo",
        businessQuestion: "Do you process supplier credit memos?",
        thinkAbout: "Think about: how do you handle refunds, returns, or pricing adjustments from suppliers?",
        modules: ["FI-AP"],
        configAreas: ["Credit memo types"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Clear GR",
        businessQuestion: "Do you need to clear the GR/IR clearing account?",
        thinkAbout: "Think about: do you monitor the difference between goods received and invoices received?",
        modules: ["FI-AP", "FI-GL"],
        configAreas: ["GR/IR clearing rules"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Down Payment",
        businessQuestion: "Do you make advance payments to suppliers for direct materials?",
        thinkAbout: "Think about: do suppliers require deposits before shipping? How do you track these against final invoices?",
        modules: ["FI-AP", "MM-PUR"],
        configAreas: ["Down payment handling", "Clearing rules"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Automatic Purchase Order Creation",
        businessQuestion: "Do you automatically create purchase orders from requisitions?",
        thinkAbout: "Think about: should the system automatically convert approved requisitions to POs based on source lists and contracts?",
        modules: ["MM-PUR"],
        configAreas: ["Auto-PO rules", "Source determination"],
        masterDataNeeded: ["Source List", "Purchasing Info Record"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Automatic Conversion",
        businessQuestion: "Do you use automated conversion of purchase requisitions to purchase orders?",
        thinkAbout: "Think about: should the system automatically convert approved requisitions to POs?",
        modules: ["MM-PUR"],
        configAreas: ["Conversion rules"],
        masterDataNeeded: ["Source List"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "eDocument Cockpit",
        businessQuestion: "Do you need to monitor electronic document processing for procurement?",
        thinkAbout: "Think about: if you use e-invoicing with suppliers, do you need a dashboard to track document status?",
        modules: ["MM-PUR"],
        configAreas: ["eDocument monitoring"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Blocked Stock",
        businessQuestion: "Do you receive materials into blocked stock for quality inspection?",
        thinkAbout: "Think about: do you need to quarantine received goods before they can be used in production or sold?",
        modules: ["MM-IM"],
        configAreas: ["Blocked stock handling", "Release procedures"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Free Goods",
        businessQuestion: "Do your suppliers provide free goods with purchases?",
        thinkAbout: "Think about: do you receive bonus items or samples with your orders?",
        modules: ["MM-PUR"],
        configAreas: ["Free goods determination"],
        masterDataNeeded: ["Material Master", "Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Quantity Optimization",
        businessQuestion: "Do you optimize purchase order quantities (rounding, minimum order)?",
        thinkAbout: "Think about: do your suppliers have minimum order quantities or packing unit requirements?",
        modules: ["MM-PUR"],
        configAreas: ["Rounding profiles", "Lot size optimization"],
        masterDataNeeded: ["Purchasing Info Record"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Rework",
        businessQuestion: "Do you need a rework workflow for purchase orders?",
        thinkAbout: "Think about: when a PO is rejected during approval, does it need a structured rework and re-approval process?",
        modules: ["MM-PUR"],
        configAreas: ["Rework workflow", "Flexible workflow"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Dunning Reminder",
        businessQuestion: "Do you send delivery reminders to suppliers for overdue purchase orders?",
        thinkAbout: "Think about: do you formally remind suppliers when deliveries are late?",
        modules: ["MM-PUR"],
        configAreas: ["Dunning reminder output", "Scheduling"],
        masterDataNeeded: ["Supplier Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Task Cards",
        businessQuestion: "Do you need a task card view for purchase order approvals?",
        thinkAbout: "Think about: would your approvers benefit from a card-based visual view of pending approvals?",
        modules: ["MM-PUR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Workflow Review",
        businessQuestion: "Do you need a review step in your purchase order workflow?",
        thinkAbout: "Think about: beyond approval, do POs need a separate review step for compliance or quality checks?",
        modules: ["MM-PUR"],
        configAreas: ["Review workflow"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
    ],
    defaultImplications: {
      fitDescription: "SAP standard procurement process will be configured as-is. Your purchasing team will follow SAP best practice workflows for requisitions, POs, goods receipt, and invoice verification.",
      configureDescription: "Your procurement process will use SAP standard with configuration adjustments. This typically involves modifying approval thresholds, source determination rules, tolerance groups, or output formats.",
      gapDescription: "Your procurement process differs significantly from SAP standard. This will require a gap resolution workshop to determine the best approach.",
      naDescription: "This procurement capability is not needed for your organization.",
      naImpact: "Excluding procurement capabilities may affect your ability to manage purchase orders, track goods receipts, and verify supplier invoices within SAP.",
    },
  },

  // =====================================================================
  // 1NT — Project Control - Finance
  // =====================================================================
  "1NT": {
    id: "1NT",
    businessName: "Project Financial Control",
    businessDescription:
      "Create and manage projects with budgets, cost tracking, settlements, and period-end closing for both overhead and investment projects.",
    modules: [
      { code: "PS", name: "Project System" },
      { code: "CO", name: "Controlling" },
      { code: "FI-GL", name: "General Ledger" },
      { code: "MM-PUR", name: "Purchasing" },
    ],
    masterData: [
      { objectName: "WBS Element", description: "Work breakdown structure elements for project hierarchy" },
      { objectName: "Cost Center", sapCode: "BNM", description: "Cost centers for overhead allocation" },
      { objectName: "G/L Account Master", sapCode: "BNG", description: "Accounts for project postings and settlements" },
    ],
    dependencies: [
      { scopeItemId: "J58", name: "Accounting & Financial Close", reason: "Period-end settlement and closing activities", type: "required" },
      { scopeItemId: "J63", name: "Cost Center Accounting", reason: "Direct activity allocation from cost centers", type: "recommended" },
      { scopeItemId: "J45", name: "Procurement of Direct Materials", reason: "Project procurement for materials and services", type: "optional" },
    ],
    activityMetadata: [
      {
        activityTitlePattern: "Additional Information",
        businessQuestion: "Does your implementation team need to configure project management settings?",
        thinkAbout: "Think about: these are technical setup activities handled by your SAP consultant during implementation.",
        modules: ["PS"],
        configAreas: ["Teams and responsibilities", "Situation types"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Test Procedures",
        businessQuestion: "Does your team need to validate the project control process through testing?",
        thinkAbout: "Think about: this is SAP test documentation used during user acceptance testing.",
        modules: ["PS"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Create Project",
        businessQuestion: "How do you create and set up new projects?",
        thinkAbout: "Think about: who creates projects? What information is captured at creation (name, dates, responsible person, project type)?",
        modules: ["PS"],
        configAreas: ["Project profiles", "WBS templates", "Number ranges"],
        masterDataNeeded: ["WBS Element"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Copy Functionality",
        businessQuestion: "Do you create new projects by copying existing ones?",
        thinkAbout: "Think about: do you have standard project templates that you clone for similar projects?",
        modules: ["PS"],
        configAreas: ["Copy control"],
        masterDataNeeded: ["WBS Element"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Project Review",
        businessQuestion: "Do you conduct periodic project reviews?",
        thinkAbout: "Think about: how do you review project health, milestones, and budget consumption?",
        modules: ["PS"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Update Project",
        businessQuestion: "How do you update project details as things change?",
        thinkAbout: "Think about: who can modify project scope, timelines, and assignments?",
        modules: ["PS"],
        configAreas: ["Change authorization"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Mass Changes",
        businessQuestion: "Do you need to update multiple projects or work packages at once?",
        thinkAbout: "Think about: do you ever need to change dates, statuses, or responsible persons across many projects simultaneously?",
        modules: ["PS"],
        configAreas: ["Mass change authorization"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Planned Costs",
        businessQuestion: "How do you plan and estimate project costs?",
        thinkAbout: "Think about: do you create detailed cost plans by work package? What cost elements do you track?",
        modules: ["PS", "CO"],
        configAreas: ["Cost planning layout", "Cost elements"],
        masterDataNeeded: ["WBS Element", "Cost Center"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Project Budget",
        businessQuestion: "How do you manage project budgets?",
        thinkAbout: "Think about: do you set spending limits per project? What happens when a project exceeds its budget?",
        modules: ["PS", "CO"],
        configAreas: ["Budget profiles", "Availability control", "Tolerance limits"],
        masterDataNeeded: ["WBS Element"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Upload Project Budget",
        businessQuestion: "Do you import project budgets from external systems?",
        thinkAbout: "Think about: do you maintain budget data in spreadsheets or other systems that need to be uploaded?",
        modules: ["PS"],
        configAreas: ["Upload templates"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Define Demand",
        businessQuestion: "How do you define resource and material demands for projects?",
        thinkAbout: "Think about: do you plan what resources and materials each project needs in advance?",
        modules: ["PS"],
        configAreas: ["Demand management"],
        masterDataNeeded: ["WBS Element"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Release Projects",
        businessQuestion: "How do you authorize projects to start spending?",
        thinkAbout: "Think about: is there a formal release process before project costs can be incurred? Can you release parts of a project?",
        modules: ["PS"],
        configAreas: ["Status management", "Release procedures"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Direct Activity Allocation",
        businessQuestion: "Do you allocate internal activities (labor hours) directly to projects?",
        thinkAbout: "Think about: do your employees charge their time to projects? How do you value internal labor on projects?",
        modules: ["PS", "CO"],
        configAreas: ["Activity types", "Price calculation"],
        masterDataNeeded: ["Cost Center"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "General Journal Entry",
        businessQuestion: "Do you post manual journal entries to projects?",
        thinkAbout: "Think about: are there project-related costs that need to be posted manually (e.g., accruals, adjustments)?",
        modules: ["PS", "FI-GL"],
        configAreas: ["Account assignment"],
        masterDataNeeded: ["G/L Account Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Time Recording",
        businessQuestion: "How do your employees record time spent on projects?",
        thinkAbout: "Think about: do you use timesheets? How do you track hours by project and work package?",
        modules: ["PS"],
        configAreas: ["Time recording profiles"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Project Control Procurement",
        businessQuestion: "How do you procure materials and services for projects?",
        thinkAbout: "Think about: do project managers create purchase requisitions? How are procurement costs tracked against the project budget?",
        modules: ["PS", "MM-PUR"],
        configAreas: ["Account assignment to WBS"],
        masterDataNeeded: ["WBS Element"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Monitor Projects",
        businessQuestion: "How do you monitor project progress and financials?",
        thinkAbout: "Think about: what KPIs do you track? Budget vs. actual? Earned value? Completion percentage?",
        modules: ["PS", "CO"],
        configAreas: ["Monitoring views", "Report variants"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Financial Controller",
        businessQuestion: "Do project financial controllers need a dedicated overview?",
        thinkAbout: "Think about: does your finance team need a specific dashboard for project financial health?",
        modules: ["PS", "CO"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Cost Report",
        businessQuestion: "Do you need project cost reports?",
        thinkAbout: "Think about: what cost breakdowns do you need (by WBS, cost element, period)?",
        modules: ["PS", "CO"],
        configAreas: ["Report layout"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Budget Report",
        businessQuestion: "Do you need project budget reports?",
        thinkAbout: "Think about: do you compare budget vs. actual vs. committed costs?",
        modules: ["PS", "CO"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Manage Project Procurement",
        businessQuestion: "Do you need to track procurement activities within projects?",
        thinkAbout: "Think about: do project managers need visibility into PO status and delivery dates for their projects?",
        modules: ["PS", "MM-PUR"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "P&L Plan",
        businessQuestion: "Do you track project P&L (revenue and cost) against plan?",
        thinkAbout: "Think about: do your projects generate revenue? Do you compare planned vs. actual P&L?",
        modules: ["PS", "CO"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Settlement Rule",
        businessQuestion: "How do you settle project costs to final receivers?",
        thinkAbout: "Think about: where do project costs end up? Cost centers, fixed assets, profitability segments?",
        modules: ["PS", "CO"],
        configAreas: ["Settlement profiles", "Settlement receivers"],
        masterDataNeeded: ["Cost Center", "G/L Account Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Period End Closing",
        businessQuestion: "What period-end activities do you perform for projects?",
        thinkAbout: "Think about: do you run overhead calculations, settlements, and reconciliation at month-end?",
        modules: ["PS", "CO", "FI-GL"],
        configAreas: ["Overhead rates", "Settlement rules", "Closing schedule"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Apply Overhead",
        businessQuestion: "Do you apply overhead costs to projects?",
        thinkAbout: "Think about: do you add a percentage for general overhead (facilities, admin) to project costs?",
        modules: ["PS", "CO"],
        configAreas: ["Overhead rates", "Costing sheets"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Run Settlements",
        businessQuestion: "How do you execute project settlements?",
        thinkAbout: "Think about: do you settle project costs monthly to fixed assets, cost centers, or other receivers?",
        modules: ["PS", "CO"],
        configAreas: ["Settlement profiles"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Monitor Financials",
        businessQuestion: "How do you review project financials after period-end closing?",
        thinkAbout: "Think about: what financial reconciliation do you perform after project settlements?",
        modules: ["PS", "CO"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Complete Project",
        businessQuestion: "How do you formally complete project phases or entire projects?",
        thinkAbout: "Think about: what happens when a project is finished? Do you have a formal sign-off process?",
        modules: ["PS"],
        configAreas: ["Status management"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Close Project",
        businessQuestion: "How do you close projects and prevent further postings?",
        thinkAbout: "Think about: after final settlement, how do you lock projects against further cost postings?",
        modules: ["PS"],
        configAreas: ["Closing procedures"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
    ],
    defaultImplications: {
      fitDescription: "SAP standard project control will be configured as-is. Your project managers will follow SAP best practice workflows for project creation, budgeting, cost tracking, and settlement.",
      configureDescription: "Your project control process will use SAP standard with configuration adjustments. This typically involves modifying budget profiles, settlement rules, overhead rates, or approval workflows.",
      gapDescription: "Your project control process differs significantly from SAP standard. This will require a gap resolution workshop to determine the best approach.",
      naDescription: "This project control capability is not needed for your organization.",
      naImpact: "Excluding project control may affect your ability to track project costs, manage budgets, and perform project settlements within SAP.",
    },
  },

  // =====================================================================
  // BDW — Returnables Processing
  // =====================================================================
  BDW: {
    id: "BDW",
    businessName: "Returnables Processing",
    businessDescription:
      "Manage returnable transport packaging (pallets, containers) including tracking, sales, returns, and stock management.",
    modules: [
      { code: "SD-SLS", name: "Sales" },
      { code: "SD-DLV", name: "Shipping & Delivery" },
      { code: "SD-BIL", name: "Billing" },
      { code: "MM-IM", name: "Inventory Management" },
      { code: "FI-AR", name: "Accounts Receivable" },
    ],
    masterData: [
      { objectName: "Material Master", description: "Returnable packaging materials with special item categories" },
      { objectName: "Customer Master", sapCode: "BND", description: "Customers with returnable packaging agreements" },
    ],
    dependencies: [
      { scopeItemId: "BKP", name: "Sales Order Processing", reason: "Standard sales order processing for returnable shipments", type: "required" },
      { scopeItemId: "J59", name: "Accounts Receivable", reason: "Billing and payment processing for returnables", type: "required" },
    ],
    activityMetadata: [
      {
        activityTitlePattern: "Additional Information",
        businessQuestion: "Does your implementation team need to configure returnables processing settings?",
        thinkAbout: "Think about: these are technical setup activities for returnable packaging management.",
        modules: ["SD-SLS"],
        configAreas: ["Returnable item categories", "Scheduling"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Test Procedures",
        businessQuestion: "Does your team need to validate the returnables process through testing?",
        thinkAbout: "Think about: this is SAP test documentation used during user acceptance testing.",
        modules: ["SD-SLS"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Display Pallets Stock",
        businessQuestion: "Do you need to track the stock of returnable packaging?",
        thinkAbout: "Think about: how do you currently track how many pallets, crates, or containers you have in stock vs. with customers?",
        modules: ["MM-IM"],
        configAreas: [],
        masterDataNeeded: ["Material Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Create Sales Order",
        businessQuestion: "How do you process sales orders that include returnable packaging?",
        thinkAbout: "Think about: when you ship goods on pallets, how do you track which pallets went to which customer?",
        modules: ["SD-SLS"],
        configAreas: ["Order types", "Item categories for returnables"],
        masterDataNeeded: ["Customer Master", "Material Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Create Attachment",
        businessQuestion: "Do you attach documents to sales, delivery, or billing records?",
        thinkAbout: "Think about: do you need to attach contracts, photos, or other documents to your sales transactions?",
        modules: ["SD-SLS"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Create Delivery",
        businessQuestion: "How do you create delivery documents for shipments?",
        thinkAbout: "Think about: is delivery creation automatic from the sales order or manual? How do you handle partial deliveries?",
        modules: ["SD-DLV"],
        configAreas: ["Delivery types", "Shipping points"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Add Delivery Item for Pallet",
        businessQuestion: "Do you add returnable packaging as a separate line item on deliveries?",
        thinkAbout: "Think about: when shipping, do you explicitly add the pallet or container as a delivery line item?",
        modules: ["SD-DLV"],
        configAreas: ["Item categories"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Execute Picking",
        businessQuestion: "How do you pick goods and returnable packaging for shipment?",
        thinkAbout: "Think about: does your warehouse pick pallets as part of the order fulfillment process?",
        modules: ["SD-DLV"],
        configAreas: ["Picking rules"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Check Batches",
        businessQuestion: "Do you use batch management for returnable packaging?",
        thinkAbout: "Think about: do you track individual batches or lots of packaging materials?",
        modules: ["MM-IM"],
        configAreas: ["Batch management"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Post Goods Issue",
        businessQuestion: "How do you record goods leaving your warehouse?",
        thinkAbout: "Think about: when pallets ship out, how is your inventory updated? Automatically from the delivery?",
        modules: ["MM-IM"],
        configAreas: ["Movement types"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Create Billing",
        businessQuestion: "How do you bill customers for returnable packaging?",
        thinkAbout: "Think about: do you charge customers for pallets? Is it a deposit that gets refunded on return?",
        modules: ["SD-BIL"],
        configAreas: ["Billing types", "Pricing conditions"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Post Incoming Payment",
        businessQuestion: "How do you process incoming payments for returnables?",
        thinkAbout: "Think about: how do customers pay for returnable packaging deposits?",
        modules: ["FI-AR"],
        configAreas: ["Payment methods"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Outbound Delivery without Order",
        businessQuestion: "Do you ship returnable packaging without a formal sales order?",
        thinkAbout: "Think about: are there situations where you ship pallets directly without going through the order process?",
        modules: ["SD-DLV"],
        configAreas: ["Delivery types"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Pallets Return",
        businessQuestion: "How do you process the return of packaging from customers?",
        thinkAbout: "Think about: how do customers return pallets? Do you create a return order? Who initiates the return process?",
        modules: ["SD-SLS", "MM-IM"],
        configAreas: ["Return order types", "Return movement types"],
        masterDataNeeded: ["Customer Master", "Material Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Post Goods Receipt",
        businessQuestion: "How do you record returned packaging arriving at your warehouse?",
        thinkAbout: "Think about: when pallets come back, how do you update inventory? Do you inspect returned packaging?",
        modules: ["MM-IM"],
        configAreas: ["Movement types"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Return Process for Returnable",
        businessQuestion: "Do you use an alternative return process for returnable materials?",
        thinkAbout: "Think about: do you have a second variant for handling returns (e.g., direct return without a return order)?",
        modules: ["SD-SLS", "MM-IM"],
        configAreas: ["Alternative return handling"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Pallets Issue Order",
        businessQuestion: "Do you issue returnable packaging through a separate issue process?",
        thinkAbout: "Think about: do you manage pallet issuance separately from the main sales process?",
        modules: ["SD-SLS"],
        configAreas: ["Issue order types"],
        masterDataNeeded: ["Material Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Job Scheduling",
        businessQuestion: "Do you need automated scheduling for delivery, billing, and goods issue?",
        thinkAbout: "Think about: should these processes run automatically on a schedule rather than being triggered manually?",
        modules: ["SD-DLV", "SD-BIL"],
        configAreas: ["Background jobs", "Scheduling parameters"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
    ],
    defaultImplications: {
      fitDescription: "SAP standard returnables processing will be configured as-is. Your team will follow SAP best practice workflows for tracking, shipping, and returning packaging materials.",
      configureDescription: "Your returnables process will use SAP standard with configuration adjustments. This typically involves modifying item categories, pricing, or return handling rules.",
      gapDescription: "Your returnables process differs significantly from SAP standard. This will require a gap resolution workshop to determine the best approach.",
      naDescription: "This returnables processing capability is not needed for your organization.",
      naImpact: "Excluding returnables may affect your ability to track packaging inventory, bill customers for deposits, and manage the return cycle within SAP.",
    },
  },

  // =====================================================================
  // 2ET — Sales Order Processing for Non-Stock Material
  // =====================================================================
  "2ET": {
    id: "2ET",
    businessName: "Non-Stock Sales Orders",
    businessDescription:
      "Process sales orders for non-stock materials including quotations, contracts, delivery, billing, and proof of delivery.",
    modules: [
      { code: "SD-SLS", name: "Sales" },
      { code: "SD-DLV", name: "Shipping & Delivery" },
      { code: "SD-BIL", name: "Billing" },
      { code: "FI-AR", name: "Accounts Receivable" },
      { code: "MM-IM", name: "Inventory Management" },
    ],
    masterData: [
      { objectName: "Material Master", description: "Non-stock materials (services, consumables) without inventory tracking" },
      { objectName: "Customer Master", sapCode: "BND", description: "Customers with sales area and billing data" },
      { objectName: "Pricing Conditions", description: "Price lists and discount conditions" },
    ],
    dependencies: [
      { scopeItemId: "J59", name: "Accounts Receivable", reason: "Customer invoicing and payment collection", type: "required" },
      { scopeItemId: "J58", name: "Accounting & Financial Close", reason: "Revenue recognition and period-end closing", type: "required" },
      { scopeItemId: "BD6", name: "Basic Credit Management", reason: "Credit limit checks on sales orders", type: "optional" },
    ],
    activityMetadata: [
      {
        activityTitlePattern: "Additional Information",
        businessQuestion: "Does your implementation team need to configure sales order settings for non-stock materials?",
        thinkAbout: "Think about: these are technical setup activities such as proof of delivery settings.",
        modules: ["SD-SLS"],
        configAreas: ["POD relevance", "Delivery item categories"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Preliminary Steps",
        businessQuestion: "Does your implementation team need to configure preliminary settings?",
        thinkAbout: "Think about: these include proof-of-delivery relevance settings and business partner master data configuration.",
        modules: ["SD-SLS"],
        configAreas: ["POD configuration", "BP master data"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Test Procedures",
        businessQuestion: "Does your team need to validate the non-stock sales order process through testing?",
        thinkAbout: "Think about: this is SAP test documentation used during user acceptance testing.",
        modules: ["SD-SLS"],
        configAreas: [],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Credit",
        businessQuestion: "Do you check customer credit limits before accepting sales orders?",
        thinkAbout: "Think about: do you set credit limits per customer? What happens when a customer exceeds their limit?",
        modules: ["SD-SLS", "FI-AR"],
        configAreas: ["Credit management", "Credit limits", "Block rules"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Sales Quotation",
        businessQuestion: "Do you create formal quotations for customers before they place orders?",
        thinkAbout: "Think about: do customers request quotes? How long are quotes valid? Can customers accept partial quotes?",
        modules: ["SD-SLS"],
        configAreas: ["Quotation types", "Validity periods", "Pricing"],
        masterDataNeeded: ["Customer Master", "Material Master", "Pricing Conditions"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Sales Contract",
        businessQuestion: "Do you use long-term sales contracts or agreements with customers?",
        thinkAbout: "Think about: do you have framework agreements, blanket orders, or scheduled agreements with customers?",
        modules: ["SD-SLS"],
        configAreas: ["Contract types", "Release orders"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Create Sales Order",
        businessQuestion: "How do customer orders for non-stock items enter your system?",
        thinkAbout: "Think about: how do orders arrive (phone, email, web portal, EDI)? What information is captured on each order?",
        modules: ["SD-SLS"],
        configAreas: ["Order types", "Item categories", "Pricing", "Partner determination"],
        masterDataNeeded: ["Customer Master", "Material Master", "Pricing Conditions"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Sales Order Approval",
        businessQuestion: "Do sales orders require approval before processing?",
        thinkAbout: "Think about: do certain orders (large value, new customers, special terms) need manager approval?",
        modules: ["SD-SLS"],
        configAreas: ["Approval workflow", "Threshold rules"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Blocked Sales Orders",
        businessQuestion: "How do you handle sales orders blocked by credit checks?",
        thinkAbout: "Think about: who reviews and releases credit-blocked orders? What's the escalation process?",
        modules: ["SD-SLS", "FI-AR"],
        configAreas: ["Block reasons", "Release procedures"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Create Delivery",
        businessQuestion: "How do you create delivery documents for non-stock items?",
        thinkAbout: "Think about: is delivery creation automatic from the sales order? How do you handle partial deliveries?",
        modules: ["SD-DLV"],
        configAreas: ["Delivery types", "Shipping points", "Route determination"],
        masterDataNeeded: [],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Split Outbound Delivery",
        businessQuestion: "Do you split deliveries across multiple shipments?",
        thinkAbout: "Think about: do you sometimes ship an order in multiple packages or from different locations?",
        modules: ["SD-DLV"],
        configAreas: ["Delivery split criteria"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Freight Cost",
        businessQuestion: "Do you add freight charges to deliveries?",
        thinkAbout: "Think about: how do you calculate and charge shipping costs? Do you pass freight to the customer or absorb it?",
        modules: ["SD-DLV"],
        configAreas: ["Freight condition types", "Freight determination"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Post Goods Issue",
        businessQuestion: "How do you record goods leaving your location for non-stock items?",
        thinkAbout: "Think about: for non-stock items, goods issue typically triggers revenue recognition. Is this your process?",
        modules: ["SD-DLV", "MM-IM"],
        configAreas: ["Goods issue posting"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Proof of Delivery",
        businessQuestion: "Do you use proof of delivery confirmation?",
        thinkAbout: "Think about: do your customers or drivers confirm delivery receipt? Do you need electronic proof of delivery?",
        modules: ["SD-DLV"],
        configAreas: ["POD configuration", "POD relevance"],
        masterDataNeeded: [],
        effortCategory: "low",
      },
      {
        activityTitlePattern: "Create Billing Document",
        businessQuestion: "How do you create customer invoices for non-stock items?",
        thinkAbout: "Think about: is billing triggered automatically after delivery? Do you combine multiple deliveries into one invoice?",
        modules: ["SD-BIL"],
        configAreas: ["Billing types", "Billing schedules", "Output determination"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "medium",
      },
      {
        activityTitlePattern: "Pro Forma Invoice",
        businessQuestion: "Do you issue pro forma invoices before actual billing?",
        thinkAbout: "Think about: do customers need a pro forma invoice for customs, banking, or pre-payment purposes?",
        modules: ["SD-BIL"],
        configAreas: ["Pro forma billing types"],
        masterDataNeeded: ["Customer Master"],
        effortCategory: "low",
      },
    ],
    defaultImplications: {
      fitDescription: "SAP standard non-stock sales order processing will be configured as-is. Your sales team will follow SAP best practice workflows for quotations, orders, delivery, and billing.",
      configureDescription: "Your sales process will use SAP standard with configuration adjustments. This typically involves modifying order types, pricing schemes, approval workflows, or output formats.",
      gapDescription: "Your sales process differs significantly from SAP standard. This will require a gap resolution workshop to determine the best approach.",
      naDescription: "This non-stock sales order capability is not needed for your organization.",
      naImpact: "Excluding non-stock sales processing may affect your ability to sell services, consumables, or other non-inventory items through SAP.",
    },
  },
};

// --- Helper Functions ---

/** Get metadata for a scope item, or null if not curated. */
export function getScopeItemMetadata(scopeItemId: string): ScopeItemMetadata | null {
  return SCOPE_ITEM_METADATA[scopeItemId] ?? null;
}

/** Get activity metadata matching an activity title within a scope item. */
export function getActivityMetadata(
  scopeItemId: string,
  activityTitle: string,
): ActivityMetadata | null {
  const scopeMeta = SCOPE_ITEM_METADATA[scopeItemId];
  if (!scopeMeta) return null;

  // Try exact substring match first, then increasingly fuzzy
  for (const am of scopeMeta.activityMetadata) {
    if (activityTitle.includes(am.activityTitlePattern)) {
      return am;
    }
  }

  // Try case-insensitive match
  const lowerTitle = activityTitle.toLowerCase();
  for (const am of scopeMeta.activityMetadata) {
    if (lowerTitle.includes(am.activityTitlePattern.toLowerCase())) {
      return am;
    }
  }

  return null;
}

/** Get all modules for a scope item. */
export function getModulesForScopeItem(scopeItemId: string): ScopeItemModuleInfo[] {
  return SCOPE_ITEM_METADATA[scopeItemId]?.modules ?? [];
}

/** Get all dependencies for a scope item. */
export function getDependenciesForScopeItem(scopeItemId: string): ScopeItemDependency[] {
  return SCOPE_ITEM_METADATA[scopeItemId]?.dependencies ?? [];
}
