/** All user-facing strings — never hardcode text in JSX */

import { APP_CONFIG } from "@/constants/config";

export const UI_TEXT = {
  app: {
    name: "Aptus",
    tagline: "SAP Business Process Assessment",
    // Phase 11 — AD-3: read from APP_CONFIG so the version label can never
    // drift from the canonical sapVersion. Previously hardcoded "2508"
    // (already 4 minor releases stale at the time of fix).
    sapVersion: `SAP Best Practices ${APP_CONFIG.sapVersion}`,
  },
  auth: {
    loginTitle: "Sign in",
    loginSubtitle: "Enter your email to receive a sign-in link",
    emailPlaceholder: "you@company.com",
    sendMagicLink: "Continue",
    magicLinkSent: "Check your email",
    magicLinkDescription: "We sent a sign-in link to your email. Click the link to continue.",
    mfaSetupTitle: "Set Up Two-Factor Authentication",
    mfaSetupDescription: "Scan the QR code with your authenticator app, then enter the 6-digit code to verify.",
    mfaVerifyTitle: "Two-Factor Authentication",
    mfaVerifyDescription: "Enter the 6-digit code from your authenticator app.",
    mfaCodePlaceholder: "000000",
    mfaVerifyButton: "Verify",
    mfaSetupButton: "Verify & Enable",
    mfaManualEntry: "Can't scan? Enter this code manually:",
    signOut: "Sign Out",
    sessionExpired: "Your session has expired. Please sign in again.",
    sessionRevoked: "You were signed out because another session was started.",
  },
  assessment: {
    listTitle: "Assessments",
    createNew: "New Assessment",
    noAssessments: "No assessments yet",
    noAssessmentsDescription: "Create your first assessment to compare your business processes with SAP.",
    companyName: "Company Name",
    industry: "Industry",
    country: "Primary Country",
    operatingCountries: "Operating Countries",
    companySize: "Company Size",
    revenueBand: "Revenue Band",
    currentErp: "Current ERP System",
    createButton: "Create Assessment",
  },
  stakeholder: {
    title: "Team Members",
    addButton: "Add Team Member",
    name: "Full Name",
    email: "Email Address",
    role: "Role",
    assignedAreas: "Assigned Functional Areas",
    inviteButton: "Send Invitation",
    removeButton: "Remove",
    pendingInvitation: "Invitation pending",
    accepted: "Active",
  },
  status: {
    draft: "Draft",
    in_progress: "In Progress",
    completed: "Completed",
    reviewed: "Reviewed",
    signed_off: "Signed Off",
  },
  fitStatus: {
    FIT: "Matches",
    CONFIGURE: "Needs Adjustment",
    GAP: "Doesn\u2019t Match",
    NA: "Not Relevant",
    PENDING: "Pending",
  },
  roles: {
    process_owner: "Process Owner",
    it_lead: "IT Lead",
    executive: "Executive",
    consultant: "Consultant",
    admin: "Administrator",
  },
  errors: {
    unauthorized: "You must be signed in to access this page.",
    forbidden: "You don't have permission to access this resource.",
    notFound: "The requested resource was not found.",
    areaLocked: "You don't have permission to edit this area.",
    mfaRequired: "Two-factor authentication is required.",
    generic: "Something went wrong. Please try again.",
  },
  scope: {
    title: "Select Your Scope",
    description: "Choose which SAP business processes are relevant to your organization.",
    industryPreSelected: "We've pre-selected items common for {industry} companies. Review and adjust.",
    selectedCount: "{count} scope items selected",
    stepsToReview: "{count} process steps to review",
    searchPlaceholder: "Search scope items...",
    filterAll: "All",
    filterSelected: "Selected",
    filterNotSelected: "Not Selected",
    filterMaybe: "Maybe",
    selectAllInArea: "Select All",
    deselectAllInArea: "Deselect All",
    backButton: "← Company Profile",
    continueButton: "Continue to Process Review →",
    noResults: "No scope items match your filters",
    noResultsDescription: "Try adjusting your search or filter criteria.",
    areaSelected: "{selected} / {total} selected",
    viewLandscape: "Process Map",
    viewList: "List View",
    selectChain: "Select entire chain",
    clearChain: "Clear chain",
    otherItems: "Other Scope Items",
    chainSelected: "{selected}/{total} selected",
    briefingBack: "Back to Scope Selection",
    briefingStartReview: "Start Detailed Review",
    briefingWhatCovers: "What This Covers",
    briefingHowStructured: "How the Review Is Structured",
    briefingQuestions: "Questions to Discuss Before Starting",
  },
  nav: {
    assessments: "Assessments",
    dashboard: "Dashboard",
    templates: "Templates",
    analytics: "Analytics",
    organization: "Organization",
    admin: "Admin",
    intelligence: "Intelligence",
  },
} as const;
