/** GET: Remaining Items Register XLSX */

import { NextResponse, type NextRequest } from "next/server";
import { authenticateForReport, isErrorResponse } from "@/lib/report/report-auth";
import { prisma } from "@/lib/db/prisma";
import { generateXlsx, remainingItemsSheet } from "@/lib/report/xlsx-generator";

export const preferredRegion = "sin1";
export const maxDuration = 30;

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
): Promise<NextResponse> {
  const { id: assessmentId } = await params;
  const auth = await authenticateForReport(assessmentId, false);
  if (isErrorResponse(auth)) return auth;

  const items = await prisma.remainingItem.findMany({
    where: { assessmentId },
    orderBy: [{ severity: "asc" }, { category: "asc" }],
  });

  const data = items.map((item, i) => ({
    itemNumber: i + 1,
    category: item.category,
    title: item.title,
    description: item.description,
    severity: item.severity,
    sourceEntity: item.sourceEntityType ? `${item.sourceEntityType}:${item.sourceEntityId}` : "",
    scopeItemId: item.scopeItemId ?? "",
    functionalArea: item.functionalArea ?? "",
    assignedTo: item.assignedTo ?? "",
    resolution: item.resolution ?? "",
    resolvedAt: item.resolvedAt?.toISOString() ?? "",
    resolvedBy: item.resolvedBy ?? "",
    autoGenerated: item.autoGenerated ? "Yes" : "No",
  }));

  const xlsx = await generateXlsx([remainingItemsSheet(data)]);

  return new NextResponse(xlsx as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${auth.assessment.companyName}_Remaining_Items_Register.xlsx"`,
    },
  });
}
