/**
 * SEED-008: Active org, Phase 1 signed + Phase 2 in progress
 * Purpose: Test parent-child assessment relationship and carry-forward configuration
 */
export function seedPhase2() {
  const orgId = "seed-org-008";
  const phase1Id = "seed-assessment-008-p1";
  const phase2Id = "seed-assessment-008-p2";
  const snapshotId = "seed-snapshot-008-p1";
  const signOffId = "seed-signoff-008-p1";

  const commonFields = {
    companyName: "Zenith Electronics",
    industry: "Electronics",
    country: "MY",
    operatingCountries: ["MY", "SG", "TH", "PH"],
    companySize: "LARGE",
    revenueBand: "$500M-$1B",
    currentErp: "SAP ECC 6.0",
    sapVersion: "2508",
    organizationId: orgId,
    employeeCount: 4200,
    annualRevenue: 680000000,
    currencyCode: "USD",
    deploymentModel: "cloud" as const,
    languageRequirements: ["EN", "MS", "TH"],
    regulatoryFrameworks: ["SOX", "SST"],
    itLandscapeSummary: "Multi-site SAP ECC with MES and PLM integrations",
    currentErpVersion: "EHP8",
    migrationApproach: "brownfield" as const,
  };

  return {
    organization: {
      id: orgId,
      name: "Continuum Consulting",
      slug: "continuum-consulting",
      type: "partner",
      orgType: "partner",
      plan: "PROFESSIONAL",
      subscriptionStatus: "ACTIVE",
      trialEndsAt: null,
      maxActiveAssessments: 10,
      maxPartnerUsers: 25,
      isActive: true,
    },
    users: [
      {
        id: "seed-user-008a",
        email: "lead@continuumconsulting.com",
        name: "Jessica Teo",
        role: "partner_lead",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-008b",
        email: "consultant@continuumconsulting.com",
        name: "Marcus Lim",
        role: "consultant",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-008c",
        email: "architect@continuumconsulting.com",
        name: "Anita Desai",
        role: "solution_architect",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-008d",
        email: "exec@zenith.com",
        name: "Tan Ah Kow",
        role: "executive_sponsor",
        organizationId: orgId,
        isActive: true,
      },
    ],
    assessments: [
      {
        id: phase1Id,
        ...commonFields,
        status: "signed_off",
        createdBy: "seed-user-008b",
        targetGoLiveDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        sapModules: ["FI", "CO", "MM", "SD"],
        keyProcesses: ["Order-to-Cash", "Procure-to-Pay", "Record-to-Report"],
        profileCompletedAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-008b",
        phaseNumber: 1,
        currentSnapshotId: snapshotId,
        parentAssessmentId: null,
      },
      {
        id: phase2Id,
        ...commonFields,
        companyName: "Zenith Electronics - Phase 2",
        status: "process_review",
        createdBy: "seed-user-008b",
        targetGoLiveDate: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000),
        sapModules: ["PP", "QM", "PM", "EWM"],
        keyProcesses: ["Plan-to-Produce", "Quality-to-Compliance", "Maintain-to-Operate"],
        profileCompletedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-008b",
        phaseNumber: 2,
        parentAssessmentId: phase1Id,
        clonedFromSnapshotId: snapshotId,
        carryForwardConfig: {
          includeScope: true,
          includeClassifications: true,
          includeGaps: true,
          includeIntegrations: false,
          includeDataMigration: false,
          includeOcm: false,
          carryForwardDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
          sourcePhase: 1,
          targetPhase: 2,
          scopeItemsCarried: 35,
          scopeItemsNew: 20,
          gapsCarriedForward: 5,
          notes: "Phase 2 focuses on manufacturing, quality, and warehouse modules. Finance and procurement scope carried forward for reference.",
        },
      },
    ],
    snapshots: [
      {
        id: snapshotId,
        assessmentId: phase1Id,
        version: 1,
        label: "Phase 1 Final",
        snapshotData: {
          scopeSelections: 35,
          stepResponses: 175,
          gapResolutions: 18,
          integrationPoints: 5,
          dataMigrationObjects: 8,
          fitRate: 0.48,
          configureRate: 0.27,
          gapRate: 0.12,
          naRate: 0.08,
          pendingRate: 0.05,
        },
        dataHash: "sha256:d4e5f6a7b8c9012345678abcdef0123456789abcdef0123456789abcdef04",
        createdById: "seed-user-008b",
        reason: "Phase 1 completed - snapshot for Phase 2 carry-forward",
      },
    ],
    signOffProcesses: [
      {
        id: signOffId,
        assessmentId: phase1Id,
        snapshotId,
        status: "COMPLETED",
        initiatedById: "seed-user-008b",
        completedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        certificatePdfUrl: "/certificates/seed-assessment-008-p1.pdf",
        certificateHash: "sha256:cert_d4e5f6a7b8c9012345678",
        verificationToken: "verify-seed-008-p1-token",
      },
    ],
    phaseProgress: [
      {
        id: "seed-progress-008-p2-scoping",
        assessmentId: phase2Id,
        phase: "scoping",
        status: "completed",
        completionPct: 100,
        startedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        completedBy: "seed-user-008b",
      },
      {
        id: "seed-progress-008-p2-process",
        assessmentId: phase2Id,
        phase: "process_review",
        status: "in_progress",
        completionPct: 35,
        startedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed-progress-008-p2-gap",
        assessmentId: phase2Id,
        phase: "gap_resolution",
        status: "not_started",
        completionPct: 0,
      },
    ],
  };
}
