/**
 * SEED-007: Active org, 1 SIGNED_OFF assessment + 1 HANDED_OFF
 * Purpose: Test post-sign-off state including snapshots, signatures, and certificate data
 */
export function seedSignedOff() {
  const orgId = "seed-org-007";
  const signedAssessmentId = "seed-assessment-007a";
  const handedOffAssessmentId = "seed-assessment-007b";
  const signOffIdA = "seed-signoff-007a";
  const signOffIdB = "seed-signoff-007b";
  const snapshotIdA = "seed-snapshot-007a";
  const snapshotIdB = "seed-snapshot-007b";

  const commonAssessmentFields = {
    industry: "Manufacturing",
    country: "MY",
    operatingCountries: ["MY", "SG"],
    companySize: "LARGE",
    revenueBand: "$500M-$1B",
    currentErp: "SAP ECC 6.0",
    sapVersion: "2508",
    organizationId: orgId,
    employeeCount: 5000,
    annualRevenue: 750000000,
    currencyCode: "USD",
    deploymentModel: "cloud" as const,
    sapModules: ["FI", "CO", "MM", "SD", "PP"],
    keyProcesses: ["Order-to-Cash", "Procure-to-Pay", "Record-to-Report"],
    languageRequirements: ["EN", "MS"],
    regulatoryFrameworks: ["SOX", "SST"],
    itLandscapeSummary: "SAP ECC with third-party integrations",
    currentErpVersion: "EHP8",
    migrationApproach: "brownfield" as const,
    phaseNumber: 1,
  };

  return {
    organization: {
      id: orgId,
      name: "Milestone Advisory",
      slug: "milestone-advisory",
      type: "partner",
      orgType: "partner",
      plan: "PROFESSIONAL",
      subscriptionStatus: "ACTIVE",
      trialEndsAt: null,
      stripeCustomerId: "cus_seed_007",
      stripeSubscriptionId: "sub_seed_007",
      billingEmail: "billing@milestoneadvisory.com",
      maxActiveAssessments: 10,
      maxPartnerUsers: 25,
      isActive: true,
    },
    users: [
      {
        id: "seed-user-007a",
        email: "lead@milestoneadvisory.com",
        name: "Amanda Chia",
        role: "partner_lead",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-007b",
        email: "consultant@milestoneadvisory.com",
        name: "Kevin Loh",
        role: "consultant",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-007c",
        email: "exec@techglobal.com",
        name: "Datuk Ismail",
        role: "executive_sponsor",
        organizationId: orgId,
        isActive: true,
      },
    ],
    assessments: [
      {
        id: signedAssessmentId,
        companyName: "TechGlobal Industries",
        ...commonAssessmentFields,
        status: "signed_off",
        createdBy: "seed-user-007b",
        targetGoLiveDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
        profileCompletedAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-007b",
        currentSnapshotId: snapshotIdA,
      },
      {
        id: handedOffAssessmentId,
        companyName: "TechGlobal Industries - Phase 1B",
        ...commonAssessmentFields,
        status: "handed_off",
        createdBy: "seed-user-007b",
        targetGoLiveDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        profileCompletedAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-007b",
        currentSnapshotId: snapshotIdB,
      },
    ],
    snapshots: [
      {
        id: snapshotIdA,
        assessmentId: signedAssessmentId,
        version: 1,
        label: "Final Sign-Off Snapshot",
        snapshotData: {
          scopeSelections: 35,
          stepResponses: 180,
          gapResolutions: 20,
          integrationPoints: 6,
          dataMigrationObjects: 10,
          fitRate: 0.45,
          configureRate: 0.30,
          gapRate: 0.12,
          naRate: 0.08,
          pendingRate: 0.05,
        },
        dataHash: "sha256:b2c3d4e5f6a789012345678abcdef0123456789abcdef0123456789abcdef02",
        createdById: "seed-user-007b",
        reason: "Final snapshot for executive sign-off",
      },
      {
        id: snapshotIdB,
        assessmentId: handedOffAssessmentId,
        version: 1,
        label: "Handoff Snapshot",
        snapshotData: {
          scopeSelections: 28,
          stepResponses: 140,
          gapResolutions: 15,
          integrationPoints: 4,
          dataMigrationObjects: 8,
          fitRate: 0.50,
          configureRate: 0.28,
          gapRate: 0.10,
          naRate: 0.07,
          pendingRate: 0.05,
        },
        dataHash: "sha256:c3d4e5f6a7b89012345678abcdef0123456789abcdef0123456789abcdef03",
        createdById: "seed-user-007b",
        reason: "Snapshot for implementation handoff",
      },
    ],
    signOffProcesses: [
      {
        id: signOffIdA,
        assessmentId: signedAssessmentId,
        snapshotId: snapshotIdA,
        status: "COMPLETED",
        initiatedById: "seed-user-007b",
        completedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        certificatePdfUrl: "/certificates/seed-assessment-007a.pdf",
        certificateHash: "sha256:cert_a1b2c3d4e5f6789012345678",
        verificationToken: "verify-seed-007a-token",
      },
      {
        id: signOffIdB,
        assessmentId: handedOffAssessmentId,
        snapshotId: snapshotIdB,
        status: "COMPLETED",
        initiatedById: "seed-user-007b",
        completedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        certificatePdfUrl: "/certificates/seed-assessment-007b.pdf",
        certificateHash: "sha256:cert_b2c3d4e5f6a789012345678",
        verificationToken: "verify-seed-007b-token",
      },
    ],
    signatureRecords: [
      {
        id: "seed-sig-007a-exec",
        signOffId: signOffIdA,
        signatureType: "EXECUTIVE",
        signerId: "seed-user-007c",
        signerName: "Datuk Ismail",
        signerEmail: "exec@techglobal.com",
        signerRole: "executive_sponsor",
        signerOrganization: "TechGlobal Industries",
        signerTitle: "Chief Operating Officer",
        authorityStatement: "I confirm that I have reviewed the assessment findings and authorize the sign-off on behalf of TechGlobal Industries.",
        ipAddress: "203.0.113.50",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        authMethod: "email_otp",
        mfaVerified: true,
        documentHash: "sha256:b2c3d4e5f6a789012345678abcdef0123456789abcdef0123456789abcdef02",
        signedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        status: "COMPLETED",
      },
      {
        id: "seed-sig-007a-partner",
        signOffId: signOffIdA,
        signatureType: "PARTNER",
        signerId: "seed-user-007a",
        signerName: "Amanda Chia",
        signerEmail: "lead@milestoneadvisory.com",
        signerRole: "partner_lead",
        signerOrganization: "Milestone Advisory",
        signerTitle: "Managing Partner",
        authorityStatement: "I confirm that this assessment has been conducted according to our methodology and the findings are accurate.",
        ipAddress: "203.0.113.100",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        authMethod: "totp",
        mfaVerified: true,
        documentHash: "sha256:b2c3d4e5f6a789012345678abcdef0123456789abcdef0123456789abcdef02",
        signedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        status: "COMPLETED",
      },
      {
        id: "seed-sig-007b-exec",
        signOffId: signOffIdB,
        signatureType: "EXECUTIVE",
        signerId: "seed-user-007c",
        signerName: "Datuk Ismail",
        signerEmail: "exec@techglobal.com",
        signerRole: "executive_sponsor",
        signerOrganization: "TechGlobal Industries",
        signerTitle: "Chief Operating Officer",
        authorityStatement: "I authorize the handoff of this assessment to the implementation team.",
        ipAddress: "203.0.113.50",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        authMethod: "email_otp",
        mfaVerified: true,
        documentHash: "sha256:c3d4e5f6a7b89012345678abcdef0123456789abcdef0123456789abcdef03",
        signedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        status: "COMPLETED",
      },
      {
        id: "seed-sig-007b-partner",
        signOffId: signOffIdB,
        signatureType: "PARTNER",
        signerId: "seed-user-007a",
        signerName: "Amanda Chia",
        signerEmail: "lead@milestoneadvisory.com",
        signerRole: "partner_lead",
        signerOrganization: "Milestone Advisory",
        signerTitle: "Managing Partner",
        authorityStatement: "I confirm the handoff package is complete and ready for implementation.",
        ipAddress: "203.0.113.100",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        authMethod: "totp",
        mfaVerified: true,
        documentHash: "sha256:c3d4e5f6a7b89012345678abcdef0123456789abcdef0123456789abcdef03",
        signedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        status: "COMPLETED",
      },
    ],
    handoffPackages: [
      {
        id: "seed-handoff-007",
        assessmentId: handedOffAssessmentId,
        snapshotVersion: 1,
        packageType: "FULL",
        contents: [
          "executive_summary",
          "scope_analysis",
          "fit_gap_report",
          "gap_resolutions",
          "integration_register",
          "data_migration_plan",
          "ocm_assessment",
          "risk_register",
          "effort_estimates",
          "process_flow_diagrams",
        ],
        fileSize: 15728640,
        blobUrl: "/handoff/seed-assessment-007b-full.zip",
        generatedById: "seed-user-007b",
      },
    ],
  };
}
