/**
 * SEED-011: Past due org, 14 days into grace period
 * Purpose: Test past-due subscription behavior, grace period enforcement, and payment prompts
 */
export function seedPastDue() {
  const orgId = "seed-org-011";

  return {
    organization: {
      id: orgId,
      name: "LatePay Consulting",
      slug: "latepay-consulting",
      type: "partner",
      orgType: "partner",
      plan: "PROFESSIONAL",
      subscriptionStatus: "PAST_DUE",
      trialEndsAt: null,
      stripeCustomerId: "cus_seed_011",
      stripeSubscriptionId: "sub_seed_011",
      billingEmail: "billing@latepayconsulting.com",
      maxActiveAssessments: 10,
      maxPartnerUsers: 25,
      isActive: true,
    },
    users: [
      {
        id: "seed-user-011a",
        email: "lead@latepayconsulting.com",
        name: "Ng Chee Keong",
        role: "partner_lead",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-011b",
        email: "consultant@latepayconsulting.com",
        name: "Shalini Devi",
        role: "consultant",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-011c",
        email: "pm@latepayconsulting.com",
        name: "Thomas Lee",
        role: "project_manager",
        organizationId: orgId,
        isActive: true,
      },
    ],
    assessments: [
      {
        id: "seed-assessment-011a",
        companyName: "Gamma Manufacturing",
        industry: "Manufacturing",
        country: "MY",
        operatingCountries: ["MY", "SG"],
        companySize: "MEDIUM",
        revenueBand: "$50M-$100M",
        currentErp: "SAP Business One",
        sapVersion: "2508",
        status: "process_review",
        createdBy: "seed-user-011b",
        organizationId: orgId,
        employeeCount: 500,
        annualRevenue: 75000000,
        currencyCode: "MYR",
        targetGoLiveDate: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000),
        deploymentModel: "cloud",
        sapModules: ["FI", "CO", "MM", "SD", "PP"],
        keyProcesses: ["Order-to-Cash", "Procure-to-Pay", "Plan-to-Produce"],
        languageRequirements: ["EN", "MS"],
        regulatoryFrameworks: ["SST", "MFRS"],
        itLandscapeSummary: "SAP Business One with custom extensions",
        currentErpVersion: "10.0",
        migrationApproach: "greenfield",
        profileCompletedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-011b",
        phaseNumber: 1,
      },
      {
        id: "seed-assessment-011b",
        companyName: "Delta Logistics",
        industry: "Logistics",
        country: "MY",
        operatingCountries: ["MY"],
        companySize: "SMALL",
        revenueBand: "$10M-$50M",
        currentErp: "None",
        sapVersion: "2508",
        status: "scope_locked",
        createdBy: "seed-user-011b",
        organizationId: orgId,
        employeeCount: 200,
        annualRevenue: 30000000,
        currencyCode: "MYR",
        targetGoLiveDate: new Date(Date.now() + 300 * 24 * 60 * 60 * 1000),
        deploymentModel: "cloud",
        sapModules: ["FI", "CO", "MM", "SD", "TM"],
        keyProcesses: ["Order-to-Cash", "Procure-to-Pay"],
        languageRequirements: ["EN", "MS"],
        regulatoryFrameworks: ["SST"],
        itLandscapeSummary: "Spreadsheet-based operations, greenfield implementation",
        migrationApproach: "greenfield",
        profileCompletedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-011b",
        phaseNumber: 1,
      },
      {
        id: "seed-assessment-011c",
        companyName: "Epsilon Trading",
        industry: "Trading",
        country: "SG",
        operatingCountries: ["SG", "MY", "HK"],
        companySize: "MEDIUM",
        revenueBand: "$100M-$500M",
        currentErp: "SAP ECC 6.0",
        sapVersion: "2508",
        status: "gap_resolution",
        createdBy: "seed-user-011b",
        organizationId: orgId,
        employeeCount: 600,
        annualRevenue: 200000000,
        currencyCode: "SGD",
        targetGoLiveDate: new Date(Date.now() + 200 * 24 * 60 * 60 * 1000),
        deploymentModel: "cloud",
        sapModules: ["FI", "CO", "MM", "SD"],
        keyProcesses: ["Order-to-Cash", "Procure-to-Pay", "Record-to-Report"],
        languageRequirements: ["EN", "ZH"],
        regulatoryFrameworks: ["SFRS", "SOX"],
        itLandscapeSummary: "SAP ECC with CRM and BI integrations",
        currentErpVersion: "EHP7",
        migrationApproach: "brownfield",
        profileCompletedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-011b",
        phaseNumber: 1,
      },
    ],
    usageEvents: [
      {
        id: "seed-usage-011a",
        organizationId: orgId,
        eventType: "assessment_created",
        entityId: "seed-assessment-011a",
        metadata: { plan: "PROFESSIONAL" },
        stripeSent: true,
        createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed-usage-011b",
        organizationId: orgId,
        eventType: "assessment_created",
        entityId: "seed-assessment-011b",
        metadata: { plan: "PROFESSIONAL" },
        stripeSent: true,
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed-usage-011c",
        organizationId: orgId,
        eventType: "assessment_created",
        entityId: "seed-assessment-011c",
        metadata: { plan: "PROFESSIONAL" },
        stripeSent: false,
        stripeError: "Payment method declined",
        createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
      },
    ],
  };
}
