/**
 * SEED-006: Active org, 1 assessment at PENDING_SIGN_OFF with all validation ready
 * Purpose: Test sign-off validation flow including area, technical, and cross-functional validation
 */
export function seedPendingSignOff() {
  const orgId = "seed-org-006";
  const assessmentId = "seed-assessment-006";
  const signOffId = "seed-signoff-006";
  const snapshotId = "seed-snapshot-006";

  const functionalAreas = ["Finance", "Procurement", "Sales", "Warehouse", "Quality"];

  const areaValidations = functionalAreas.map((area, i) => ({
    id: `seed-area-val-006-${String(i + 1).padStart(2, "0")}`,
    signOffId,
    functionalArea: area,
    validatedById: `seed-user-006${String.fromCharCode(99 + i)}`, // c, d, e, f, g
    validatorName: [
      "Ahmad Razak",
      "Siti Aminah",
      "Kumar Patel",
      "Lee Mei Ling",
      "Farid Hassan",
    ][i],
    validatorEmail: [
      "ahmad@acmeclient.com",
      "siti@acmeclient.com",
      "kumar@acmeclient.com",
      "mei.ling@acmeclient.com",
      "farid@acmeclient.com",
    ][i],
    validatorRole: "process_owner",
    status: i < 4 ? "APPROVED" : "PENDING",
    comments: i < 4 ? `${area} processes reviewed and validated` : null,
    rejectionReason: null,
    validatedAt: i < 4 ? new Date(Date.now() - (5 - i) * 24 * 60 * 60 * 1000) : null,
  }));

  return {
    organization: {
      id: orgId,
      name: "SignOff Consulting Group",
      slug: "signoff-consulting",
      type: "partner",
      orgType: "partner",
      plan: "PROFESSIONAL",
      subscriptionStatus: "ACTIVE",
      trialEndsAt: null,
      maxActiveAssessments: 10,
      maxPartnerUsers: 25,
      isActive: true,
    },
    users: [
      {
        id: "seed-user-006a",
        email: "lead@signoffconsulting.com",
        name: "Patricia Santos",
        role: "partner_lead",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006b",
        email: "consultant@signoffconsulting.com",
        name: "Daniel Ooi",
        role: "consultant",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006c",
        email: "ahmad@acmeclient.com",
        name: "Ahmad Razak",
        role: "process_owner",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006d",
        email: "siti@acmeclient.com",
        name: "Siti Aminah",
        role: "process_owner",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006e",
        email: "kumar@acmeclient.com",
        name: "Kumar Patel",
        role: "process_owner",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006f",
        email: "mei.ling@acmeclient.com",
        name: "Lee Mei Ling",
        role: "process_owner",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006g",
        email: "farid@acmeclient.com",
        name: "Farid Hassan",
        role: "process_owner",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006h",
        email: "it-lead@acmeclient.com",
        name: "Vincent Lee",
        role: "it_lead",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006i",
        email: "dm-lead@acmeclient.com",
        name: "Nadia Yusof",
        role: "data_migration_lead",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-006j",
        email: "exec@acmeclient.com",
        name: "Tan Sri Abdullah",
        role: "executive_sponsor",
        organizationId: orgId,
        isActive: true,
      },
    ],
    assessments: [
      {
        id: assessmentId,
        companyName: "Acme Manufacturing Corp",
        industry: "Manufacturing",
        country: "MY",
        operatingCountries: ["MY", "SG", "TH"],
        companySize: "LARGE",
        revenueBand: "$500M-$1B",
        currentErp: "SAP ECC 6.0",
        sapVersion: "2508",
        status: "pending_sign_off",
        createdBy: "seed-user-006b",
        organizationId: orgId,
        employeeCount: 5000,
        annualRevenue: 750000000,
        currencyCode: "USD",
        targetGoLiveDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        deploymentModel: "cloud",
        sapModules: ["FI", "CO", "MM", "SD", "PP", "QM", "WM"],
        keyProcesses: ["Order-to-Cash", "Procure-to-Pay", "Plan-to-Produce", "Record-to-Report"],
        languageRequirements: ["EN", "MS"],
        regulatoryFrameworks: ["SOX", "SST", "MFRS"],
        itLandscapeSummary: "Multi-site SAP ECC with WMS and CRM integrations",
        currentErpVersion: "EHP8",
        migrationApproach: "brownfield",
        profileCompletedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-006b",
        phaseNumber: 1,
        currentSnapshotId: snapshotId,
      },
    ],
    snapshots: [
      {
        id: snapshotId,
        assessmentId,
        version: 1,
        label: "Pre-Sign-Off Snapshot",
        snapshotData: {
          scopeSelections: 40,
          stepResponses: 200,
          gapResolutions: 25,
          integrationPoints: 8,
          dataMigrationObjects: 12,
          fitRate: 0.42,
          configureRate: 0.28,
          gapRate: 0.15,
          naRate: 0.08,
          pendingRate: 0.07,
        },
        dataHash: "sha256:a1b2c3d4e5f6789012345678abcdef0123456789abcdef0123456789abcdef01",
        createdById: "seed-user-006b",
        reason: "Snapshot created for sign-off validation",
      },
    ],
    signOffProcess: {
      id: signOffId,
      assessmentId,
      snapshotId,
      status: "VALIDATION_IN_PROGRESS",
      initiatedById: "seed-user-006b",
    },
    areaValidations,
    technicalValidation: {
      id: "seed-tech-val-006",
      signOffId,
      itLeadId: "seed-user-006h",
      itLeadName: "Vincent Lee",
      itLeadEmail: "it-lead@acmeclient.com",
      itLeadStatus: "APPROVED",
      itLeadComments: "Integration architecture reviewed. API specifications validated. No blockers identified.",
      itLeadAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      dmLeadId: "seed-user-006i",
      dmLeadName: "Nadia Yusof",
      dmLeadEmail: "dm-lead@acmeclient.com",
      dmLeadStatus: "APPROVED",
      dmLeadComments: "Data migration objects mapped and validated. Cleansing plan approved.",
      dmLeadAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    crossFunctionalValidation: {
      id: "seed-cross-val-006",
      signOffId,
      validatedById: "seed-user-006b",
      validatorName: "Daniel Ooi",
      validatorEmail: "consultant@signoffconsulting.com",
      status: "APPROVED",
      comments: "Cross-functional dependencies reviewed. All conflicts resolved.",
      conflictsReviewed: true,
      conflictCount: 3,
      conflictsResolved: 3,
      validatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
  };
}
