/**
 * SEED-010: Expired trial org with 2 read-only assessments
 * Purpose: Test expired trial behavior, read-only access, and upgrade prompts
 */
export function seedExpiredTrial() {
  const orgId = "seed-org-010";

  return {
    organization: {
      id: orgId,
      name: "Expired Trial LLC",
      slug: "expired-trial",
      type: "partner",
      orgType: "partner",
      plan: "TRIAL",
      subscriptionStatus: "TRIAL_EXPIRED",
      trialEndsAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      maxActiveAssessments: 1,
      maxPartnerUsers: 5,
      isActive: true,
    },
    users: [
      {
        id: "seed-user-010a",
        email: "owner@expiredtrial.com",
        name: "Fatimah Zahra",
        role: "partner_lead",
        organizationId: orgId,
        isActive: true,
      },
      {
        id: "seed-user-010b",
        email: "consultant@expiredtrial.com",
        name: "Raj Krishnan",
        role: "consultant",
        organizationId: orgId,
        isActive: true,
      },
    ],
    assessments: [
      {
        id: "seed-assessment-010a",
        companyName: "Alpha Retail Sdn Bhd",
        industry: "Retail",
        country: "MY",
        operatingCountries: ["MY"],
        companySize: "SMALL",
        revenueBand: "$10M-$50M",
        currentErp: "None",
        sapVersion: "2508",
        status: "scope_in_progress",
        createdBy: "seed-user-010b",
        organizationId: orgId,
        employeeCount: 150,
        annualRevenue: 25000000,
        currencyCode: "MYR",
        targetGoLiveDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        deploymentModel: "cloud",
        sapModules: ["FI", "CO", "MM", "SD"],
        keyProcesses: ["Order-to-Cash", "Procure-to-Pay"],
        languageRequirements: ["EN", "MS"],
        regulatoryFrameworks: ["SST"],
        itLandscapeSummary: "Greenfield implementation, no existing ERP",
        migrationApproach: "greenfield",
        profileCompletedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        profileCompletedBy: "seed-user-010b",
        phaseNumber: 1,
      },
      {
        id: "seed-assessment-010b",
        companyName: "Beta Services Pte Ltd",
        industry: "Professional Services",
        country: "SG",
        operatingCountries: ["SG", "MY"],
        companySize: "SMALL",
        revenueBand: "$10M-$50M",
        currentErp: "QuickBooks",
        sapVersion: "2508",
        status: "setup",
        createdBy: "seed-user-010b",
        organizationId: orgId,
        employeeCount: 80,
        annualRevenue: 15000000,
        currencyCode: "SGD",
        targetGoLiveDate: new Date(Date.now() + 270 * 24 * 60 * 60 * 1000),
        deploymentModel: "cloud",
        sapModules: ["FI", "CO"],
        keyProcesses: ["Record-to-Report"],
        languageRequirements: ["EN"],
        regulatoryFrameworks: ["SFRS"],
        itLandscapeSummary: "QuickBooks with Excel-based reporting",
        migrationApproach: "greenfield",
        phaseNumber: 1,
      },
    ],
  };
}
