#!/usr/bin/env python3
"""
Emit TypeScript ScopeItemContent modules from SAP BPDs + decisions YAMLs.

Companion to ft2std-toolkit/build_workbench.py — instead of HTML, this writes
typed TypeScript data files that the Next.js app consumes at build time.

Usage:
  python emit_ts.py 1IQ BD9 BDG
  python emit_ts.py --all

Output: lib/fts/data/<CODE>.ts (one per scope item) + lib/fts/data/index.ts (registry)
"""
import argparse
import json
import sys
from pathlib import Path

# Reuse the parser from the main toolkit
TOOLKIT = Path(__file__).resolve().parent.parent.parent / "ft2std-toolkit"
sys.path.insert(0, str(TOOLKIT))
from build_workbench import (  # noqa: E402
    parse_bpd,
    load_sscui_catalog,
    lookup_sscuis,
    load_decisions,
)

ROOT = Path(__file__).resolve().parent.parent
DECISIONS_DIR = ROOT / "scripts" / "decisions-yaml"
INPUT_DIR = TOOLKIT / "_input"          # BPDs + SSCUI catalog live here
DATA_DIR = ROOT / "lib" / "fts" / "data"


def to_ts(value):
    """Render a Python value as TypeScript literal."""
    return json.dumps(value, ensure_ascii=False, indent=2)


def emit_scope(code, catalog):
    """Build ScopeItemContent TS module for one scope code."""
    candidates = list(INPUT_DIR.glob(f"{code}_*.docx"))
    if not candidates:
        print(f"  [SKIP] No BPD for {code}")
        return False
    parsed = parse_bpd(candidates[0])

    # Override decisions dir to point at our YAMLs
    import build_workbench
    build_workbench.DECISIONS_DIR = DECISIONS_DIR
    decisions = load_decisions(code)

    sscui_refs = lookup_sscuis(catalog, code)

    payload = {
        "code": parsed["code"],
        "title": parsed["title"] or f"Scope item {code}",
        "overview": parsed["overview"] or "",
        "business_roles": parsed["business_roles"],
        "fiori_apps": parsed["fiori_apps"],
        "process_steps": parsed["process_steps"],
        "master_data": parsed["master_data"],
        "succeeding_processes": parsed["succeeding_processes"],
        "decisions": decisions,
        "sscui_refs": sscui_refs[:50],
        "release": "S/4HANA Cloud Public Edition 2602 — MY",
    }

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    out = DATA_DIR / f"{code}.ts"
    out.write_text(
        "// Auto-generated by scripts/emit_ts.py — do not edit by hand.\n"
        "// Source: SAP Best Practices BPD + decisions YAML.\n"
        "// Re-run: `python scripts/emit_ts.py " + code + "`\n\n"
        'import type { ScopeItemContent } from "../types";\n\n'
        f"const content: ScopeItemContent = {to_ts(payload)};\n\n"
        "export default content;\n",
        encoding="utf-8",
    )
    print(f"  [OK]   {code}: {parsed['title']} → lib/fts/data/{code}.ts "
          f"({len(parsed['process_steps'])} steps, {len(decisions)} decisions, "
          f"{len(sscui_refs)} SSCUIs)")
    return True


def _ident(code):
    """Produce a valid JS identifier from a scope code (which may start with a digit)."""
    return f"scope_{code}" if code[0].isdigit() else code


def emit_index(codes):
    """Build a registry file: lib/fts/data/index.ts"""
    imports = "\n".join(f'import {_ident(c)} from "./{c}";' for c in codes)
    registry = ",\n  ".join(f'"{c}": {_ident(c)}' for c in codes)
    index = (
        "// Auto-generated by scripts/emit_ts.py — do not edit by hand.\n\n"
        'import type { ScopeItemContent } from "../types";\n'
        f"{imports}\n\n"
        "/** Registry of all scope items with curated Tier-1 decisions. */\n"
        "export const scopeItems: Record<string, ScopeItemContent> = {\n"
        f"  {registry},\n"
        "};\n\n"
        "/** List of scope codes available, sorted alphabetically. */\n"
        "export const scopeCodes = Object.keys(scopeItems).sort();\n\n"
        "/** Look up a scope item by code; returns undefined if not found. */\n"
        "export function getScopeItem(code: string): ScopeItemContent | undefined {\n"
        "  return scopeItems[code];\n"
        "}\n"
    )
    (DATA_DIR / "index.ts").write_text(index, encoding="utf-8")
    print(f"  [OK]   index: {len(codes)} scope items registered → lib/fts/data/index.ts")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("codes", nargs="*")
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args()

    sscui_path = INPUT_DIR / "SSCUI_List_EN_XX.xlsm"
    if not sscui_path.exists():
        print(f"ERROR: missing {sscui_path}")
        sys.exit(1)

    print("Loading SSCUI catalog...")
    catalog = load_sscui_catalog(sscui_path)
    print(f"  {len(catalog)} configuration entries loaded.\n")

    if args.all:
        codes = sorted(p.stem for p in DECISIONS_DIR.glob("*.yaml")
                       if not p.stem.startswith("_"))
    else:
        codes = args.codes

    if not codes:
        print("Usage: python emit_ts.py 1IQ BD9 BDG   (or --all)")
        sys.exit(1)

    print(f"Emitting {len(codes)} TypeScript module(s):")
    successes = []
    for code in codes:
        if emit_scope(code, catalog):
            successes.append(code)
    if successes:
        emit_index(successes)
    print(f"\nDone. {len(successes)}/{len(codes)} modules emitted to lib/fts/data/")


if __name__ == "__main__":
    main()
