/**
 * 2608 WS5 — regenerate the Fit-to-Standard workbench data from the 2608 BPDs.
 *
 *   pnpm sap:2608:emit-fts            # write src/lib/fts/data/<CODE>.ts + index.ts + docs/2608/bpd-delta.md
 *   pnpm sap:2608:emit-fts -- --check # parse + compare, write nothing, exit 1 on drift
 *   pnpm sap:2608:emit-fts -- --json  # print the composed payloads
 *
 * Sources (all in the committed drop, sha256-pinned by sap-references/2608/MANIFEST.json):
 *   sap-references/2608/bpd-fts/<CODE>_S4CLD2608_BPD_EN_MY.xlsx   structured test case — the steps
 *   sap-references/2608/bpd-fts/<CODE>_S4CLD2608_BPD_EN_MY.docx   roles / master data / succeeding processes
 *
 * Curated Tier-1 decisions are CARRIED OVER from the committed data file of
 * the same code (they were emitted from scripts/decisions-yaml/<CODE>.yaml by
 * the 2602 toolkit and re-validated in WS1); a code with no prior file gets
 * `decisions: []`. This script never authors a decision.
 *
 * The delta report compares the 2608 steps with the 2602 baseline frozen in
 * scripts/lib/bpd-2608/baseline-2602.json (the three data files the 2602
 * workbench carried — 1IQ / BD9 / BDG — captured before this emitter first
 * ran), and "no exact steps in aptus" for the six items new to it.
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { composeBpd, type ComposedBpd } from "./lib/bpd-2608/compose";
import { parseBpdDocx, type BpdDocxParse } from "./lib/bpd-2608/parse-bpd-docx";
import { parseBpdXlsx, type BpdXlsxParse } from "./lib/bpd-2608/parse-bpd-xlsx";
import { BPD_2608_SCOPE_ITEMS, sapContentSourcesFor } from "./lib/sap-content-sources";
import { loadManifest } from "./lib/manifest-2608";
import BASELINE_2602 from "./lib/bpd-2608/baseline-2602.json";

const ROOT = process.cwd();
const DATA_DIR = path.join(ROOT, "src/lib/fts/data");
const DELTA_PATH = path.join(ROOT, "docs/2608/bpd-delta.md");
const RELEASE_LABEL = "S/4HANA Cloud Public Edition 2608 — MY";

type Decision = Record<string, unknown> & { id: string; sscui_id?: string };
type Baseline2602 = {
  title: string;
  steps: string[];
  roles: string[];
  apps: string[];
  decisions: number;
  sscuiRefs: number;
};
type PriorContent = {
  code: string;
  process_steps: { name: string; role: string; app: string; expected: string }[];
  business_roles: { name: string; id: string }[];
  fiori_apps: string[];
  decisions: Decision[];
  sscui_refs: { sscui_id: string; name: string; category: string; subarea: string }[];
  release: string;
};

export type EmittedScopeItem = ComposedBpd & {
  decisions: Decision[];
  sscui_refs: { sscui_id: string; name: string; category: string; subarea: string }[];
  release: string;
  source_note: string;
};

async function loadPrior(code: string): Promise<PriorContent | null> {
  const file = path.join(DATA_DIR, `${code}.ts`);
  if (!fs.existsSync(file)) return null;
  const mod = (await import(pathToFileURL(file).href)) as { default: PriorContent };
  return mod.default;
}

/**
 * sscui_refs are CARRIED OVER from the prior data file, never derived here.
 * The SSCUI_List 2608 "Main Scope Item ID" column is LoB-wide (a typical row
 * names 100–700 scope items; ~1,600 rows name 1IQ), so filtering it by scope
 * item would attach the whole sales configuration catalogue to every sales
 * item — grounding in name only. A per-item SSCUI appendix needs a curated
 * source; until then a new item carries an empty appendix.
 */
export function carriedSscuiRefs(prior: PriorContent | null): EmittedScopeItem["sscui_refs"] {
  return prior?.sscui_refs ?? [];
}

function renderDataFile(item: EmittedScopeItem, sha: { xlsx: string; docx: string }): string {
  const { provenance, ...payload } = item;
  const body = JSON.stringify(payload, null, 2);
  return (
    "// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.\n" +
    `// Source: sap-references/2608/bpd-fts/${item.code}_S4CLD2608_BPD_EN_MY.xlsx (sha256 ${sha.xlsx.slice(0, 12)}…)\n` +
    `//       + ${item.code}_S4CLD2608_BPD_EN_MY.docx (sha256 ${sha.docx.slice(0, 12)}…) for roles / master data / succeeding processes.\n` +
    `// Steps: xlsx activities after "Test Procedures" (${item.process_steps.length}); ${provenance.stepsFilledFromDocx} step(s) took role/app/expected from the docx Overview Table.\n` +
    `// Decisions: ${item.decisions.length === 0 ? "none curated yet" : "carried over from the curated set (scripts/decisions-yaml)"}; sscui_refs: ${item.sscui_refs.length === 0 ? "none (no curated per-item SSCUI source yet)" : `${item.sscui_refs.length} carried over from the curated 2602 appendix`}.\n` +
    "// Re-run: `pnpm sap:2608:emit-fts`\n\n" +
    'import type { ScopeItemContent } from "../types";\n\n' +
    `const content: ScopeItemContent = ${body};\n\n` +
    "export default content;\n"
  );
}

function renderIndex(codes: string[]): string {
  const ident = (c: string) => (/^\d/.test(c) ? `scope_${c}` : c);
  return (
    "// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.\n" +
    "// Re-run: `pnpm sap:2608:emit-fts`\n" +
    "//\n" +
    "// MANUAL ADDITION (not emitted by the script): the O2C-SALES VALUE\n" +
    "// STREAM entry. See src/lib/fts/value-streams/o2c-sales.ts. The emitter\n" +
    "// preserves this import + map line on every run.\n\n" +
    'import type { ScopeItemContent } from "../types";\n' +
    codes.map((c) => `import ${ident(c)} from "./${c}";`).join("\n") +
    '\nimport { O2C_SALES } from "../value-streams/o2c-sales";\n\n' +
    "/** Registry of all scope items with curated Tier-1 decisions. */\n" +
    "export const scopeItems: Record<string, ScopeItemContent> = {\n" +
    codes.map((c) => `  ${/^\d/.test(c) ? `"${c}"` : c}: ${ident(c)},`).join("\n") +
    '\n  "O2C-SALES": O2C_SALES,\n};\n\n' +
    "/** List of scope codes available, sorted alphabetically. */\n" +
    "export const scopeCodes = Object.keys(scopeItems).sort();\n\n" +
    "/** Look up a scope item by code; returns undefined if not found. */\n" +
    "export function getScopeItem(code: string): ScopeItemContent | undefined {\n" +
    "  return scopeItems[code];\n" +
    "}\n"
  );
}

type Delta = {
  code: string;
  title: string;
  before: number | null;
  after: number;
  added: string[];
  removed: string[];
  renamedNote: string;
  rolesBefore: number | null;
  rolesAfter: number;
  appsBefore: number | null;
  appsAfter: number;
  decisions: number;
  sscuiRefs: number;
  provenance: ComposedBpd["provenance"];
  preliminary: number;
  docxHeadings: number;
};

function stepKey(s: string): string {
  return s
    .toLowerCase()
    .replace(/\(optional\)/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function diffSteps(before: string[] | null, after: string[]): Pick<Delta, "added" | "removed"> {
  if (!before) return { added: after, removed: [] };
  const b = new Set(before.map(stepKey));
  const a = new Set(after.map(stepKey));
  return { added: after.filter((s) => !b.has(stepKey(s))), removed: before.filter((s) => !a.has(stepKey(s))) };
}

function renderDelta(deltas: Delta[], generatedAt: string): string {
  const lines: string[] = [];
  lines.push("# BPD 2602 → 2608 — Fit-to-Standard step delta");
  lines.push("");
  lines.push(
    `Generated ${generatedAt} by \`scripts/emit-fts-2608.ts\` from the committed 2608 drop (\`sap-references/2608/bpd-fts/\`).`,
  );
  lines.push("");
  lines.push(
    "**Baseline.** The 2602 workbench carried exact steps for three scope items only (1IQ, BD9, BDG — parsed from the 2602 BPD docx by the external toolkit). The other six items in the 2608 drop had no data file, so their 2602 column reads *none*: they now have exact steps for the first time.",
  );
  lines.push("");
  lines.push(
    "**Method.** 2608 steps = the xlsx test-case activities after the `Test Procedures` marker (the click-level test script), one step per activity, in SAP's order. Steps are compared by name (case-insensitive, `(Optional)` ignored). Roles come from the docx Roles table; apps from the steps' `Access the App` actions plus the docx Overview Table.",
  );
  lines.push("");
  lines.push(
    "| Code | Title | Steps 2602 | Steps 2608 | Added | Removed | Roles | Apps | Decisions | SSCUI refs (carried) |",
  );
  lines.push("|---|---|---:|---:|---:|---:|---|---|---:|---:|");
  for (const d of deltas) {
    const roles = d.rolesBefore == null ? `${d.rolesAfter}` : `${d.rolesBefore} → ${d.rolesAfter}`;
    const apps = d.appsBefore == null ? `${d.appsAfter}` : `${d.appsBefore} → ${d.appsAfter}`;
    lines.push(
      `| ${d.code} | ${d.title} | ${d.before == null ? "none" : d.before} | ${d.after} | ${d.added.length} | ${d.removed.length} | ${roles} | ${apps} | ${d.decisions} | ${d.sscuiRefs} |`,
    );
  }
  lines.push("");
  for (const d of deltas) {
    lines.push(`## ${d.code} — ${d.title}`);
    lines.push("");
    lines.push(
      `- 2608 source: xlsx steps ${d.after}; ${d.provenance.stepsFilledFromDocx} step(s) took role/app/expected from the docx Overview Table (${d.provenance.docxOverviewSteps} rows); ${d.preliminary} preliminary/configuration activities before the steps (not counted as steps); docx procedure headings ${d.docxHeadings}.`,
    );
    if (d.before == null)
      lines.push(
        `- 2602: no exact steps in aptus (not in the workbench). All ${d.after} steps are new to the workbench.`,
      );
    else {
      lines.push(`- 2602 → 2608: ${d.before} → ${d.after} steps.${d.renamedNote}`);
      if (d.added.length) lines.push(`- Added (${d.added.length}): ${d.added.map((s) => `\`${s}\``).join(", ")}`);
      if (d.removed.length)
        lines.push(`- Removed (${d.removed.length}): ${d.removed.map((s) => `\`${s}\``).join(", ")}`);
      if (!d.added.length && !d.removed.length) lines.push("- Step names unchanged.");
    }
    if (d.decisions === 0)
      lines.push(
        "- Decisions: none curated yet — the item renders its steps; Tier-1 decisions are a curation task (scripts/decisions-yaml).",
      );
    if (d.sscuiRefs === 0)
      lines.push(
        '- SSCUI appendix: empty — the SSCUI_List "Main Scope Item ID" column is LoB-wide (a row names 100–700 items), so no per-item list is derived from it.',
      );
    lines.push("");
  }
  lines.push("## What this report does not claim");
  lines.push("");
  lines.push(
    "- The 2602 baseline for the six new items is *absence from the workbench*, not the 2602 BPD: the 2602 drop is not in the repository (WS0), so no 2602 xlsx could be parsed for them.",
  );
  lines.push(
    "- A step whose name changed between releases shows as one removal plus one addition; the report does not guess at renames.",
  );
  lines.push(
    "- Role/app cells are SAP's wording from the test script; a step whose script names no role or app keeps an empty cell rather than an inferred one.",
  );
  return lines.join("\n") + "\n";
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const json = process.argv.includes("--json");
  const sources = sapContentSourcesFor("2608");
  const manifest = loadManifest(sources.manifest!);
  const shaOf = (rel: string) => manifest.files.find((f) => f.file === rel)?.sha256 ?? "";

  const generatedAt = new Date().toISOString().slice(0, 10);
  const items: EmittedScopeItem[] = [];
  const deltas: Delta[] = [];
  const problems: string[] = [];

  for (const code of BPD_2608_SCOPE_ITEMS) {
    const src = sources.bpd.find((b) => b.scopeItemCode === code)!;
    const x: BpdXlsxParse = await parseBpdXlsx(src.xlsx, code);
    let d: BpdDocxParse | null = null;
    try {
      d = parseBpdDocx(src.docx, code);
    } catch (err) {
      problems.push(`${code}: docx not parsed (${err instanceof Error ? err.message : String(err)}) — xlsx only`);
    }
    const composed = composeBpd(x, d);
    const prior = await loadPrior(code);
    const sscui_refs = carriedSscuiRefs(prior);
    const item: EmittedScopeItem = {
      ...composed,
      decisions: prior?.decisions ?? [],
      sscui_refs,
      release: RELEASE_LABEL,
      source_note: `Generated from ${code}_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · ${composed.process_steps.length} steps`,
    };
    if (item.process_steps.length === 0) problems.push(`${code}: zero steps parsed`);
    items.push(item);

    const baseline = (BASELINE_2602 as Record<string, Baseline2602 | unknown>)[code] as Baseline2602 | undefined;
    const before = baseline?.steps ?? null;
    const after = item.process_steps.map((s) => s.name);
    deltas.push({
      code,
      title: item.title,
      before: before ? before.length : null,
      after: after.length,
      ...diffSteps(before, after),
      renamedNote: "",
      rolesBefore: baseline ? baseline.roles.length : null,
      rolesAfter: item.business_roles.length,
      appsBefore: baseline ? baseline.apps.length : null,
      appsAfter: item.fiori_apps.length,
      decisions: item.decisions.length,
      sscuiRefs: sscui_refs.length,
      provenance: composed.provenance,
      preliminary: x.preliminary.length,
      docxHeadings: d?.procedureHeadings.length ?? 0,
    });
  }

  if (json) {
    console.log(JSON.stringify({ items, deltas }, null, 2));
    return;
  }

  const rendered = new Map<string, string>();
  for (const item of items) {
    const src = sources.bpd.find((b) => b.scopeItemCode === item.code)!;
    rendered.set(
      path.join(DATA_DIR, `${item.code}.ts`),
      renderDataFile(item, { xlsx: shaOf(src.xlsx), docx: shaOf(src.docx) }),
    );
  }
  rendered.set(path.join(DATA_DIR, "index.ts"), renderIndex([...BPD_2608_SCOPE_ITEMS]));
  rendered.set(DELTA_PATH, renderDelta(deltas, generatedAt));

  if (check) {
    let drift = 0;
    for (const [file, content] of rendered) {
      // The delta report carries a date; compare everything but its header line.
      const strip = (s: string) => (file === DELTA_PATH ? s.replace(/^Generated .*$/m, "") : s);
      const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
      if (strip(current) !== strip(content)) {
        drift++;
        console.log(`DRIFT  ${path.relative(ROOT, file)}`);
      }
    }
    for (const p of problems) console.log(`WARN   ${p}`);
    console.log(
      drift === 0 && problems.length === 0
        ? "OK: fts data matches the 2608 drop"
        : `FAIL: ${drift} file(s) differ, ${problems.length} problem(s)`,
    );
    process.exit(drift === 0 && problems.length === 0 ? 0 : 1);
  }

  for (const [file, content] of rendered) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, "utf8");
  }
  for (const d of deltas) {
    console.log(
      `${d.code.padEnd(4)} ${d.title.padEnd(48)} steps ${String(d.before ?? "none").padStart(4)} → ${String(d.after).padStart(3)}  roles ${d.rolesAfter}  apps ${d.appsAfter}  decisions ${d.decisions}  sscui ${d.sscuiRefs}`,
    );
  }
  for (const p of problems) console.log(`WARN ${p}`);
  console.log(`wrote ${rendered.size} files (data, index, ${path.relative(ROOT, DELTA_PATH)})`);
  if (problems.length > 0) process.exit(1);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
