// Auto-generated by scripts/emit_ts.py — do not edit by hand.
// Source: SAP Best Practices BPD + decisions YAML.
// Re-run: `python scripts/emit_ts.py 1IQ`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "1IQ",
  "title": "Sales Inquiry",
  "overview": "This scope item describes the process for a standard sales inquiry. It allows you to create, edit, and reject an inquiry. You can then create a quotation or sales order based on the inquiry.",
  "business_roles": [
    {
      "name": "Internal Sales Representative",
      "id": "SAP_BR_INTERNAL_SALES_REP"
    }
  ],
  "fiori_apps": [
    "Manage Sales Inquiries (F2370)"
  ],
  "process_steps": [
    {
      "name": "Create Sales Inquiry",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Inquiries (F2370)",
      "expected": "The sales inquiry is created and printed."
    },
    {
      "name": "Change Sales Inquiry",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Inquiries (F2370)",
      "expected": "The sales inquiry is changed."
    },
    {
      "name": "Reject Sales Inquiry",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Inquiries (F2370)",
      "expected": "The sales inquiry is rejected."
    }
  ],
  "master_data": [
    {
      "data": "Material",
      "sample": "TG11",
      "details": "Trading Good for Reg. Trading (MRP planning)"
    },
    {
      "data": "Material",
      "sample": "TG12",
      "details": "Trad.Good 12,Reorder Point,Reg.Trad."
    },
    {
      "data": "Material",
      "sample": "TG21",
      "details": "Trad.Good 21,Reorder Point,Batch-FIFO"
    },
    {
      "data": "Material",
      "sample": "TG22",
      "details": "Trad.Good 22,Reorder Point,Batch-ExpD"
    },
    {
      "data": "Sold-to party",
      "sample": "54100003",
      "details": "Domestic MY Customer 3"
    },
    {
      "data": "Ship-to party",
      "sample": "54100003",
      "details": "Domestic MY Customer 3"
    },
    {
      "data": "Payer",
      "sample": "54100003",
      "details": "Customer domestic 03"
    },
    {
      "data": "Plant",
      "sample": "5410",
      "details": "Plant 1 MY"
    },
    {
      "data": "Storage Location",
      "sample": "541A",
      "details": ""
    },
    {
      "data": "Shipping Point",
      "sample": "5410",
      "details": ""
    },
    {
      "data": "Sales Organization",
      "sample": "5410",
      "details": ""
    },
    {
      "data": "Distribution Channel",
      "sample": "10",
      "details": ""
    },
    {
      "data": "Material",
      "sample": "SM0001",
      "details": "Service Material 01"
    },
    {
      "data": "Material",
      "sample": "NS0002",
      "details": "Non-Stock Material 02"
    }
  ],
  "succeeding_processes": [
    {
      "raw": "BDG – Sales Quotation (optional)",
      "description": "This scope item describes the sequence for a standard quotation process with a customer.\nUsing the master data from this document, complete the following activities described in the Test Script:\nSales Quotation (BDG).\nCreate a sales order with reference using the sales inquiry number."
    },
    {
      "raw": "BD9- Sell from Stock (optional)",
      "description": "This scope item describes the sequence for a standard sales process (sell from stock) with a customer.\nUsing the master data from this document, complete the following activities described in The test Script:\nSell from Stock (BD9).\nCreate a sales order with reference using the sales inquiry number."
    }
  ],
  "decisions": [
    {
      "id": "d1",
      "title": "Inquiry document type",
      "summary": "SAP delivers a standard inquiry document type (IN). Do you need a custom inquiry type (e.g., \"Service Inquiry\" vs \"Product Inquiry\")?\n",
      "sscui": "102495 - Configure Sales Document Types",
      "sscui_id": "102495",
      "sscui_name": "Configure Sales Document Types",
      "std_desc": "Use SAP standard inquiry type IN. Fastest path.",
      "cfg_desc": "Add one or two additional inquiry types via SSCUI. Included in base scope.",
      "cst_desc": "Build a custom inquiry document type with custom fields/logic. ~3-5 days extra effort.",
      "effort": 4,
      "custom_type": "Key User Extensibility (custom fields) + Custom Sales Doc Type",
      "ext_impact": "Medium - custom fields need regression test each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d2",
      "title": "Number ranges for inquiries",
      "summary": "How should inquiries be numbered? SAP uses an internal numeric range by default.",
      "sscui": "102819 - Define Number Ranges for Sales Documents",
      "sscui_id": "102819",
      "sscui_name": "Define Number Ranges for Sales Documents",
      "std_desc": "Accept SAP standard internal numbering.",
      "cfg_desc": "Define your own number range pattern via SSCUI (e.g., prefix by year). Included.",
      "cst_desc": "Number generation logic tied to external system / custom prefix scheme. ~2 days.",
      "effort": 2,
      "custom_type": "Developer Extensibility (custom number range BAdI)",
      "ext_impact": "Medium - BAdI implementation, retest on each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d3",
      "title": "Reasons for rejection",
      "summary": "When an inquiry is rejected, what reasons should be available in the dropdown? SAP delivers ~20 standard reasons.\n",
      "sscui": "Standard configuration in OVAG",
      "sscui_id": "OVAG",
      "sscui_name": "Define Reasons for Rejection",
      "std_desc": "Use SAP standard rejection reasons. Most clients find these sufficient.",
      "cfg_desc": "Add or rename rejection reasons. Included.",
      "cst_desc": "Conditional rejection logic (e.g., auto-route certain reasons to approval). ~3 days.",
      "effort": 3,
      "custom_type": "Developer Extensibility + Flexible Workflow",
      "ext_impact": "Medium - conditional logic + workflow integration",
      "ricefw_class": "W (Workflow)"
    },
    {
      "id": "d4",
      "title": "Pricing on the inquiry",
      "summary": "Should the inquiry show preliminary pricing? Standard SAP runs full pricing on inquiry.",
      "sscui": "104274/75/76 - Pricing Date logic",
      "sscui_id": "104274",
      "sscui_name": "Pricing Date - Parameter Catalog / Formulas / Custom Routines",
      "std_desc": "Standard pricing runs at inquiry creation. No commitment, just an indicative price.",
      "cfg_desc": "Adjust pricing date logic (e.g., use requested delivery date, not inquiry date). Included.",
      "cst_desc": "Custom pricing routine for inquiries (e.g., apply promo logic only at inquiry stage). ~5 days.",
      "effort": 5,
      "custom_type": "Developer Extensibility (custom pricing routine)",
      "ext_impact": "High - custom pricing impacts all downstream sales docs, full regression each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d5",
      "title": "Requested delivery date logic",
      "summary": "How should the system default and validate the requested delivery date entered by the rep?",
      "sscui": "103827-30 - Requested Delivery Date parameters & formulas",
      "sscui_id": "103827",
      "sscui_name": "Requested Delivery Date - Parameters / Formulas / Rules / Custom Routines",
      "std_desc": "Default = today + standard lead time. Standard behavior.",
      "cfg_desc": "Customize default formula via SSCUI (e.g., today + 14 days, skip weekends). Included.",
      "cst_desc": "Custom routine to look up delivery date from external planning system. ~4 days.",
      "effort": 4,
      "custom_type": "Developer Extensibility (custom date routine) + Integration",
      "ext_impact": "Medium-High - external system dependency, integration regression each release",
      "ricefw_class": "I (Interface)"
    },
    {
      "id": "d6",
      "title": "Output (print/email of inquiry)",
      "summary": "When the inquiry is created, should it auto-print, email to customer, or stay internal?",
      "sscui": "Output Management - standard channels",
      "sscui_id": "OM",
      "sscui_name": "Output Management Configuration",
      "std_desc": "No automatic output. Rep chooses Print/Email manually.",
      "cfg_desc": "Auto-email inquiry confirmation to customer using standard SAP form. Included.",
      "cst_desc": "Custom PDF layout with company branding / custom fields. ~3 days per form variant.",
      "effort": 3,
      "custom_type": "Adobe Forms (Form Template) + Key User Extensibility",
      "ext_impact": "Low - form templates are upgrade-stable",
      "ricefw_class": "F (Form)"
    },
    {
      "id": "d7",
      "title": "Approval workflow before quotation conversion",
      "summary": "Does an inquiry need management approval before it can be converted to a quotation?",
      "sscui": "Flexible Workflow for Sales Documents",
      "sscui_id": "FW",
      "sscui_name": "Flexible Workflow Configuration",
      "std_desc": "No approval. Any inquiry can be converted to quotation directly.",
      "cfg_desc": "Use SAP Flexible Workflow with threshold-based approval (e.g., > MYR 100k). Included.",
      "cst_desc": "Multi-stage approval with custom routing logic and integration to external approval tool. ~7 days.",
      "effort": 7,
      "custom_type": "Workflow Developer Extension + Integration",
      "ext_impact": "High - multi-stage approval logic + external system, full retest each release",
      "ricefw_class": "W (Workflow)"
    }
  ],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2602 — MY"
};

export default content;
