// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Source: sap-references/2608/bpd-fts/1NT_S4CLD2608_BPD_EN_MY.xlsx (sha256 b018d9639de7…)
//       + 1NT_S4CLD2608_BPD_EN_MY.docx (sha256 447ec6f2b045…) for roles / master data / succeeding processes.
// Steps: xlsx activities after "Test Procedures" (32); 23 step(s) took role/app/expected from the docx Overview Table.
// Decisions: none curated yet; sscui_refs: none (no curated per-item SSCUI source yet).
// Re-run: `pnpm sap:2608:emit-fts`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "1NT",
  "title": "Project Control – Finance",
  "overview": "For many purposes, companies run projects to plan and coordinate the work, staff employees, and track project progress and costs. In this scenario, a Work Breakdown Structure (WBS) as an accounting structure is created. Planned project costs (uploaded by the project financial controller) can be captured in SAP Analytics Cloud. After releasing all or part of the project, the project is executed. Time can be recorded, and project-related purchasing can be performed. In finance, allocations or general journal entries can be done with regard to project WBS elements. The project financial controller monitors the project costs through overview pages and detailed project reporting. At period end, depending on the type of project, different period-end closing activities such as overhead application or settlement can be executed for a project. Afterwards, the financial controller completes and closes project parts and then closes the complete project.",
  "business_roles": [
    {
      "name": "Project Financial Controller",
      "id": "SAP_BR_PROJ_FIN_CONTROLLER"
    },
    {
      "name": "Configuration Expert - Business Process Configuration",
      "id": "SAP_BR_BPC_EXPERT"
    },
    {
      "name": "General Ledger Accountant",
      "id": "SAP_BR_GL_ACCOUNTANT"
    },
    {
      "name": "Cost Accountant - Overhead",
      "id": "SAP_BR_OVERHEAD_ACCOUNTANT"
    },
    {
      "name": "Analytics Specialist",
      "id": "SAP_BR_ANALYTICS_SPECIALIST"
    },
    {
      "name": "Business Process Specialist",
      "id": "SAP_BR_BUSINESS_PROCESS_SPEC"
    },
    {
      "name": "Business Process Specialist",
      "id": "SAP_BR_BUSINESS_PROCESS_SPEC"
    }
  ],
  "fiori_apps": [
    "Project Control - Enterprise Projects (F3215)",
    "See the test script.",
    "Project Control - Enterprise Projects (F3215) and Mass Changes to Projects (F3891)",
    "Mass Changes to Projects (F3891)",
    "Import Financial Plan Data (F1711)",
    "Manage Budget Documents - Projects (F5342)",
    "Manage Direct Activity Allocation - Deprecated (F3697)",
    "Post General Journal Entries (F0718)",
    "Project Financial Controller Overview or Project Budget Report or Monitor Projects or P&L Plan/Actual or Project Cost Report Plan/Actual",
    "Project Financial Controller Overview (F3078)",
    "Monitor Projects (F3088)",
    "Project Cost Report - Plan/Actual (F2513)",
    "Project Budget Report (F3377)",
    "Manage Project Procurement (F2930)",
    "P&L Plan/Actual - Profit and Loss (F1710)",
    "See the Period-End Closing – Projects (BNA) test script."
  ],
  "process_steps": [
    {
      "name": "Create Project",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "Project definition and WBS Elements with all the required parameters will be created."
    },
    {
      "name": "Create Project Using Copy Functionality (Optional)",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "Project is created with the provided definition parameters."
    },
    {
      "name": "Project Review (Optional)",
      "role": "Project Financial Controller",
      "app": "See the test script.",
      "expected": "See the test script."
    },
    {
      "name": "Update Project (Optional)",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215) and Mass Changes to Projects (F3891)",
      "expected": "Created projects can be updated."
    },
    {
      "name": "Mass Changes to Projects and Work Packages (Optional)",
      "role": "Project Financial Controller",
      "app": "Mass Changes to Projects (F3891)",
      "expected": "Multiple projects can be modified simultaneously."
    },
    {
      "name": "Capture Planned Costs",
      "role": "Project Financial Controller",
      "app": "Import Financial Plan Data (F1711)",
      "expected": "Planned costs for the project WBS Element are posted"
    },
    {
      "name": "Capture Project Budget",
      "role": "Project Financial Controller",
      "app": "Import Financial Plan Data (F1711)",
      "expected": "Budget for the project WBS Element is posted"
    },
    {
      "name": "Upload Project Budget (Optional)",
      "role": "Project Financial Controller",
      "app": "Import Financial Plan Data (F1711)",
      "expected": "A CSV file will be saved with the budget details."
    },
    {
      "name": "Manage Project Budget (Optional)",
      "role": "Project Financial Controller",
      "app": "Manage Budget Documents - Projects (F5342)",
      "expected": "The budget supplement document is created"
    },
    {
      "name": "Define Demand",
      "role": "See the test script.",
      "app": "See the test script.",
      "expected": "See the test script."
    },
    {
      "name": "Release Projects/Project Parts",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "The project status is changed to REL (Release)"
    },
    {
      "name": "Direct Activity Allocation",
      "role": "Project Financial Controller",
      "app": "Manage Direct Activity Allocation - Deprecated (F3697)",
      "expected": "Actual activities that occurred in relation to a WBS element are confirmed"
    },
    {
      "name": "Post General Journal Entry",
      "role": "General Ledger Accountant",
      "app": "Post General Journal Entries (F0718)",
      "expected": "Post actual primary costs to WBS elements"
    },
    {
      "name": "Time Recording",
      "role": "See the test script.",
      "app": "See the test script.",
      "expected": "See the test script."
    },
    {
      "name": "Project Control Procurement",
      "role": "See the test script.",
      "app": "See the test script.",
      "expected": "See the test script."
    },
    {
      "name": "Monitor Projects",
      "role": "Project Financial Controller",
      "app": "Project Financial Controller Overview or Project Budget Report or Monitor Projects or P&L Plan/Actual or Project Cost Report Plan/Actual",
      "expected": "Compare Project actual vs planned"
    },
    {
      "name": "Monitor Notification (Optional)",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "Notifications triggered by situation management are displayed."
    },
    {
      "name": "Monitor Projects via Project Financial Controller Overview",
      "role": "Project Financial Controller",
      "app": "Project Financial Controller Overview (F3078)",
      "expected": "The Overall Status, Planned and Active Projects, Actual costs, Cost to Date-Timeline and Upcoming Milestones are displayed."
    },
    {
      "name": "Monitor Projects via Monitor Projects App",
      "role": "Project Financial Controller",
      "app": "Monitor Projects (F3088)",
      "expected": "A detailed view of the project cost, project progress is displayed in graphical form.."
    },
    {
      "name": "Monitor Projects via Project Cost Report",
      "role": "Project Financial Controller",
      "app": "Project Cost Report - Plan/Actual (F2513)",
      "expected": "All plan, actual costs and their variances are displayed."
    },
    {
      "name": "Monitor Projects via Project Budget Report",
      "role": "Project Financial Controller",
      "app": "Project Budget Report (F3377)",
      "expected": "The cumulative actual costs, commitments, budget planned and available budget on the project are displayed."
    },
    {
      "name": "Monitor Projects via Manage Project Procurement",
      "role": "Project Financial Controller",
      "app": "Manage Project Procurement (F2930)",
      "expected": "Details of the project related to purchase order and purchase requisition, such as delivery quantity, net order value, delivery date and so on are displayed"
    },
    {
      "name": "Monitor Projects via P&amp;L Plan/Actual",
      "role": "Project Financial Controller",
      "app": "P&L Plan/Actual - Profit and Loss (F1710)",
      "expected": "All actual costs are displayed."
    },
    {
      "name": "Check/update Settlement Rules (Optional)",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "Settlement rule is updated"
    },
    {
      "name": "Settlement Rule for Overhead Projects",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "Settlement rule would be generated with regard to cost centers."
    },
    {
      "name": "Settlement Rule for Investment Projects",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Period End Closing Projects (Optional)",
      "role": "See the Period-End Closing – Projects (BNA) test script.",
      "app": "See the Period-End Closing – Projects (BNA) test script.",
      "expected": "See the Period-End Closing – Projects (BNA) test script."
    },
    {
      "name": "Period End Closing Projects - Apply Overhead (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Period End Closing Projects – Run Settlements",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Period End Closing Projects- Monitor Financials",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Complete Project Parts and Project",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "Project Status should be changed to TECO (Technically complete)"
    },
    {
      "name": "Close Project Parts and Project",
      "role": "Project Financial Controller",
      "app": "Project Control - Enterprise Projects (F3215)",
      "expected": "Project Status should be changed to CLSD (Closed)"
    }
  ],
  "master_data": [
    {
      "data": "Controlling Area",
      "sample": "A000",
      "details": "Controlling Area A000"
    },
    {
      "data": "Company Code",
      "sample": "5410",
      "details": "Company Code 5410"
    },
    {
      "data": "Plant",
      "sample": "5410",
      "details": "Plant 1 MY"
    },
    {
      "data": "Cost Center",
      "sample": "54101501\n54101601\n54101321",
      "details": "R&D Cost center\nMarketing Cost Center\nServices/Consltg"
    },
    {
      "data": "Activity Types",
      "sample": "8",
      "details": "Consulting"
    },
    {
      "data": "Cost Rate",
      "sample": "Actual and planned cost rates are maintained for the following combination of cost centers and activity types:\nCost centers: 54101321, 54101101\nActivity types: 8",
      "details": ""
    },
    {
      "data": "G/L Account",
      "sample": "61005000",
      "details": "Trav. Expense – Ground transportation"
    },
    {
      "data": "61008000",
      "sample": "Travel Expenses – Miscellaneous",
      "details": ""
    },
    {
      "data": "10010000",
      "sample": "Petty Cash",
      "details": ""
    },
    {
      "data": "Profit Center",
      "sample": "YB600\nYB110",
      "details": "Shared Services\nProduct A"
    },
    {
      "data": "Functional Area",
      "sample": "YB25\nYB75",
      "details": "Consulting/Services\nOther expenses"
    }
  ],
  "succeeding_processes": [
    {
      "raw": "BNA",
      "description": "Period-End Closing - Projects"
    }
  ],
  "decisions": [],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2608 — MY",
  "source_note": "Generated from 1NT_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · 32 steps"
};

export default content;
