// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Source: sap-references/2608/bpd-fts/2ET_S4CLD2608_BPD_EN_MY.xlsx (sha256 62f86695c296…)
//       + 2ET_S4CLD2608_BPD_EN_MY.docx (sha256 6f3020a6d4bb…) for roles / master data / succeeding processes.
// Steps: xlsx activities after "Test Procedures" (13); 10 step(s) took role/app/expected from the docx Overview Table.
// Decisions: none curated yet; sscui_refs: none (no curated per-item SSCUI source yet).
// Re-run: `pnpm sap:2608:emit-fts`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "2ET",
  "title": "Sales Order Processing for Non-Stock Material",
  "overview": "A non-stock material can be used in the Sales Order. Non-stock materials are not included in inventory management. With creation of a delivery, the goods issue is reflected by a confirmation posting. Non-stock items can be handled along with stock items on one sales order.",
  "business_roles": [
    {
      "name": "Internal Sales Representative",
      "id": "SAP_BR_INTERNAL_SALES_REP"
    },
    {
      "name": "Shipping Specialist",
      "id": "SAP_BR_SHIPPING_SPECIALIST"
    },
    {
      "name": "Billing Clerk",
      "id": "SAP_BR_BILLING_CLERK"
    },
    {
      "name": "Credit Controller",
      "id": "SAP_BR_CREDIT_CONTROLLER"
    },
    {
      "name": "Master Data Specialist - Business Partner Data",
      "id": "SAP_BR_BUPA_MASTER_SPECIALIST"
    },
    {
      "name": "Configuration Expert - Business Process Configuration",
      "id": "SAP_BR_BPC_EXPERT"
    }
  ],
  "fiori_apps": [
    "Manage Sales Orders - Version 2 (F3893)",
    "Create Outbound Deliveries - From Sales Orders (F0869A)",
    "Split Outbound Delivery (VLSP)",
    "Change Outbound Delivery (VL02N)",
    "Change Outbound Delivery - Proof of Delivery (VLPOD)",
    "Create Billing Documents (F0798)",
    "Create Billing Documents - VF01 (VF01)"
  ],
  "process_steps": [
    {
      "name": "Basic Credit Management (BD6) - Set Credit Limit (Optional)",
      "role": "Credit Controller",
      "app": "",
      "expected": "Credit Limit for Customer 54100005 has been set."
    },
    {
      "name": "Sales Quotation (BDG) (Optional)",
      "role": "Internal Sales Representative",
      "app": "",
      "expected": ""
    },
    {
      "name": "Sales Contract (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Sales Order",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders - Version 2 (F3893)",
      "expected": "The Manage Sales Orders screen displays."
    },
    {
      "name": "Process Sales Order Approval (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Basic Credit Management (BD6) - Review Blocked Sales Orders (Optional)",
      "role": "Credit Controller",
      "app": "",
      "expected": "Sales order is released."
    },
    {
      "name": "Create Delivery",
      "role": "Shipping Specialist",
      "app": "Create Outbound Deliveries - From Sales Orders (F0869A)",
      "expected": "Delivery is created."
    },
    {
      "name": "Split Outbound Delivery (Optional)",
      "role": "Shipping Specialist",
      "app": "Split Outbound Delivery (VLSP)",
      "expected": "Single outbound delivery split into two (according to preconfigured split profile)"
    },
    {
      "name": "Add Freight Cost (Optional)",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": "Freight Costs are added to the Outbound Delivery and will be later copied to the Invoice."
    },
    {
      "name": "Post Goods Issue",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": "The goods issue is posted."
    },
    {
      "name": "Proof of Delivery (Optional)",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery - Proof of Delivery (VLPOD)",
      "expected": "The Outbound Delivery document is saved with confirmation for actually delivered quantities."
    },
    {
      "name": "Create Billing Document",
      "role": "Billing Clerk",
      "app": "Create Billing Documents (F0798)",
      "expected": "Billing is carried out."
    },
    {
      "name": "Create Pro Forma Invoice (Optional)",
      "role": "Billing Clerk",
      "app": "Create Billing Documents - VF01 (VF01)",
      "expected": "Preview for PDF document displays."
    }
  ],
  "master_data": [
    {
      "data": "Material",
      "sample": "NS0002",
      "details": "Non-Stock Material 02 (No MRP planning)\nNo serial number, no batch"
    },
    {
      "data": "Sold-to party",
      "sample": "54100003 54100005 54100009",
      "details": "Domestic MY Customer 3 Domestic MY Customer 5 Domestic MY Customer 9"
    },
    {
      "data": "Ship-to party",
      "sample": "54100003 54100005 54100009",
      "details": "Domestic MY Customer 3 Domestic MY Customer 5 Domestic MY Customer 9"
    },
    {
      "data": "Payer",
      "sample": "54100003 54100005 54100009",
      "details": "Customer domestic 03 Customer domestic 05 Domestic MY Customer 9"
    },
    {
      "data": "Plant",
      "sample": "5410",
      "details": "Plant 1 MY"
    },
    {
      "data": "Storage Location",
      "sample": "541A",
      "details": "Std. storage 1"
    },
    {
      "data": "Shipping Point",
      "sample": "5410",
      "details": "Shipping Point 5410"
    },
    {
      "data": "Sales organization",
      "sample": "5410",
      "details": "Dom. Sales Org"
    },
    {
      "data": "Distribution channel",
      "sample": "10",
      "details": "Direct Sales"
    },
    {
      "data": "Division",
      "sample": "00",
      "details": "Product Division 00"
    }
  ],
  "succeeding_processes": [
    {
      "raw": "Accounts Receivable (J59)",
      "description": "Posting a Customer Invoice in Accounting, and so on.\nUsing the master data from this document, complete the following activities described in the test script:\nPosting a Customer Invoice in Accounting\nOverdue Receivables, Display Customer Balances\nManage Customer Line Items"
    },
    {
      "raw": "Sales Period End Closing Operations (BKK) (optional)",
      "description": "This scope item describes the collection of periodic activities such as day ending activities, or reporting.\nUsing the master data from this document, complete all the activities described in the Test Script of the scope item:\nReview Incomplete SAP Digital Documents (deliveries),\nReview Sales Documents blocked for billing\nReview Log of collective invoice creation"
    }
  ],
  "decisions": [],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2608 — MY",
  "source_note": "Generated from 2ET_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · 13 steps"
};

export default content;
