// Auto-generated by scripts/emit_ts.py — do not edit by hand.
// Source: SAP Best Practices BPD + decisions YAML.
// Re-run: `python scripts/emit_ts.py BD9`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "BD9",
  "title": "Sell from Stock",
  "overview": "Sell-from-Stock provides a streamlined approach to order fulfillment. The Sell-from-Stock process is designed to efficiently manage and track the sales and shipment of existing inventory. It expedites order fulfillment, accurately recognizes revenue, and maintains precise financial accounting.",
  "business_roles": [
    {
      "name": "Configuration Expert - Business Process Configuration",
      "id": "SAP_BR_BPC_EXPERT"
    },
    {
      "name": "Configuration Expert - Business Network Integration",
      "id": "SAP_BR_CONF_EXPERT_BUS_NET_INT"
    },
    {
      "name": "Internal Sales Representative",
      "id": "SAP_BR_INTERNAL_SALES_REP"
    },
    {
      "name": "Shipping Specialist",
      "id": "SAP_BR_SHIPPING_SPECIALIST"
    },
    {
      "name": "Warehouse Clerk",
      "id": "SAP_BR_WAREHOUSE_CLERK"
    },
    {
      "name": "Billing Clerk",
      "id": "SAP_BR_BILLING_CLERK"
    },
    {
      "name": "Credit Controller",
      "id": "SAP_BR_CREDIT_CONTROLLER"
    },
    {
      "name": "Master Data Specialist - Business Partner Data",
      "id": "SAP_BR_BUPA_MASTER_SPECIALIST"
    },
    {
      "name": "Sales Manager",
      "id": "SAP_BR_SALES_MANAGER"
    },
    {
      "name": "Business Process Specialist",
      "id": "SAP_BR_BUSINESS_PROCESS_SPEC"
    },
    {
      "name": "Administrator",
      "id": "SAP_BR_ADMINISTRATOR"
    },
    {
      "name": "Pricing Specialist",
      "id": "SAP_BR_PRICING_SPECIALIST"
    },
    {
      "name": "Master Data Specialist - Product Data",
      "id": "SAP_BR_PRODMASTER_SPECIALIST"
    },
    {
      "name": "Extensibility Specialist",
      "id": "SAP_BR_EXTENSIBILITY_SPEC"
    }
  ],
  "fiori_apps": [
    "Manage Sales Orders (F1873)",
    "My Inbox- All Items",
    "Create Outbound Deliveries - From Sales Orders (F0869A)",
    "Display Outbound Delivery (VL03N)",
    "Manage Outbound Deliveries - VL06O (VL06O_CLOUD)",
    "Change Outbound Delivery (VL02N)",
    "Split Outbound Delivery (VLSP)",
    "POD - Change Outbound Delivery",
    "Create Preliminary Billing Documents (F2876)",
    "Manage Preliminary Billing Documents (F2875)",
    "My Inbox - All Items (F2097)",
    "Create Billing Documents - VF01 (VF01)",
    "Create Billing Documents (F0798)",
    "Display Billing Documents (VF03)"
  ],
  "process_steps": [
    {
      "name": "Set Credit Limit (Optional)",
      "role": "Credit Controller",
      "app": "",
      "expected": "Credit Limit for 54100005 Customer has been set."
    },
    {
      "name": "Complete Sales Quotation (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Sales Order",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders (F1873)",
      "expected": "The Manage Sales Orders screen displays."
    },
    {
      "name": "Create Sales Order Using IFRS15 Bundling Functionality (Optional)",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders (F1873)",
      "expected": "The Manage Sales Orders screen displays."
    },
    {
      "name": "Create Attachment for Sales Order (Optional)",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders (F1873)",
      "expected": ""
    },
    {
      "name": "Review Blocked Sales Orders (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Process Sales Order Approval (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Withdraw from Approval",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders (F1873)",
      "expected": ""
    },
    {
      "name": "Approve/Reject/Rework Sales Order",
      "role": "Sales Manager",
      "app": "My Inbox- All Items",
      "expected": ""
    },
    {
      "name": "Rework Sales Order",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Check the Notifications",
      "role": "Internal Sales Representative",
      "app": "My Inbox- All Items",
      "expected": ""
    },
    {
      "name": "Change Sales Order",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders (F1873)",
      "expected": ""
    },
    {
      "name": "Advanced Available-to-Promise Processing (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Delivery",
      "role": "Shipping Specialist",
      "app": "Create Outbound Deliveries - From Sales Orders (F0869A)",
      "expected": ""
    },
    {
      "name": "Create Attachment for Delivery (Optional)",
      "role": "Shipping Specialist",
      "app": "Display Outbound Delivery (VL03N)",
      "expected": ""
    },
    {
      "name": "Execute Picking",
      "role": "Shipping Specialist",
      "app": "Manage Outbound Deliveries - VL06O (VL06O_CLOUD)",
      "expected": ""
    },
    {
      "name": "Check Batches (Optional)",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": "Batch numbers are checked"
    },
    {
      "name": "Maintain Serial Numbers (Optional)",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": ""
    },
    {
      "name": "Split Outbound Delivery (Optional)",
      "role": "Shipping Specialist",
      "app": "Split Outbound Delivery (VLSP)",
      "expected": ""
    },
    {
      "name": "Add Freight Costs (Optional)",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": ""
    },
    {
      "name": "Post Goods Issue",
      "role": "Shipping Specialist",
      "app": "Manage Outbound Deliveries - VL06O (VL06O_CLOUD)",
      "expected": "The goods issue is posted."
    },
    {
      "name": "Proof of Delivery (Optional)",
      "role": "Shipping Specialist",
      "app": "POD - Change Outbound Delivery",
      "expected": ""
    },
    {
      "name": "Create Preliminary Billing Document (Optional)",
      "role": "Billing Clerk",
      "app": "Create Preliminary Billing Documents (F2876)",
      "expected": ""
    },
    {
      "name": "Finalize the Preliminary Billing Document",
      "role": "Billing Clerk",
      "app": "Manage Preliminary Billing Documents (F2875)",
      "expected": ""
    },
    {
      "name": "Rework from Approval",
      "role": "Billing Clerk",
      "app": "Manage Preliminary Billing Documents (F2875)",
      "expected": ""
    },
    {
      "name": "Approve/Reject/Rework Preliminary Billing Document",
      "role": "Billing approval",
      "app": "My Inbox - All Items (F2097)",
      "expected": ""
    },
    {
      "name": "Rework Preliminary Billing Document",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Check the Notifications",
      "role": "Billing Clerk",
      "app": "My Inbox - All Items (F2097)",
      "expected": ""
    },
    {
      "name": "Change Preliminary Billing Document",
      "role": "Billing Clerk",
      "app": "Manage Preliminary Billing Documents (F2875)",
      "expected": ""
    },
    {
      "name": "Create Partial Billing Document (Optional)",
      "role": "Billing Clerk",
      "app": "Create Billing Documents - VF01 (VF01)",
      "expected": ""
    },
    {
      "name": "Create Billing Document",
      "role": "Billing Clerk",
      "app": "Create Billing Documents (F0798)",
      "expected": "The Create Billing Document screen displays."
    },
    {
      "name": "Create Attachment for Billing (Optional)",
      "role": "Billing Clerk",
      "app": "Display Billing Documents (VF03)",
      "expected": "The Display Billing Document screen displays."
    }
  ],
  "master_data": [],
  "succeeding_processes": [],
  "decisions": [
    {
      "id": "d1",
      "title": "Sales order document type",
      "summary": "SAP delivers a standard order type (OR). Do you need additional order types (e.g., \"Cash Sale\", \"Rush Order\", \"Consignment Order\")?\n",
      "sscui": "102495 - Configure Sales Document Types",
      "sscui_id": "102495",
      "sscui_name": "Configure Sales Document Types",
      "std_desc": "Use SAP standard order type OR. Single type covers most cases.",
      "cfg_desc": "Add additional order types via SSCUI (e.g., Cash Sale, Rush Order). Included.",
      "cst_desc": "Custom order type with custom fields, logic, integrations. Effort estimated separately in your SOW.",
      "effort": 5,
      "custom_type": "Key User Extensibility + Custom Sales Doc Type",
      "ext_impact": "Medium - custom fields need regression test each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d2",
      "title": "Order number ranges",
      "summary": "How should sales orders be numbered? Internal sequential vs external prefix pattern?",
      "sscui": "102819 - Define Number Ranges for Sales Documents",
      "sscui_id": "102819",
      "sscui_name": "Define Number Ranges for Sales Documents",
      "std_desc": "Accept SAP standard internal numbering. Simple, fast.",
      "cfg_desc": "Define custom number ranges per order type or company code (e.g., year prefix). Included.",
      "cst_desc": "Number generation logic tied to external system or legacy migration scheme. Effort estimated separately in your SOW.",
      "effort": 2,
      "custom_type": "Developer Extensibility (custom number range BAdI)",
      "ext_impact": "Medium - BAdI implementation, retest on each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d3",
      "title": "Availability check policy",
      "summary": "How strict should the availability check be? Block order creation if stock not available? Allow partial confirmation?\n",
      "sscui": "No direct SSCUI — Advanced Available-to-Promise (aATP)",
      "sscui_id": "",
      "sscui_name": "Advanced Available-to-Promise (aATP)",
      "std_desc": "Standard ATP check. Stock confirmed; partial deliveries allowed.",
      "cfg_desc": "Configure checking group, scope of check, backorder behavior via SSCUI. Included.",
      "cst_desc": "Advanced ATP, external availability check, or custom allocation logic. Effort estimated separately in your SOW.",
      "effort": 6,
      "custom_type": "Developer Extensibility + advanced ATP / external integration",
      "ext_impact": "High - touches all order flows, full regression each release",
      "ricefw_class": "I (Interface)"
    },
    {
      "id": "d4",
      "title": "Credit management at order",
      "summary": "Should orders be checked against customer credit limits? Block on failure? Auto-route to approver?\n",
      "sscui": "No direct SSCUI — SAP Credit Management",
      "sscui_id": "",
      "sscui_name": "SAP Credit Management",
      "std_desc": "No automatic credit check. Manual review by AR team.",
      "cfg_desc": "Enable standard credit check with risk categories and block-on-fail. Included.",
      "cst_desc": "Multi-stage credit workflow with custom risk scoring and external credit bureau integration. Effort estimated separately in your SOW.",
      "effort": 7,
      "custom_type": "Workflow Developer Extension + Credit Bureau Integration",
      "ext_impact": "High - external system + multi-stage logic, full retest",
      "ricefw_class": "I (Interface)"
    },
    {
      "id": "d5",
      "title": "Pricing manual override",
      "summary": "Can sales reps manually override pricing on individual line items? Who can approve discounts above a threshold?\n",
      "sscui": "101117 - Set Pricing Procedures",
      "sscui_id": "101117",
      "sscui_name": "Set Pricing Procedures",
      "std_desc": "Standard pricing locked. Discounts only via approved condition records.",
      "cfg_desc": "Enable manual price override with approval workflow above threshold. Included.",
      "cst_desc": "Custom approval routing based on customer tier, product, region. Effort estimated separately in your SOW.",
      "effort": 5,
      "custom_type": "Flexible Workflow + Key User Extensibility",
      "ext_impact": "Medium-High - approval logic + custom routing",
      "ricefw_class": "W (Workflow)"
    },
    {
      "id": "d6",
      "title": "Order confirmation output",
      "summary": "When an order is saved, should it auto-send confirmation to the customer? Format and channel?",
      "sscui": "No direct SSCUI — Output Management (Output Determination)",
      "sscui_id": "",
      "sscui_name": "Output Management (Output Determination)",
      "std_desc": "Manual output. Rep clicks Print/Email when needed.",
      "cfg_desc": "Auto-email order confirmation using standard SAP form template. Included.",
      "cst_desc": "Custom-branded PDF, multilingual, with company-specific fields and conditional content. Effort estimated separately in your SOW (per form variant).",
      "effort": 4,
      "custom_type": "Adobe Forms (Form Template) + Key User Extensibility",
      "ext_impact": "Low - form templates are upgrade-stable",
      "ricefw_class": "F (Form)"
    },
    {
      "id": "d7",
      "title": "Delivery split / consolidation",
      "summary": "Should one order generate one delivery, or split by plant/shipping point? Allow customer-side consolidation across multiple orders?\n",
      // TODO(verify): no clean "delivery split" SSCUI in 2602; closest catalogue candidate is 102763 (Define Copying Control for Delivery Document to Billing Document). Confirm intended config or keep this framework label.
      "sscui": "No direct SSCUI — Delivery/Shipping Configuration",
      "sscui_id": "",
      "sscui_name": "Delivery/Shipping Configuration",
      "std_desc": "Standard delivery split rules (per plant, per ship-to). One order may produce multiple deliveries.",
      "cfg_desc": "Adjust split criteria via SSCUI (e.g., consolidate by customer regardless of plant). Included.",
      "cst_desc": "Custom split logic based on customer preference, carrier, route, or schedule. Effort estimated separately in your SOW.",
      "effort": 4,
      "custom_type": "Developer Extensibility (delivery split BAdI)",
      "ext_impact": "Medium - delivery flow regression each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d8",
      "title": "Order approval workflow",
      "summary": "Do high-value orders need management approval before going to fulfillment? Threshold-based, customer-based, or product-based?\n",
      "sscui": "No direct SSCUI — Flexible Workflow for Sales Documents",
      "sscui_id": "",
      "sscui_name": "Flexible Workflow for Sales Documents",
      "std_desc": "No approval required. Orders flow directly to fulfillment.",
      "cfg_desc": "Enable SAP Flexible Workflow with value-threshold approval. Included.",
      "cst_desc": "Multi-stage approval with custom criteria (margin, product, customer tier) and external escalation. Effort estimated separately in your SOW.",
      "effort": 8,
      "custom_type": "Workflow Developer Extension + Integration",
      "ext_impact": "High - multi-stage logic + external integration, full retest each release",
      "ricefw_class": "W (Workflow)"
    }
  ],
  "sscui_refs": [
    {
      "sscui_id": "102430",
      "name": "Set Alternative Calculation of Condition Amount",
      "category": "Optional",
      "subarea": "Price Management"
    },
    {
      "sscui_id": "103073",
      "name": "Assign eDocument Type to Delivery Type",
      "category": "Recommended",
      "subarea": "Legal Compliance"
    },
    {
      "sscui_id": "103303",
      "name": "Define Relevant Date for Product Hierarchy Determination",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "102353",
      "name": "Define Incoterms",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "103044",
      "name": "Create Condition Tables for Revenue Account Determination",
      "category": "Optional",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "103045",
      "name": "Change Condition Tables for Revenue Account Determination",
      "category": "Optional",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "103046",
      "name": "Change Field Catalog for Condition Tables",
      "category": "Optional",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "103062",
      "name": "Assign Custom Routines to Billing Types",
      "category": "Optional",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102795",
      "name": "Edit List of Fields Used in Pricing Routines",
      "category": "Mandatory",
      "subarea": "Price Management"
    },
    {
      "sscui_id": "102905",
      "name": "Set Copying Control: Sales Document to Sales Document",
      "category": "Optional",
      "subarea": "Sales Order Management and Processing"
    },
    {
      "sscui_id": "102906",
      "name": "Set Copying Control: Billing Document to Sales Document",
      "category": "Optional",
      "subarea": "Sales Order Management and Processing"
    },
    {
      "sscui_id": "102359",
      "name": "Define Reasons for Quantity Differences",
      "category": "Mandatory",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102361",
      "name": "Maintain Country And Transportation Zone For Shipping Point",
      "category": "Optional",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102362",
      "name": "Define Transportation Zones",
      "category": "Optional",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102394",
      "name": "Assign Output Texts to Business Partner Data",
      "category": "Optional",
      "subarea": "Basic Functions"
    },
    {
      "sscui_id": "102395",
      "name": "Assign Output Texts to Document Text Types",
      "category": "Optional",
      "subarea": "Basic Functions"
    },
    {
      "sscui_id": "102433",
      "name": "Define Sales Statuses",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "102435",
      "name": "Define Weight Groups",
      "category": "Optional",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102436",
      "name": "Maintain Working Hours",
      "category": "Optional",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102733",
      "name": "Determine eDocument Type by Billing Type and Customer Category",
      "category": "Recommended",
      "subarea": "Legal Compliance"
    },
    {
      "sscui_id": "102734",
      "name": "Determine eDocument Type by Document Type and Customer Category",
      "category": "Recommended",
      "subarea": "Legal Compliance"
    },
    {
      "sscui_id": "102735",
      "name": "Determine eInvoice Type by Document Class and Tax Code",
      "category": "Recommended",
      "subarea": "Legal Compliance"
    },
    {
      "sscui_id": "102808",
      "name": "Set Alternative Calculation of Condition Base Value",
      "category": "Optional",
      "subarea": "Price Management"
    },
    {
      "sscui_id": "102841",
      "name": "Maintain Organization Unit",
      "category": "Recommended",
      "subarea": "Legal Compliance"
    },
    {
      "sscui_id": "101292",
      "name": "Set Up Text Determination for Billing Header",
      "category": "Optional",
      "subarea": "Basic Functions"
    },
    {
      "sscui_id": "101289",
      "name": "Set Up Text Determination for Sales Area Texts in Customer Master",
      "category": "Optional",
      "subarea": "Basic Functions"
    },
    {
      "sscui_id": "101290",
      "name": "Set Up Text Determination for Sales Document Header",
      "category": "Optional",
      "subarea": "Basic Functions"
    },
    {
      "sscui_id": "101291",
      "name": "Set Up Text Determination for Delivery Header",
      "category": "Optional",
      "subarea": "Basic Functions"
    },
    {
      "sscui_id": "102213",
      "name": "Define Reasons for Blocking in Shipping",
      "category": "Mandatory",
      "subarea": "Basic Functions"
    },
    {
      "sscui_id": "101117",
      "name": "Set Pricing Procedures",
      "category": "Recommended",
      "subarea": "Price Management"
    },
    {
      "sscui_id": "101202",
      "name": "Set Customer Pricing Procedures",
      "category": "Mandatory",
      "subarea": "Price Management"
    },
    {
      "sscui_id": "101118",
      "name": "Set Pricing Procedure Determination",
      "category": "Mandatory",
      "subarea": "Price Management"
    },
    {
      "sscui_id": "102762",
      "name": "Define Copying Control for Sales Document to Billing Document",
      "category": "Optional",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102763",
      "name": "Define Copying Control for Delivery Document to Billing Document",
      "category": "Optional",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102764",
      "name": "Define Copying Control for Billing Document to Billing Document",
      "category": "Optional",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102174",
      "name": "Define Account Assignment Groups for Customers",
      "category": "Mandatory",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102173",
      "name": "Define Account Assignment Groups for Materials",
      "category": "Mandatory",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102400",
      "name": "Define Access Sequences for Revenue Account Determination",
      "category": "Mandatory",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102370",
      "name": "Define Account Determination Types",
      "category": "Mandatory",
      "subarea": "Sales Billing"
    },
    {
      "sscui_id": "102577",
      "name": "Customer Group 1",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "102578",
      "name": "Customer Group 2",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "102579",
      "name": "Customer Group 3",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "102580",
      "name": "Customer Group 4",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "102581",
      "name": "Customer Group 5",
      "category": "Optional",
      "subarea": "Sales Master Data Management"
    },
    {
      "sscui_id": "102124",
      "name": "Define Delivery Priorities",
      "category": "Optional",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102151",
      "name": "Maintain Route Determination",
      "category": "Recommended",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102131",
      "name": "Define Modes of Transport",
      "category": "Optional",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102130",
      "name": "Assign Picking Locations",
      "category": "Recommended",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102126",
      "name": "Assign Shipping Points",
      "category": "Mandatory",
      "subarea": "Delivery Management"
    },
    {
      "sscui_id": "102523",
      "name": "Maintain Duration",
      "category": "Optional",
      "subarea": "Delivery Management"
    }
  ],
  "release": "S/4HANA Cloud Public Edition 2602 — MY"
};

export default content;
