// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Source: sap-references/2608/bpd-fts/BDG_S4CLD2608_BPD_EN_MY.xlsx (sha256 d870808c94b2…)
//       + BDG_S4CLD2608_BPD_EN_MY.docx (sha256 f9527146ee45…) for roles / master data / succeeding processes.
// Steps: xlsx activities after "Test Procedures" (10); 5 step(s) took role/app/expected from the docx Overview Table.
// Decisions: carried over from the curated set (scripts/decisions-yaml); sscui_refs: none (no curated per-item SSCUI source yet).
// Re-run: `pnpm sap:2608:emit-fts`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "BDG",
  "title": "Sales Quotation",
  "overview": "This scope item starts when requests for quotations are received from customers. Quotations are created in the system and can be either accepted or rejected by customers.",
  "business_roles": [
    {
      "name": "Business Process Specialist",
      "id": "SAP_BR_BUSINESS_PROCESS_SPEC"
    },
    {
      "name": "Configuration Expert - Business Process Configuration",
      "id": "SAP_BR_BPC_EXPERT"
    },
    {
      "name": "Administrator",
      "id": "SAP_BR_ADMINISTRATOR"
    },
    {
      "name": "Internal Sales Representative",
      "id": "SAP_BR_INTERNAL_SALES_REP"
    },
    {
      "name": "Sales Manager",
      "id": "SAP_BR_SALES_MANAGER"
    },
    {
      "name": "Extensibility Specialist",
      "id": "SAP_BR_EXTENSIBILITY_SPEC"
    }
  ],
  "fiori_apps": [
    "Manage Sales Quotations (F1852)",
    "My Inbox - All Items (F0862)"
  ],
  "process_steps": [
    {
      "name": "Create Sales Quotation",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Quotations (F1852)",
      "expected": "Preview for PDF document displays."
    },
    {
      "name": "Process Sales Quotation Approval (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Withdraw from Approval",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Quotations (F1852)",
      "expected": "Approval status is changed to In Approval."
    },
    {
      "name": "Approve/Reject/Rework Quotation",
      "role": "Sales Manager",
      "app": "My Inbox - All Items (F0862)",
      "expected": "Based on above decisions, choose next steps accordingly:"
    },
    {
      "name": "Rework Sales Quotation",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Change Quotation (Optional)",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Quotations (F1852)",
      "expected": "The quantity is changed in the quotation document."
    },
    {
      "name": "Set Quotation as Rework not Required",
      "role": "Internal Sales Representative",
      "app": "My Inbox - All Items (F0862)",
      "expected": "Set item to rework not required."
    },
    {
      "name": "Release the Reworked Quotation",
      "role": "Sales Manager",
      "app": "My Inbox - All Items (F0862)",
      "expected": "The reworked quotation is released."
    },
    {
      "name": "Change Quotation",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Quotations (F1852)",
      "expected": "The quantity is changed in the quotation document."
    },
    {
      "name": "Reject Sales Quotation",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Quotations (F1852)",
      "expected": "Quotation is rejected."
    }
  ],
  "master_data": [
    {
      "data": "Material",
      "sample": "TG10",
      "details": "Trad.Good 10,PD,Third Party\nTrading Good for regular Trading (MRP planning) with item category group CBOR.\nno Serial no.; no batch"
    },
    {
      "data": "Material",
      "sample": "TG11",
      "details": "Trading Good for Reg. Trading (MRP planning)\nno Serial no.; no batch"
    },
    {
      "data": "Material",
      "sample": "TG12",
      "details": "Trad.Good 12,Reorder Point,Reg.Trad.\nno Serial no.; no batch"
    },
    {
      "data": "Material",
      "sample": "TG13",
      "details": "Trad.Good 13,Reorder Point,Thrd Party\nTrading Good for Regular Trading (reorder point planning) with item category group CBNA.\nno batch"
    },
    {
      "data": "Material",
      "sample": "TG14",
      "details": "Trad.Good 14,PD,Bought-In,H14\nTrading material with item category group CBUK (Reorder point planning, bought in item).\nno batch"
    },
    {
      "data": "Material",
      "sample": "TG21",
      "details": "Trad.Good 21,Reorder Point,Batch-FIFO\nno Serial no.; batch-controlled (FIFO strategy)"
    },
    {
      "data": "Material",
      "sample": "TG22",
      "details": "Trad.Good 22,Reorder Point,Batch-ExpD\nno Serial no.; batch-controlled (Exp. Date)"
    },
    {
      "data": "Material",
      "sample": "SM0001",
      "details": "Service Material 01"
    },
    {
      "data": "Material",
      "sample": "NS0002",
      "details": "Non-Stock Material 02"
    },
    {
      "data": "Material",
      "sample": "CM-FL-V00",
      "details": "Forklift"
    },
    {
      "data": "Sold-to party",
      "sample": "54100001",
      "details": "Domestic MY Customer 1"
    },
    {
      "data": "Ship-to party",
      "sample": "54100001",
      "details": "Domestic MY Customer 1"
    },
    {
      "data": "Payer",
      "sample": "54100001",
      "details": "Domestic MY Customer 1"
    },
    {
      "data": "Plant",
      "sample": "5410",
      "details": "Plant 1 MY"
    },
    {
      "data": "Storage Location",
      "sample": "541A",
      "details": "Std. storage 1"
    },
    {
      "data": "Shipping Point",
      "sample": "5410",
      "details": "Shipping Point 5410"
    },
    {
      "data": "Sales organization",
      "sample": "5410",
      "details": "Dom. Sales Org"
    },
    {
      "data": "Distribution channel",
      "sample": "10",
      "details": "Direct Sales"
    },
    {
      "data": "Division",
      "sample": "00",
      "details": "Product Division 00"
    }
  ],
  "succeeding_processes": [
    {
      "raw": "Sell from Stock (BD9) (optional)",
      "description": "Process sequence for a standard sales process (sell from stock) with a customer.\nUsing the master data from this document, complete relevant activities described in the test script Sell from Stock (BD9).\nWhen creating the Sales Order, create it with reference using the sales quotation number."
    },
    {
      "raw": "Situation Handling (31N) (optional)",
      "description": "Complete the activities described in test script Situation Handling (31N) to trigger a situation when an open quotation will expire. The situation shall be notified to the responsible employee (defined within responsibility management).\nPossible dimension for Situation Handling:\nOrder Net Value\nSales Organization\nSold-to Party\nOverall Status\nQuotation valid date\nConversion Rate\nDays Before Expiry"
    }
  ],
  "decisions": [
    {
      "id": "d1",
      "title": "Quotation document type",
      "summary": "SAP delivers a standard quotation type (QT). Do you need additional types (e.g., \"Service Quotation\", \"Project Quotation\")?\n",
      "sscui": "102495 - Configure Sales Document Types",
      "sscui_id": "102495",
      "sscui_name": "Configure Sales Document Types",
      "std_desc": "Use SAP standard quotation type QT. Fastest path.",
      "cfg_desc": "Add additional quotation types via SSCUI. Included.",
      "cst_desc": "Custom quotation type with custom fields, logic, and integrations. Effort estimated separately in your SOW.",
      "effort": 4,
      "custom_type": "Key User Extensibility + Custom Sales Doc Type",
      "ext_impact": "Medium - custom fields need regression test each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d2",
      "title": "Quotation validity period",
      "summary": "How long should quotations remain valid? SAP delivers a standard validity period from creation date.",
      "sscui": "105546 - Define Parameter Catalog for Validity Dates",
      "sscui_id": "105546",
      "sscui_name": "Define Parameter Catalog for Validity Dates",
      "std_desc": "Standard 30-day validity. Quote expires automatically.",
      "cfg_desc": "Configure validity per document type or per customer segment (e.g., longer windows for tier-1 customers). Included.",
      "cst_desc": "Dynamic validity based on product, market conditions, or external pricing inputs. Effort estimated separately in your SOW.",
      "effort": 3,
      "custom_type": "Developer Extensibility (custom validity routine)",
      "ext_impact": "Medium - retest on each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d3",
      "title": "Pricing binding at quotation",
      "summary": "Is the price quoted binding once the customer accepts, or only indicative and re-priced at order? Important for FX-sensitive sales.\n",
      "sscui": "101117 - Set Pricing Procedures",
      "sscui_id": "101117",
      "sscui_name": "Set Pricing Procedures",
      "std_desc": "Standard SAP - pricing recalculated at order creation using quotation date. Binding within validity.",
      "cfg_desc": "Configure copying control so order locks the quotation price exactly. Included.",
      "cst_desc": "Custom pricing rules (e.g., lock-in for tier-1 customers, recalc for others). Effort estimated separately in your SOW.",
      "effort": 4,
      "custom_type": "Developer Extensibility (custom pricing routine)",
      "ext_impact": "High - touches all downstream sales docs",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d4",
      "title": "Output to customer",
      "summary": "How should the quotation be delivered to the customer? Auto-email? PDF format?",
      "sscui": "No direct SSCUI — Output Management (Output Determination)",
      "sscui_id": "",
      "sscui_name": "Output Management (Output Determination)",
      "std_desc": "Manual output. Rep clicks Print/Email when ready.",
      "cfg_desc": "Auto-email quotation using standard SAP form on save or approval. Included.",
      "cst_desc": "Custom-branded quotation PDF with company logo, multilingual, dynamic content per customer tier. Effort estimated separately in your SOW.",
      "effort": 5,
      "custom_type": "Adobe Forms + Key User Extensibility",
      "ext_impact": "Low - form templates are upgrade-stable",
      "ricefw_class": "F (Form)"
    },
    {
      "id": "d5",
      "title": "Approval before sending to customer",
      "summary": "Do quotations above a value threshold need internal approval before being sent? Important for margin protection.\n",
      "sscui": "No direct SSCUI — Flexible Workflow for Sales Documents",
      "sscui_id": "",
      "sscui_name": "Flexible Workflow for Sales Documents",
      "std_desc": "No approval required. Reps can send quotations directly.",
      "cfg_desc": "Threshold-based approval via SAP Flexible Workflow (e.g., > MYR 50k = manager approval). Included.",
      "cst_desc": "Multi-stage approval with custom criteria (margin %, customer tier, product mix). Effort estimated separately in your SOW.",
      "effort": 6,
      "custom_type": "Workflow Developer Extension",
      "ext_impact": "Medium-High - workflow logic regression each release",
      "ricefw_class": "W (Workflow)"
    },
    {
      "id": "d6",
      "title": "Quote-to-order conversion",
      "summary": "When the customer accepts, how does the quotation become a sales order? One-click conversion or new document required?\n",
      "sscui": "Copying Control - Quotation to Order",
      "sscui_id": "102905",
      "sscui_name": "Set Copying Control - Sales Document to Sales Document",
      "std_desc": "One-click conversion. SAP copies all data to a new sales order; rep just confirms.",
      "cfg_desc": "Adjust copying control to require additional fields, or split quotation across multiple orders. Included.",
      "cst_desc": "Custom conversion logic (e.g., conditional split, integration with external sales platform). Effort estimated separately in your SOW.",
      "effort": 4,
      "custom_type": "Developer Extensibility (copying control BAdI)",
      "ext_impact": "Medium - copying control regression each release",
      "ricefw_class": "E (Enhancement)"
    },
    {
      "id": "d7",
      "title": "Quotation status reporting",
      "summary": "How do you want to track quotation pipeline (sent, accepted, rejected, expired)? Standard reporting or custom dashboard?\n",
      "sscui": "102433 - Define Sales Statuses",
      "sscui_id": "102433",
      "sscui_name": "Define Sales Statuses",
      "std_desc": "Use SAP standard Fiori apps - Sales Performance, Quotation Status. Sufficient for most.",
      "cfg_desc": "Configure custom KPI tiles and SAC stories using standard data. Included.",
      "cst_desc": "Custom dashboard with external CRM integration, conversion rate ML, predictive analytics. Effort estimated separately in your SOW.",
      "effort": 10,
      "custom_type": "Custom SAC Stories + External Integration + ML",
      "ext_impact": "Medium - external system + analytics regression",
      "ricefw_class": "R (Report)"
    }
  ],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2608 — MY",
  "source_note": "Generated from BDG_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · 10 steps"
};

export default content;
