// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Source: sap-references/2608/bpd-fts/BDW_S4CLD2608_BPD_EN_MY.xlsx (sha256 e1d4b5c35e0d…)
//       + BDW_S4CLD2608_BPD_EN_MY.docx (sha256 d5ab995c38f0…) for roles / master data / succeeding processes.
// Steps: xlsx activities after "Test Procedures" (28); 22 step(s) took role/app/expected from the docx Overview Table.
// Decisions: none curated yet; sscui_refs: none (no curated per-item SSCUI source yet).
// Re-run: `pnpm sap:2608:emit-fts`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "BDW",
  "title": "Returnables Processing",
  "overview": "This scope item enables the shipping of standard pallets and their return. When you create a standard sales order, the delivery is automatically created based on this sales order. During the picking and shipping steps of this process, a pallet (returnable packaging) is added to the delivery. During the billing process, pallets can also be returned to manufacturers using a pallet return order with pallet return delivery and goods receipt, or a pallet return delivery without reference and goods receipt.",
  "business_roles": [
    {
      "name": "Internal Sales Representative",
      "id": "SAP_BR_INTERNAL_SALES_REP"
    },
    {
      "name": "Shipping Specialist",
      "id": "SAP_BR_SHIPPING_SPECIALIST"
    },
    {
      "name": "Warehouse Clerk",
      "id": "SAP_BR_WAREHOUSE_CLERK"
    },
    {
      "name": "Billing Clerk",
      "id": "SAP_BR_BILLING_CLERK"
    },
    {
      "name": "Inventory Manager",
      "id": "SAP_BR_INVENTORY_MANAGER"
    },
    {
      "name": "Returns and Refund Clerk",
      "id": "SAP_BR_RETURNS_REFUND_CLERK"
    }
  ],
  "fiori_apps": [
    "Display Stock Overview (MMBE)",
    "Manage Sales Orders - Version 2 (F3893)",
    "Manage Customer Returns (F1708)",
    "Change Outbound Delivery (VL02N)",
    "Display Outbound Delivery (VL03N)",
    "Manage Outbound Deliveries - VL06O (VL06O_CLOUD)",
    "Create Billing Documents (F0798)",
    "Manage Billing Documents (F2250)",
    "Create Outbound Delivery - Without Order Reference (VL01NO)",
    "Create Sales Orders - VA01 (VA01)",
    "Manage Sales Orders (F1873)",
    "Create Outbound Deliveries - From Sales Orders (F0869A)"
  ],
  "process_steps": [
    {
      "name": "Display Pallets Stock",
      "role": "Warehouse Clerk",
      "app": "Display Stock Overview (MMBE)",
      "expected": "The Stock Overview: Basic List screen displays."
    },
    {
      "name": "Create Sales Order",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders - Version 2 (F3893)",
      "expected": "Sales order saved demand created for MRP within delivery plant"
    },
    {
      "name": "Create Attachment for Sales Order (Optional)",
      "role": "Internal Sales Representative",
      "app": "Manage Customer Returns (F1708)",
      "expected": ""
    },
    {
      "name": "Create Delivery",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": "Delivery created."
    },
    {
      "name": "Create Attachment for Delivery (Optional)",
      "role": "Shipping Specialist",
      "app": "Display Outbound Delivery (VL03N)",
      "expected": ""
    },
    {
      "name": "Add Delivery Item for Pallet",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": "Pallets have been added to the delivery document."
    },
    {
      "name": "Execute Picking",
      "role": "Shipping Specialist",
      "app": "Manage Outbound Deliveries - VL06O (VL06O_CLOUD)",
      "expected": "Picking is done"
    },
    {
      "name": "Check Batches (Optional)",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": "Batch numbers are assigned to the materials"
    },
    {
      "name": "Post Goods Issue",
      "role": "Shipping Specialist",
      "app": "Display Outbound Delivery (VL03N)",
      "expected": "The goods issue is posted."
    },
    {
      "name": "Display Pallets Stock",
      "role": "Warehouse Clerk",
      "app": "Display Stock Overview (MMBE)",
      "expected": "The Stock Overview: Basic List screen displays."
    },
    {
      "name": "Create Billing Documents",
      "role": "Billing Clerk",
      "app": "Create Billing Documents (F0798)",
      "expected": "Invoice created and posted in FI/CO"
    },
    {
      "name": "Create Attachment for Billing (Optional)",
      "role": "Billing Clerk",
      "app": "Manage Billing Documents (F2250)",
      "expected": "The attachment for billing is created."
    },
    {
      "name": "Post Incoming Payment",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Delivery Process for Returnable Materials (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Outbound Delivery without Order Reference (Optional)",
      "role": "Shipping Specialist",
      "app": "Create Outbound Delivery - Without Order Reference (VL01NO)",
      "expected": "The Create Outbound Delivery without Order Reference screen displays."
    },
    {
      "name": "Create Pallets Return Sales Order",
      "role": "Internal Sales Representative",
      "app": "Create Sales Orders - VA01 (VA01)",
      "expected": "Pallets return sales order created"
    },
    {
      "name": "Create Attachment for Sales Order (Optional)",
      "role": "Internal Sales Representative",
      "app": "Manage Customer Returns (F1708)",
      "expected": ""
    },
    {
      "name": "Post Goods Receipt",
      "role": "Shipping Specialist",
      "app": "Manage Outbound Deliveries - VL06O (VL06O_CLOUD)",
      "expected": "The goods receipt is posted."
    },
    {
      "name": "Display Pallets Stock",
      "role": "Warehouse Clerk",
      "app": "Display Stock Overview (MMBE)",
      "expected": "The Stock Overview: Basic List screen displays."
    },
    {
      "name": "Return Process for Returnable Materials (Second Variant)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Outbound Delivery w/o Order Reference",
      "role": "Shipping Specialist",
      "app": "Create Outbound Delivery - Without Order Reference (VL01NO)",
      "expected": "The pallet return delivery is created"
    },
    {
      "name": "Create Attachment for Delivery (Optional)",
      "role": "Shipping Specialist",
      "app": "Display Outbound Delivery (VL03N)",
      "expected": ""
    },
    {
      "name": "Create Pallets Issue Order",
      "role": "Internal Sales Representative",
      "app": "Manage Sales Orders (F1873)",
      "expected": "Returnable packaging issue order is created."
    },
    {
      "name": "Post Goods Issue",
      "role": "Shipping Specialist",
      "app": "Change Outbound Delivery (VL02N)",
      "expected": "The goods issue is posted."
    },
    {
      "name": "Create Billing Document",
      "role": "Billing Clerk",
      "app": "Create Billing Documents (F0798)",
      "expected": "Billing document created"
    },
    {
      "name": "Create Attachment for Billing (Optional)",
      "role": "Billing Clerk",
      "app": "Manage Billing Documents (F2250)",
      "expected": "The attachment for billing is created."
    },
    {
      "name": "Post Incoming Payment",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Display Pallets Stock",
      "role": "Warehouse Clerk",
      "app": "Display Stock Overview (MMBE)",
      "expected": "The Stock Overview: Basic List screen displays."
    }
  ],
  "master_data": [
    {
      "data": "Material",
      "sample": "TG11",
      "details": "Trading Good for Reg. Trading (MRP planning)\nno Serial no.; no batch"
    },
    {
      "data": "Material",
      "sample": "TG12",
      "details": "Trad.Good 12,Reorder Point,Reg.Trad.\nno Serial no.; no batch"
    },
    {
      "data": "Material",
      "sample": "TG21",
      "details": "Trad.Good 21,Reorder Point,Batch-FIFO\nNo serial number, batch controlled (FIFO strategy)"
    },
    {
      "data": "Material",
      "sample": "TG22",
      "details": "Trad.Good 22,Reorder Point,Batch-ExpD\nNo serial number, batch controlled (Exp. Date)"
    },
    {
      "data": "Material",
      "sample": "RP001",
      "details": "Empties,ND"
    },
    {
      "data": "Material",
      "sample": "CM-FL-V00",
      "details": "Forklift"
    },
    {
      "data": "Sold-to Party",
      "sample": "54100001",
      "details": "Domestic MY Customer 1"
    },
    {
      "data": "Ship-to Party",
      "sample": "54100001",
      "details": "Domestic MY Customer 1"
    },
    {
      "data": "Payer",
      "sample": "54100001",
      "details": "Domestic MY Customer 1"
    },
    {
      "data": "Plant",
      "sample": "5410",
      "details": "Plant 1 MY"
    },
    {
      "data": "Storage Location",
      "sample": "541A",
      "details": ""
    },
    {
      "data": "Shipping Point",
      "sample": "5410",
      "details": ""
    },
    {
      "data": "Sales Organization",
      "sample": "5410",
      "details": ""
    },
    {
      "data": "Distribution Channel",
      "sample": "10",
      "details": ""
    },
    {
      "data": "Division",
      "sample": "00",
      "details": ""
    }
  ],
  "succeeding_processes": [
    {
      "raw": "BKK - Sales Order Fulfillment Monitoring and Operations (optional)",
      "description": "Complete the following activities:\nReview Incomplete Sales Orders\nReview Incomplete SD Documents (deliveries)\nReview Outbound Deliveries for Goods Issue\nReview List Blocked (for accounting) Billing Documents)"
    }
  ],
  "decisions": [],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2608 — MY",
  "source_note": "Generated from BDW_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · 28 steps"
};

export default content;
