// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Re-run: `pnpm sap:2608:emit-fts`
//
// MANUAL ADDITION (not emitted by the script): the O2C-SALES VALUE
// STREAM entry. See src/lib/fts/value-streams/o2c-sales.ts. The emitter
// preserves this import + map line on every run.

import type { ScopeItemContent } from "../types";
import scope_1IQ from "./1IQ";
import scope_1NT from "./1NT";
import scope_2ET from "./2ET";
import BD9 from "./BD9";
import BDG from "./BDG";
import BDW from "./BDW";
import J45 from "./J45";
import J59 from "./J59";
import J60 from "./J60";
import { O2C_SALES } from "../value-streams/o2c-sales";

/** Registry of all scope items with curated Tier-1 decisions. */
export const scopeItems: Record<string, ScopeItemContent> = {
  "1IQ": scope_1IQ,
  "1NT": scope_1NT,
  "2ET": scope_2ET,
  BD9: BD9,
  BDG: BDG,
  BDW: BDW,
  J45: J45,
  J59: J59,
  J60: J60,
  "O2C-SALES": O2C_SALES,
};

/** List of scope codes available, sorted alphabetically. */
export const scopeCodes = Object.keys(scopeItems).sort();

/** Look up a scope item by code; returns undefined if not found. */
export function getScopeItem(code: string): ScopeItemContent | undefined {
  return scopeItems[code];
}
