// Auto-generated by scripts/emit_ts.py — do not edit by hand.
// Re-run: `python scripts/emit_ts.py --all`

import type { ScopeItemContent } from "../types";
import scope_1IQ from "./1IQ";
import BD9 from "./BD9";
import BDG from "./BDG";

/** Registry of all scope items with curated Tier-1 decisions. */
export const scopeItems: Record<string, ScopeItemContent> = {
  "1IQ": scope_1IQ,
  BD9: BD9,
  BDG: BDG,
};

/** List of scope codes available, sorted alphabetically. */
export const scopeCodes = Object.keys(scopeItems).sort();

/** Look up a scope item by code; returns undefined if not found. */
export function getScopeItem(code: string): ScopeItemContent | undefined {
  return scopeItems[code];
}
