// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Source: sap-references/2608/bpd-fts/J45_S4CLD2608_BPD_EN_MY.xlsx (sha256 aac157df8bd4…)
//       + J45_S4CLD2608_BPD_EN_MY.docx (sha256 53e668e3e14f…) for roles / master data / succeeding processes.
// Steps: xlsx activities after "Test Procedures" (43); 35 step(s) took role/app/expected from the docx Overview Table.
// Decisions: none curated yet; sscui_refs: none (no curated per-item SSCUI source yet).
// Re-run: `pnpm sap:2608:emit-fts`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "J45",
  "title": "Procurement of Direct Materials",
  "overview": "This purchasing process uses purchase requisitions that are generated either by the Material Requirements Planning (MRP) process or manually by a requester. The conversion from a purchase requisition to a purchase order can either be done manually (in case adoptions are necessary) or automatically (applicable for large volumes). Alternatively, the purchase orders can be generated manually.",
  "business_roles": [
    {
      "name": "Master Data Specialist - Product Data",
      "id": "SAP_BR_PRODMASTER_SPECIALIST"
    },
    {
      "name": "Master Data Specialist - Business Partner Data",
      "id": "SAP_BR_BUPA_MASTER_SPECIALIST"
    },
    {
      "name": "Purchaser",
      "id": "SAP_BR_PURCHASER"
    },
    {
      "name": "Purchasing Manager",
      "id": "SAP_BR_PURCHASING_MANAGER"
    },
    {
      "name": "Inventory Manager",
      "id": "SAP_BR_INVENTORY_MANAGER"
    },
    {
      "name": "Warehouse Clerk",
      "id": "SAP_BR_WAREHOUSE_CLERK"
    },
    {
      "name": "Accounts Payable Accountant",
      "id": "SAP_BR_AP_ACCOUNTANT"
    },
    {
      "name": "Configuration Expert - Business Process Configuration",
      "id": "SAP_BR_BPC_EXPERT"
    },
    {
      "name": "Business Process Specialist",
      "id": "SAP_BR_BUSINESS_PROCESS_SPEC"
    },
    {
      "name": "Billing Clerk",
      "id": "SAP_BR_BILLING_CLERK"
    },
    {
      "name": "Administrator",
      "id": "SAP_BR_ADMINISTRATOR"
    }
  ],
  "fiori_apps": [
    "Process Purchase Requisitions (F1048A)",
    "Manage Purchase Orders (F0842A)",
    "My Inbox - All Items (F0862)",
    "Monitor Purchase Order Items (F2358)",
    "Mass Changes to Purchase Orders (F2593)",
    "Manage Supplier Confirmations (F5039)",
    "Post Goods Receipt for Purchasing Document (F0843)",
    "Material Documents Overview (F1077)",
    "Stock - Single Material (F1076)",
    "Manage Stock (F1062)",
    "Create Supplier Invoice (F0859)",
    "Supplier Invoices List (F1060A)",
    "Clear GR/IR Clearing Account (MR11)",
    "Display/Cancel Account Maintenance Document (MR11SHOW)",
    "Create Purchase Order - Advanced (ME21N)",
    "Monitor Purchase Order Down Payments (F2877)",
    "Post Outgoing Payments (F1612)",
    "Create Supplier Invoice - Advanced (MIRO)",
    "Manage Purchase Requisitions - Professional (F2229)",
    "Schedule Purchasing Jobs - Advanced (F1702)",
    "Create Supplier Invoice - Advanced (MIRO) ."
  ],
  "process_steps": [
    {
      "name": "Procurement of Stock Material: Convert Purchase Requisitions to Purchase Orders",
      "role": "Purchaser",
      "app": "Process Purchase Requisitions (F1048A)",
      "expected": "A list of Requisitions is displayed."
    },
    {
      "name": "Procurement of Stock Material: Create Purchase Order",
      "role": "Purchaser",
      "app": "Manage Purchase Orders (F0842A)",
      "expected": "The Manage Purchase Orders screen is displayed with a list of existing Purchasing Document Items."
    },
    {
      "name": "Procurement of Stock Material: Approve Purchase Order (Optional)",
      "role": "Purchasing Manager",
      "app": "My Inbox - All Items (F0862)",
      "expected": "A list of already created Purchase Orders is displayed."
    },
    {
      "name": "Procurement of Stock Material: Preview Purchase Order (Optional)",
      "role": "Purchaser",
      "app": "Manage Purchase Orders (F0842A)",
      "expected": "The Manage Purchase Orders screen is displayed.\nA list of already created Purchase Orders is displayed."
    },
    {
      "name": "Procurement of Stock Material: Change Purchase Order (Optional)",
      "role": "Purchaser",
      "app": "Manage Purchase Orders (F0842A)",
      "expected": "The Manage Purchase Orders screen is displayed.A list of already created Purchase Orders is displayed."
    },
    {
      "name": "Procurement of Stock Material: Monitor Purchase Order Items (Optional)",
      "role": "Purchaser",
      "app": "Monitor Purchase Order Items (F2358)",
      "expected": "The Monitor Purchase Order Items screen is displayed also, the numbers of current overdue PO items are listed."
    },
    {
      "name": "Procurement of Stock Material: Execute Mass Changes to Purchase Orders (Optional)",
      "role": "Purchaser",
      "app": "Mass Changes to Purchase Orders (F2593)",
      "expected": "The Mass Changes to Purchase Orders screen is displayed."
    },
    {
      "name": "Procurement of Stock Material: Create Supplier Confirmation (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Purchase Order with Confirmation (Optional)",
      "role": "",
      "app": "Manage Purchase Orders (F0842A)",
      "expected": "A new purchase order is created. Purchase order number is displayed."
    },
    {
      "name": "Create Supplier Confirmation (Optional)",
      "role": "",
      "app": "Manage Supplier Confirmations (F5039)",
      "expected": "The supplier confirmation is created."
    },
    {
      "name": "Approve Supplier Confirmation (Optional)",
      "role": "",
      "app": "My Inbox - All Items (F0862)",
      "expected": "The Supplier Confirmation is approved."
    },
    {
      "name": "Manage Supplier Confirmation (Optional)",
      "role": "",
      "app": "Manage Supplier Confirmations (F5039)",
      "expected": "You have reviewed the supplier confirmation item."
    },
    {
      "name": "Procurement of Stock Material: Post Goods Receipt",
      "role": "Warehouse Clerk",
      "app": "Post Goods Receipt for Purchasing Document (F0843)",
      "expected": "The Post Goods Receipt for Purchasing Document screen is displayed."
    },
    {
      "name": "Procurement of Stock Material: Preview Goods Receipt Slip and Label (Optional)",
      "role": "Warehouse Clerk",
      "app": "Material Documents Overview (F1077)",
      "expected": "The Material Documents Overview is displayed."
    },
    {
      "name": "Procurement of Stock Material: Check Goods Receipt Details (Optional)",
      "role": "Warehouse Clerk",
      "app": "Material Documents Overview (F1077)",
      "expected": "The Material Documents Overview is displayed."
    },
    {
      "name": "Procurement of Stock Material: Reverse Goods Receipt (Optional)",
      "role": "Warehouse Clerk",
      "app": "Material Documents Overview (F1077)",
      "expected": "The Material Documents Overview is displayed."
    },
    {
      "name": "Procurement of Stock Material: Analyze Stock Overview (Optional)",
      "role": "Inventory Manager",
      "app": "Stock - Single Material (F1076)",
      "expected": "The Stock Single Material screen is displayed."
    },
    {
      "name": "Procurement of Stock Material: Analyze Material Document (Optional)",
      "role": "Inventory Manager",
      "app": "Material Documents Overview (F1077)",
      "expected": "The Material Document Overview screen displayed."
    },
    {
      "name": "Procurement of Stock Material: Manage Stock (Optional)",
      "role": "Inventory Manager",
      "app": "Manage Stock (F1062)",
      "expected": "The Manage Stock screen is displayed."
    },
    {
      "name": "Option A: Create Supplier Invoice with PO/GR Relation",
      "role": "Accounts Payable Accountant",
      "app": "Create Supplier Invoice (F0859)",
      "expected": "The Create Supplier Invoices screen is displayed."
    },
    {
      "name": "Option B: Create Supplier Invoice with PO/GR relation (with Invoice Reduction) (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Create Supplier Invoice (F0859)",
      "expected": "The Create Supplier Invoices screen is displayed."
    },
    {
      "name": "Option B: Print Complaint Letter in case of Invoice Reduction (Only relevant for SAP S/4HANA Cloud Public Edition)",
      "role": "Accounts Payable Accountant",
      "app": "Supplier Invoices List (F1060A)",
      "expected": "The output items are sent to the printer queue."
    },
    {
      "name": "Create Supplier Invoice without PO/GR (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Create Supplier Invoice (F0859)",
      "expected": "The Create Supplier Invoice screen is displayed."
    },
    {
      "name": "Procurement of Stock Material: Detect Critical Cash Discount Situations (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Procurement of Stock Material: React to Critical Cash Discount Situations (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Supplier Invoices List (F1060A)",
      "expected": "Situation Message is shown and closed."
    },
    {
      "name": "Procurement of Stock Material: Create Credit Memo (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Create Supplier Invoice (F0859)",
      "expected": "Credit Memo is created"
    },
    {
      "name": "Procurement of Stock Material: Check Supplier Invoice List (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Supplier Invoices List (F1060A)",
      "expected": "The Supplier Invoices list screen is displayed."
    },
    {
      "name": "Procurement of Stock Material: Approve Supplier Invoice (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Supplier Invoices List (F1060A)",
      "expected": "The Supplier Invoices list screen is displayed."
    },
    {
      "name": "Procurement of Stock Material: Reverse Invoice (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Supplier Invoices List (F1060A)",
      "expected": "The Supplier Invoices list screen is displayed."
    },
    {
      "name": "Procurement of Stock Material: Clear GR / IR (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Clear GR/IR Clearing Account (MR11)",
      "expected": "The Clear GR / IR Clearing Account screen opens"
    },
    {
      "name": "Procurement of Stock Material: Cancel Journal Entry (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Display/Cancel Account Maintenance Document (MR11SHOW)",
      "expected": "The Display / Cancel Account Maintenance Document screen opens"
    },
    {
      "name": "Monitor Down Payment process: Create Purchase Order Manually for Down Payment",
      "role": "Purchaser",
      "app": "Create Purchase Order - Advanced (ME21N)",
      "expected": "The Create Purchase Order screen is displayed."
    },
    {
      "name": "Monitor Down Payment process: Monitor Down Payments (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Monitor Purchase Order Down Payments (F2877)",
      "expected": "The Monitor Purchase Order Down Payments screen displays."
    },
    {
      "name": "Monitor Down Payment process: Create Down Payment Request",
      "role": "Accounts Payable Accountant",
      "app": "Monitor Purchase Order Down Payments (F2877)",
      "expected": "The Monitor Purchase Order Down Payments screen displays."
    },
    {
      "name": "Monitor Down Payment process: Create Down Payment",
      "role": "Accounts Payable Accountant",
      "app": "Post Outgoing Payments (F1612)",
      "expected": "The Monitor Purchase Order Down Payments screen displays."
    },
    {
      "name": "Monitor Down Payment process: Post Goods Receipt",
      "role": "Warehouse Clerk",
      "app": "Post Goods Receipt for Purchasing Document (F0843)",
      "expected": "The Post Goods Receipt for Purchasing Document screen is displayed."
    },
    {
      "name": "Monitor Down Payment process: Create Supplier Invoice for Down Payment (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Create Supplier Invoice - Advanced (MIRO)",
      "expected": "The Create Supplier Invoices screen is displayed."
    },
    {
      "name": "Automatic Purchase Order Creation from Purchase Requisition",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Purchase Requisition",
      "role": "Purchaser",
      "app": "Manage Purchase Requisitions - Professional (F2229)",
      "expected": "The Manage Purchase Requisitions - Professional screen is displayed."
    },
    {
      "name": "Automatic Conversion of Purchase Requisition to Purchase Order",
      "role": "Purchaser",
      "app": "Schedule Purchasing Jobs - Advanced (F1702)",
      "expected": "The Application Jobs screen is displayed."
    },
    {
      "name": "Post Goods Receipt",
      "role": "Warehouse Clerk",
      "app": "Post Goods Receipt for Purchasing Document (F0843)",
      "expected": "The Post Goods Receipt for Purchasing Document screen is displayed."
    },
    {
      "name": "Create Supplier Invoice",
      "role": "Accounts Payable Accountant",
      "app": "Create Supplier Invoice (F0859)",
      "expected": "The Create Supplier Invoices screen is displayed."
    },
    {
      "name": "eDocument Cockpit",
      "role": "",
      "app": "",
      "expected": ""
    }
  ],
  "master_data": [],
  "succeeding_processes": [],
  "decisions": [],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2608 — MY",
  "source_note": "Generated from J45_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · 43 steps"
};

export default content;
