// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Source: sap-references/2608/bpd-fts/J59_S4CLD2608_BPD_EN_MY.xlsx (sha256 3ff229bd7b8d…)
//       + J59_S4CLD2608_BPD_EN_MY.docx (sha256 138e4fbef69e…) for roles / master data / succeeding processes.
// Steps: xlsx activities after "Test Procedures" (55); 45 step(s) took role/app/expected from the docx Overview Table.
// Decisions: none curated yet; sscui_refs: none (no curated per-item SSCUI source yet).
// Re-run: `pnpm sap:2608:emit-fts`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "J59",
  "title": "Accounts Receivable",
  "overview": "With Accounts Receivable, you manage open receivables invoices that are automatically created from sales processes. Using various analytical tools, you can manage and control open items to optimize accounts receivables handling. The primary source of incoming payments is incoming bank statements that are loaded within the Cash Management process and automatically reconciled with open invoices. User-friendly views simplify and streamline the post processing of open items.",
  "business_roles": [
    {
      "name": "Accounts Receivable Accountant",
      "id": "SAP_BR_AR_ACCOUNTANT"
    },
    {
      "name": "Accounts Receivable Manager",
      "id": "SAP_BR_AR_MANAGER"
    },
    {
      "name": "Billing Clerk",
      "id": "SAP_BR_BILLING_CLERK"
    },
    {
      "name": "General Ledger Accountant",
      "id": "SAP_BR_GL_ACCOUNTANT"
    },
    {
      "name": "Cash Management Specialist",
      "id": "SAP_BR_CASH_SPECIALIST"
    },
    {
      "name": "Administrator",
      "id": "SAP_BR_ADMINISTRATOR"
    },
    {
      "name": "Configuration Expert - Business Process Configuration",
      "id": "SAP_BR_BPC_EXPERT"
    },
    {
      "name": "Configuration Expert - Business Network Integration",
      "id": "SAP_BR_CONF_EXPERT_BUS_NET_INT"
    },
    {
      "name": "Business Process Specialist",
      "id": "SAP_BR_BUSINESS_PROCESS_SPEC"
    }
  ],
  "fiori_apps": [
    "Maintain Business Partner (BP)",
    "Display Customer List (F2640)",
    "Create Outgoing Invoices (FB70)",
    "Upload Customer Open Items (F4051)",
    "Create Dunning Notices (F150)",
    "My Dunning Proposals (F2435)",
    "Display Dunning History (F2328)",
    "Create Correspondence (F0744A)",
    "Display Correspondence History (F2934)",
    "Accounts Receivable Overview (F3242)",
    "Overdue Receivables - Today (F1747)",
    "Overdue Receivables - by Risk Class (F2539)",
    "Future Receivables - Today (F1744)",
    "Total Receivables - Today (F1748)",
    "Days Sales Outstanding - Last 12 Months (F1741)",
    "Dunning Level Distribution - Today (F1742)",
    "Days Beyond Terms - Last 12 Months (F1739)",
    "Display Item Change Log - Customer (F7796)",
    "Cash Collection Tracker - Accounts Receivable (F2925)",
    "Manage Customer Down Payment Requests (F1689)",
    "Post Incoming Payments (F1345)",
    "Clear Incoming Payments - Manual Clearing (F0773)",
    "Reprocess Bank Statement Items (F1520)",
    "Manage Processing Rules - For Bank Statements (F3555)",
    "Manage Payment Advices - Deprecated (F2550)",
    "Reset Cleared Items (F2223)",
    "Schedule Jobs to Reset Cleared Items (F9296)",
    "Manage Journal Entries (F0717A)",
    "Manage Customer Line Items (F0711)",
    "Schedule Interest Calculation Jobs (F4176)",
    "Manage Interest Runs (F4485)",
    "Manage Guarantees Made (F7934)",
    "Schedule Accounts Receivable Jobs (F2366)",
    "Manage Balance Confirmations - For Customers (F2834)",
    "Write Off Receivables (F6728)",
    "eDocument Cockpit (EDOC_COCKPIT)",
    "Dunning history displays.",
    "Create Correspondence (F0744A) or Manage Journal Entries (F0717A)"
  ],
  "process_steps": [
    {
      "name": "Preparation of Payments: Maintain Business Partners",
      "role": "Accounts Receivable Accountant",
      "app": "Maintain Business Partner (BP)",
      "expected": "Customer Master Data is created."
    },
    {
      "name": "Preparation of Payments: Maintain Business Partner Certificate",
      "role": "Accounts Receivable Accountant or a Master Data Specialist - Business Partner Data",
      "app": "Maintain Business Partner (BP)",
      "expected": "You maintained the business partner certificate."
    },
    {
      "name": "Preparation of Payments: Display Customer List",
      "role": "Accounts Receivable Accountant",
      "app": "Display Customer List (F2640)",
      "expected": "Customer List is created."
    },
    {
      "name": "Enter Invoice Without Sales Order",
      "role": "Accounts Receivable Accountant",
      "app": "Create Outgoing Invoices (FB70)",
      "expected": "Invoice is created."
    },
    {
      "name": "Mass Upload: Mass Import of Customer Invoices",
      "role": "Accounts Receivable Accountant",
      "app": "Upload Customer Open Items (F4051)",
      "expected": "Customer invoices are imported."
    },
    {
      "name": "Invoice Reporting",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Dunning Notices",
      "role": "Accounts Receivable Accountant",
      "app": "Create Dunning Notices (F150)",
      "expected": "Dunning history displays."
    },
    {
      "name": "Manage My Dunning Proposals",
      "role": "Accounts Receivable Accountant",
      "app": "My Dunning Proposals (F2435)",
      "expected": "Dunning proposal is created, managed."
    },
    {
      "name": "Display Dunning History",
      "role": "Accounts Receivable Accountant",
      "app": "Display Dunning History (F2328)",
      "expected": "Dunning history is displayed."
    },
    {
      "name": "Open Correspondence",
      "role": "Accounts Receivable Accountant",
      "app": "Create Correspondence (F0744A)",
      "expected": "Correspondence is created."
    },
    {
      "name": "Display Correspondence History",
      "role": "Accounts Receivable Accountant",
      "app": "Display Correspondence History (F2934)",
      "expected": "Correspondence history is displayed."
    },
    {
      "name": "Invoice Management Reporting: Accounts Receivable Overview",
      "role": "Accounts Receivable Manager",
      "app": "Accounts Receivable Overview (F3242)",
      "expected": "Figures and statistics display according to available options."
    },
    {
      "name": "Invoice Management Reporting: Monitor Overdue Receivables",
      "role": "Accounts Receivable Manager",
      "app": "Overdue Receivables - Today (F1747)",
      "expected": "The app returns a graphical overview for the overdue receivables."
    },
    {
      "name": "Invoice Management Reporting: Monitor Overdue Receivables by Risk Class",
      "role": "Accounts Receivable Manager",
      "app": "Overdue Receivables - by Risk Class (F2539)",
      "expected": "A graphical overview for the overdue receivables displays."
    },
    {
      "name": "Invoice Management Reporting: Future Receivables",
      "role": "Accounts Receivable Manager",
      "app": "Future Receivables - Today (F1744)",
      "expected": "A graphical overview for the future receivables displays."
    },
    {
      "name": "Invoice Management Reporting: Total Receivables",
      "role": "Accounts Receivable Manager",
      "app": "Total Receivables - Today (F1748)",
      "expected": "A graphical overview for the total receivables displays."
    },
    {
      "name": "Invoice Management Reporting: Days Sales Outstanding",
      "role": "Accounts Receivable Manager",
      "app": "Days Sales Outstanding - Last 12 Months (F1741)",
      "expected": "An overview of Days Sales Outstanding report displays."
    },
    {
      "name": "Invoice Management Reporting: Dunning Level Distribution",
      "role": "Accounts Receivable Manager",
      "app": "Dunning Level Distribution - Today (F1742)",
      "expected": "A graphical overview for the dunning level distribution displays."
    },
    {
      "name": "Invoice Management Reporting: Days Beyond Terms",
      "role": "Accounts Receivable Manager",
      "app": "Days Beyond Terms - Last 12 Months (F1739)",
      "expected": "A graphical overview for the days beyond terms displays"
    },
    {
      "name": "Invoice Management Reporting: Display Item Change Log",
      "role": "Accounts Receivable Manager",
      "app": "Display Item Change Log - Customer (F7796)",
      "expected": "Display logged changes for journal entries."
    },
    {
      "name": "Invoice Management Reporting: Cash Collection Tracker",
      "role": "Accounts Receivable Manager",
      "app": "Cash Collection Tracker - Accounts Receivable (F2925)",
      "expected": "Cash Collection Tracker Accounts Receivable is generated."
    },
    {
      "name": "Down Payments: Create Down Payment Request",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Customer Down Payment Requests (F1689)",
      "expected": "A journal entry is posted."
    },
    {
      "name": "Down Payments: Display Down Payment Request",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Customer Down Payment Requests (F1689)",
      "expected": "A list of down payment requests displays."
    },
    {
      "name": "Down Payments: Post Down Payment",
      "role": "Accounts Receivable Accountant",
      "app": "Post Incoming Payments (F1345)",
      "expected": "The payment is posted."
    },
    {
      "name": "Down Payments: Enter Invoice Without Sales Order",
      "role": "Accounts Receivable Accountant",
      "app": "Create Outgoing Invoices (FB70)",
      "expected": "Invoice is created."
    },
    {
      "name": "Down Payments: Post Incoming Payments",
      "role": "Accounts Receivable Accountant",
      "app": "Post Incoming Payments (F1345)",
      "expected": "Items are posted."
    },
    {
      "name": "Down Payments: Clear Open Items Manually",
      "role": "Accounts Receivable Accountant",
      "app": "Clear Incoming Payments - Manual Clearing (F0773)",
      "expected": "The item is manually cleared."
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Daily Cash Operations – Bank Statement",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Cash Application Intelligence Integration",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Reprocess Bank Statement Items",
      "role": "Cash Management Specialist",
      "app": "Reprocess Bank Statement Items (F1520)",
      "expected": "A Bank Statement details view is displayed."
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Manage Enrichment Rules for Bank Statement Processing (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Manage Value Extraction for Bank Statements (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Manage Bank Statement Processing Rules (Optional)",
      "role": "Cash Management Specialist",
      "app": "Manage Processing Rules - For Bank Statements (F3555)",
      "expected": "The new rule is saved."
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Obtain Payment Advices Manually (Optional)",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Manage Payment Advice",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Payment Advices - Deprecated (F2550)",
      "expected": "Payment advice is deleted."
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Clear Open Items Manually",
      "role": "Accounts Receivable Accountant",
      "app": "Clear Incoming Payments - Manual Clearing (F0773)",
      "expected": "The item is manually cleared."
    },
    {
      "name": "Incoming Payment with Electronic Bank Statement: Clear Credit/Debit Memos Manually",
      "role": "Accounts Receivable Accountant",
      "app": "Clear Incoming Payments - Manual Clearing (F0773)",
      "expected": "The system displays a Success notification. Showing the document number, company code, and year created. Option buttons to Display or go to the Payment List are available."
    },
    {
      "name": "Incoming Payment without Electronic Bank Statement: Post Incoming Payments",
      "role": "Accounts Receivable Accountant",
      "app": "Post Incoming Payments (F1345)",
      "expected": "Items are posted."
    },
    {
      "name": "Incorrect Posting: Reset Cleared Items",
      "role": "Accounts Receivable Accountant",
      "app": "Reset Cleared Items (F2223)",
      "expected": "A cleared document is reset."
    },
    {
      "name": "Incorrect Posting: Reset and Reverse Cleared Items",
      "role": "Accounts Receivable Accountant",
      "app": "Reset Cleared Items (F2223)",
      "expected": "A document is reset and reversed."
    },
    {
      "name": "Incorrect Posting: Schedule Jobs to Reset Cleared Items (Optional)",
      "role": "Accounts Receivable Accountant",
      "app": "Schedule Jobs to Reset Cleared Items (F9296)",
      "expected": "You scheduled the job to reset cleared items."
    },
    {
      "name": "Incorrect Posting: Reverse Individual Documents",
      "role": "General Ledger Accountant",
      "app": "Manage Journal Entries (F0717A)",
      "expected": "A document is reversed."
    },
    {
      "name": "Invoice Collection Preparation: Manage Customer Line Items",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Customer Line Items (F0711)",
      "expected": "Customer line items are edited"
    },
    {
      "name": "Interest Calculation: Schedule Interest Calculation Jobs",
      "role": "Accounts Receivable Accountant",
      "app": "Schedule Interest Calculation Jobs (F4176)",
      "expected": "You scheduled the interest calculation jobs."
    },
    {
      "name": "Interest Calculation: Manage Interest Runs",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Interest Runs (F4485)",
      "expected": "You managed the interest runs."
    },
    {
      "name": "Interest Calculation: Display Interest Runs",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Interest Runs (F4485)",
      "expected": "You displayed the interest runs."
    },
    {
      "name": "Guarantees Made: Guarantees Made",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Guarantees Made (F7934)",
      "expected": "You created the guarantee."
    },
    {
      "name": "Guarantees Made: Reverse Guarantees",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Guarantees Made (F7934)",
      "expected": "You reversed the guarantee."
    },
    {
      "name": "Periodic Activities: Check Open Balances",
      "role": "",
      "app": "",
      "expected": "Open balances are reviewed."
    },
    {
      "name": "Periodic Activities: Create Balance Confirmation",
      "role": "Accounts Receivable Accountant",
      "app": "Schedule Accounts Receivable Jobs (F2366)",
      "expected": "Balance Confirmation is managed."
    },
    {
      "name": "Periodic Activities: Manage Balance Confirmations",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Balance Confirmations - For Customers (F2834)",
      "expected": "Balance Confirmation is generated."
    },
    {
      "name": "Periodic Activities: Print Customer Balance Confirmation",
      "role": "Accounts Receivable Accountant",
      "app": "Manage Balance Confirmations - For Customers (F2834)",
      "expected": "Balance Confirmation is printed."
    },
    {
      "name": "Periodic Activities: Bad Debt Write-Off",
      "role": "Accounts Receivable Accountant",
      "app": "Write Off Receivables (F6728)",
      "expected": "Unrecoverable items are written off."
    },
    {
      "name": "Malaysia eInvoice: One-Time Customer (Optional)",
      "role": "Accounts Receivable Accountant",
      "app": "Create Outgoing Invoices (FB70)",
      "expected": "You created a customer invoice."
    },
    {
      "name": "eDocument Cockpit",
      "role": "Billing Clerk",
      "app": "eDocument Cockpit (EDOC_COCKPIT)",
      "expected": "You maintained the eDocument."
    }
  ],
  "master_data": [
    {
      "data": "Company Code",
      "sample": "5410",
      "details": ""
    },
    {
      "data": "Controlling Area",
      "sample": "A000",
      "details": ""
    },
    {
      "data": "Customer",
      "sample": "54100001\n54100002",
      "details": ""
    },
    {
      "data": "House Bank",
      "sample": "MYBK1/MYAC1",
      "details": ""
    },
    {
      "data": "Bank G/L Account",
      "sample": "11001000",
      "details": ""
    },
    {
      "data": "Cost Center",
      "sample": "54101101",
      "details": ""
    },
    {
      "data": "Profit Center",
      "sample": "YB700",
      "details": ""
    }
  ],
  "succeeding_processes": [],
  "decisions": [],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2608 — MY",
  "source_note": "Generated from J59_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · 55 steps"
};

export default content;
