// Auto-generated by scripts/emit-fts-2608.ts — do not edit by hand.
// Source: sap-references/2608/bpd-fts/J60_S4CLD2608_BPD_EN_MY.xlsx (sha256 5c2986b7f6f6…)
//       + J60_S4CLD2608_BPD_EN_MY.docx (sha256 53aeda21047a…) for roles / master data / succeeding processes.
// Steps: xlsx activities after "Test Procedures" (79); 71 step(s) took role/app/expected from the docx Overview Table.
// Decisions: none curated yet; sscui_refs: none (no curated per-item SSCUI source yet).
// Re-run: `pnpm sap:2608:emit-fts`

import type { ScopeItemContent } from "../types";

const content: ScopeItemContent = {
  "code": "J60",
  "title": "Accounts Payable",
  "overview": "With Accounts Payable, you manage your open payable invoices that are automatically created from purchasing processes.",
  "business_roles": [
    {
      "name": "Accounts Payable Accountant",
      "id": "SAP_BR_AP_ACCOUNTANT"
    },
    {
      "name": "Administrator",
      "id": "SAP_BR_ADMINISTRATOR"
    },
    {
      "name": "Configuration Expert - Business Process Configuration",
      "id": "SAP_BR_BPC_EXPERT"
    },
    {
      "name": "Cash Management Specialist",
      "id": "SAP_BR_CASH_SPECIALIST"
    },
    {
      "name": "Cash Manager",
      "id": "SAP_BR_CASH_MANAGER"
    },
    {
      "name": "General Ledger Accountant",
      "id": "SAP_BR_GL_ACCOUNTANT"
    },
    {
      "name": "Master Data Specialist - Business Partner Data te",
      "id": "SAP_BR_BUPA_MASTER_SPECIALIST"
    },
    {
      "name": "Manager",
      "id": "SAP_BR_MANAGER"
    },
    {
      "name": "Extensibility Specialist",
      "id": "SAP_BR_EXTENSIBILITY_SPEC"
    },
    {
      "name": "Billing Clerk",
      "id": "SAP_BR_BILLING_CLERK"
    }
  ],
  "fiori_apps": [
    "Maintain Business Partner (BP)",
    "Display Supplier List (F1861)",
    "Enter Available Amounts for Payment Program (S_ALR_87001486)",
    "Create Supplier Invoice (F0859)",
    "Create Supplier Invoice - Advanced (MIRO)",
    "Supplier Invoices List (F1060A)",
    "Manage Recurring Supplier Invoices (F4312)",
    "Schedule Accounts Payable Jobs (F2257)",
    "Import Supplier Invoices (F3041)",
    "Manage Supplier Line Items (F0712)",
    "Manage Payment Blocks (F0593A)",
    "Display Supplier Balances (F0701A)",
    "Manage Automatic Payments (F0770)",
    "Revise Payment Proposals (F0771)",
    "Display Payment Lists (S_P99_41000099)",
    "Manage Payment Plans (F4806)",
    "Create Single Payment (F0743)",
    "My Free Form Payments (F2564)",
    "Process Free Form Payments (F8654)",
    "Post Outgoing Payments (F1612)",
    "Approve Bank Payments (F0673A)",
    "See the Advanced Cash Operations (J78) test script",
    "See the Advanced Cash Operations (J78) test script for more information. The batch item status should be Payment Medium Created.",
    "Create Payment Media - for Payment Runs (F7711)",
    "Create Correspondence (F0744A)",
    "Reset Cleared Items (F2223)",
    "Schedule Jobs to Reset Cleared Items (F9296)",
    "Manage Supplier Down Payment Requests (F1688)",
    "Manage Teams and Responsibilities - Supplier Down Payment Requests (F7483)",
    "Manage Workflows - Supplier Down Payment Requests (F7100)",
    "Verify Supplier Down Payment Requests (F7103)",
    "Verify Supplier Down Payment Requests - Approver Inbox (F7102) or My Inbox - All Items (F0862)",
    "Clear Outgoing Payments - Manual Clearing (F1367)",
    "Schedule Interest Calculation Jobs (F4176)",
    "Manage Interest Runs (F4485)",
    "Manage Guarantees Received (F7933)",
    "Follow the instructions in the View Supplier Line Items [page ] 74 test procedure.",
    "Manage Balance Confirmations - For Suppliers (F2959)",
    "Accounts Payable Overview (F2917)",
    "Days Payable Outstanding - Last 12 Months (F1740)",
    "Overdue Payables - Today (F1746)",
    "Future Payables - Today (F1743)",
    "Cash Discount Forecast - Available Amount (F1735)",
    "Cash Discount Utilization - Today (F1736)",
    "Invoice Processing Analysis - Today (F1745)",
    "Invoice Processing Time - Today (F1745)",
    "Aging Analysis - Payable Amount (F1733)",
    "Aging Report for Accounts Payable (F4401)",
    "Automatic and Manual Payments - Payments for Last Year (F1749)",
    "Supplier Payment Analysis - Open Payments (F1750)",
    "Display Item Change Log - Supplier (F7795)",
    "eDocument Cockpit (EDOC_COCKPIT)",
    "Report Generic Withholding Tax - 马来西亚 (S_P00_07000134)",
    "Manage Payment Plans (F4806)\nSchedule Accounts Payable Jobs (F2257)",
    "Create Correspondence (F0744A) / Manage Journal Entries (F0717A)"
  ],
  "process_steps": [
    {
      "name": "Preparation of Payments: Maintain Business Partner",
      "role": "Accounts Payable Accountant",
      "app": "Maintain Business Partner (BP)",
      "expected": "The Business Partner is maintained."
    },
    {
      "name": "Preparation of Payments: Maintain Business Partner Certificate",
      "role": "Accounts Payable Accountant or a Master Data Specialist - Business Partner Data",
      "app": "Maintain Business Partner (BP)",
      "expected": "You maintained certificate data for the supplier."
    },
    {
      "name": "Preparation of Payments: Display Supplier List",
      "role": "Accounts Payable Accountant",
      "app": "Display Supplier List (F1861)",
      "expected": "The Supplier is displayed."
    },
    {
      "name": "Preparation of Payments: Netting of AR/AP Items (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Maintain Business Partner (BP)",
      "expected": "The Business Partner is maintained."
    },
    {
      "name": "Preparation of Payments: Available Amounts for Payment Program (Optional)",
      "role": "Accounts Payable Manager",
      "app": "Enter Available Amounts for Payment Program (S_ALR_87001486)",
      "expected": "Available amounts are defined."
    },
    {
      "name": "Invoice Entry without Purchase Order: Invoice Entry Without Purchase Order",
      "role": "Personalized User based on the SAP_BR_AP_ACCOUNTANT\nBusiness Role ID",
      "app": "Create Supplier Invoice (F0859)",
      "expected": "The invoice is created."
    },
    {
      "name": "Invoice Entry without Purchase Order: Invoice Entry for One-Time Supplier without Purchase Order",
      "role": "Accounts Payable Accountant",
      "app": "Create Supplier Invoice - Advanced (MIRO)",
      "expected": "The invoice is created."
    },
    {
      "name": "Park and Post Invoice: Park Invoice",
      "role": "Personalized User based on the SAP_BR_AP_ACCOUNTANT\nBusiness Role ID",
      "app": "Create Supplier Invoice (F0859)",
      "expected": "Invoice is parked."
    },
    {
      "name": "Park and Post Invoice: Post Invoice",
      "role": "Personalized User based on the SAP_BR_AP_ACCOUNTANT\nBusiness Role ID",
      "app": "Supplier Invoices List (F1060A)",
      "expected": "Invoice is posted."
    },
    {
      "name": "Recurring Supplier Invoices: Create Recurring Supplier Invoice",
      "role": "Accounts Payable Accountant",
      "app": "Manage Recurring Supplier Invoices (F4312)",
      "expected": "Recurring invoices are created."
    },
    {
      "name": "Recurring Supplier Invoices: Review Recurring Supplier Invoice",
      "role": "Accounts Payable Accountant",
      "app": "Manage Recurring Supplier Invoices (F4312)",
      "expected": "Recurring invoices are reviewed."
    },
    {
      "name": "Recurring Supplier Invoices: Schedule Recurring Supplier Invoice Posting",
      "role": "Accounts Payable Accountant",
      "app": "Schedule Accounts Payable Jobs (F2257)",
      "expected": "A background job is created."
    },
    {
      "name": "Mass Upload: Mass Import for Supplier Invoices",
      "role": "Accounts Payable Accountant",
      "app": "Import Supplier Invoices (F3041)",
      "expected": "Invoices are imported and posted."
    },
    {
      "name": "Invoice Payment Preparation: View Supplier Line Items",
      "role": "Accounts Payable Accountant",
      "app": "Manage Supplier Line Items (F0712)",
      "expected": "Supplier open items are displayed"
    },
    {
      "name": "Invoice Payment Preparation: Manage Payment Blocks",
      "role": "Accounts Payable Accountant",
      "app": "Manage Payment Blocks (F0593A)",
      "expected": "You reviewed blocked invoices and items. Relevant items are unblocked or reblocked with reasons."
    },
    {
      "name": "Invoice Payment Preparation: View Supplier Balance",
      "role": "Accounts Payable Accountant",
      "app": "Display Supplier Balances (F0701A)",
      "expected": "Supplier Balance is displayed."
    },
    {
      "name": "Payment Run",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Schedule Payment Proposals",
      "role": "Accounts Payable Accountant",
      "app": "Manage Automatic Payments (F0770)",
      "expected": "Invoices to be paid are proposed."
    },
    {
      "name": "Revise Payment Proposal",
      "role": "Accounts Payable Accountant",
      "app": "Revise Payment Proposals (F0771)",
      "expected": "You reviewed and revised the proposals."
    },
    {
      "name": "Release Payment Proposal",
      "role": "Accounts Payable Accountant",
      "app": "Manage Automatic Payments (F0770)",
      "expected": "Payments are processed."
    },
    {
      "name": "Mass Reverse Payment Run (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Schedule Accounts Payable Jobs (F2257)",
      "expected": "The payment run is reversed."
    },
    {
      "name": "View Payment List",
      "role": "Accounts Payable Accountant",
      "app": "Display Payment Lists (S_P99_41000099)",
      "expected": "You viewed the payment list."
    },
    {
      "name": "Payment Plans",
      "role": "Accounts Payable Accountant",
      "app": "Manage Payment Plans (F4806)",
      "expected": "You created a job and executed the payment run."
    },
    {
      "name": "Single Outgoing Payment",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Single Outgoing Payment (Indirect)",
      "role": "Accounts Payable Accountant",
      "app": "Manage Supplier Line Items (F0712)",
      "expected": "Single outgoing payment is generated."
    },
    {
      "name": "Create Single Payment (Direct)",
      "role": "Accounts Payable Accountant",
      "app": "Create Single Payment (F0743)",
      "expected": "Single payment is generated."
    },
    {
      "name": "Online Payments: Free Form Payment Request",
      "role": "Accounts Payable Accountant",
      "app": "My Free Form Payments (F2564)",
      "expected": "The request is created."
    },
    {
      "name": "Online Payments: Review or Edit Free Form Payment Request",
      "role": "Cash Management Specialist",
      "app": "Process Free Form Payments (F8654)",
      "expected": "The request is posted."
    },
    {
      "name": "Online Payments: Process Free Form Payment",
      "role": "Cash Management Specialist",
      "app": "Process Free Form Payments (F8654)",
      "expected": "The request is released."
    },
    {
      "name": "Manual Payment Online: Post Outgoing Payment",
      "role": "Accounts Payable Accountant",
      "app": "Post Outgoing Payments (F1612)",
      "expected": "You posted an outgoing payment."
    },
    {
      "name": "Payment Approval",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Bank Payment Approval (Optional based on Cash Management)",
      "role": "See Basic Cash Operations (BFB)",
      "app": "",
      "expected": "Payment released"
    },
    {
      "name": "Approval by First Approver",
      "role": "Accounts Payable Manager",
      "app": "Approve Bank Payments (F0673A)",
      "expected": "The Approve Bank Payments app displays."
    },
    {
      "name": "Rejection",
      "role": "See the Advanced Cash Operations (J78) test script",
      "app": "See the Advanced Cash Operations (J78) test script",
      "expected": ""
    },
    {
      "name": "Approval by Second Approver",
      "role": "Cash Manager",
      "app": "Approve Bank Payments (F0673A)",
      "expected": "The Approve Bank Payments app displays."
    },
    {
      "name": "Payment Media: Create Payment Media",
      "role": "",
      "app": "See the Advanced Cash Operations (J78) test script for more information. The batch item status should be Payment Medium Created.",
      "expected": ""
    },
    {
      "name": "Payment Media: Manual Creation of Payment Media",
      "role": "Accounts Payable Accountant",
      "app": "Create Payment Media - for Payment Runs (F7711)",
      "expected": "You manually created the payment media."
    },
    {
      "name": "Payment Media: Manual Deletion of Payment Media",
      "role": "Accounts Payable Accountant",
      "app": "Create Payment Media - for Payment Runs (F7711)",
      "expected": "You manually deleted the payment media."
    },
    {
      "name": "Payment Advices: Print or Email Payment Advice",
      "role": "Accounts Payable Accountant",
      "app": "Manage Automatic Payments (F0770)",
      "expected": "Payment advice is generated and an email is sent."
    },
    {
      "name": "Payment Advices: Schedule Payment Advices (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Schedule Accounts Payable Jobs (F2257)",
      "expected": "You scheduled the job."
    },
    {
      "name": "Correspondence",
      "role": "Accounts Payable Accountant",
      "app": "Create Correspondence (F0744A)",
      "expected": "You created correspondence."
    },
    {
      "name": "Incorrect Posting: Reset Cleared Items",
      "role": "Accounts Payable Accountant",
      "app": "Reset Cleared Items (F2223)",
      "expected": "The document is reset."
    },
    {
      "name": "Incorrect Posting: Reset and Reverse Cleared Items",
      "role": "Accounts Payable Accountant",
      "app": "Reset Cleared Items (F2223)",
      "expected": "The document is reset and reversed."
    },
    {
      "name": "Incorrect Posting: Schedule Jobs to Reset Cleared Items (Optional)",
      "role": "Accounts Payable Accountant",
      "app": "Schedule Jobs to Reset Cleared Items (F9296)",
      "expected": "You scheduled jobs to reset cleared items."
    },
    {
      "name": "Create Down Payment Request",
      "role": "Accounts Payable Accountant",
      "app": "Manage Supplier Down Payment Requests (F1688)",
      "expected": "A down payment request is posted."
    },
    {
      "name": "Create Down Payment Request with Workflow",
      "role": "",
      "app": "",
      "expected": ""
    },
    {
      "name": "Create Team",
      "role": "Accounts Payable Manager",
      "app": "Manage Teams and Responsibilities - Supplier Down Payment Requests (F7483)",
      "expected": "You created a team."
    },
    {
      "name": "Create Workflow",
      "role": "Accounts Payable Manager",
      "app": "Manage Workflows - Supplier Down Payment Requests (F7100)",
      "expected": "You created a workflow."
    },
    {
      "name": "Create Supplier Down Payment Request for Approval",
      "role": "Accounts Payable Accountant",
      "app": "Verify Supplier Down Payment Requests (F7103)",
      "expected": "You created a supplier down payment request."
    },
    {
      "name": "Review Down Payment Request",
      "role": "Accounts Payable Manager",
      "app": "Verify Supplier Down Payment Requests - Approver Inbox (F7102) or My Inbox - All Items (F0862)",
      "expected": "You reviewed the down payment request."
    },
    {
      "name": "Process Down Payment Request Approval",
      "role": "Accounts Payable Manager",
      "app": "Verify Supplier Down Payment Requests - Approver Inbox (F7102) or My Inbox - All Items (F0862)",
      "expected": "You approved the down payment request."
    },
    {
      "name": "Down Payments: Post Down Payment",
      "role": "Accounts Payable Accountant",
      "app": "Post Outgoing Payments (F1612)",
      "expected": "The system displays Success and the Journal entry xxxxxxxxxx was successfully posted in company code #### notification ."
    },
    {
      "name": "Down Payments: Invoice Entry",
      "role": "",
      "app": "",
      "expected": "The invoice amount should be larger than the down payment amount posted in previous step."
    },
    {
      "name": "Down Payments: Post Outgoing Payment",
      "role": "Accounts Payable Accountant",
      "app": "Post Outgoing Payments (F1612)",
      "expected": "You posted an outgoing payment."
    },
    {
      "name": "Down Payments: Clear Open Items",
      "role": "Accounts Payable Accountant",
      "app": "Clear Outgoing Payments - Manual Clearing (F1367)",
      "expected": "You cleared invoices and down payments."
    },
    {
      "name": "Optional: Interest Calculation: Optional: Schedule Interest Calculation Jobs",
      "role": "Accounts Payable Accountant",
      "app": "Schedule Interest Calculation Jobs (F4176)",
      "expected": "The Document (ID xxxxxxx) view is displayed. The report shows the status of the journal entry document, and shows information such as the journal entry number, the amounts, and the interest."
    },
    {
      "name": "Optional: Interest Calculation: Optional: Manage Interest Runs",
      "role": "Accounts Payable Accountant",
      "app": "Manage Interest Runs (F4485)",
      "expected": "The Sent Interest Letters dialog box displays messages about the output channels from which the interest letters are sent."
    },
    {
      "name": "Optional: Interest Calculation: Optional: Display Interest Runs",
      "role": "Accounts Payable Accountant",
      "app": "Manage Interest Runs (F4485)",
      "expected": "The Interest Run view is displayed for that document. The Items Subject to Interest pane shows related journal entry items, while the Output Items pane shows any outputs (for example, print or email) and their status."
    },
    {
      "name": "Guarantees Received: Guarantees Received",
      "role": "Accounts Payable Accountant",
      "app": "Manage Guarantees Received (F7933)",
      "expected": "You created a guarantee."
    },
    {
      "name": "Guarantees Received: Reverse Guarantees",
      "role": "Accounts Payable Accountant",
      "app": "Manage Guarantees Received (F7933)",
      "expected": "You reversed a guarantee."
    },
    {
      "name": "Periodic Activities: Check Open Balances",
      "role": "",
      "app": "Follow the instructions in the View Supplier Line Items [page ] 74 test procedure.",
      "expected": ""
    },
    {
      "name": "Periodic Activities: Create Supplier Balance Confirmation",
      "role": "Accounts Payable Accountant",
      "app": "Schedule Accounts Payable Jobs (F2257)",
      "expected": "The Balance confirmation is managed."
    },
    {
      "name": "Periodic Activities: Manage Supplier Balance Confirmations",
      "role": "Accounts Payable Accountant",
      "app": "Manage Balance Confirmations - For Suppliers (F2959)",
      "expected": "The Supplier Balance confirmation is managed."
    },
    {
      "name": "Periodic Activities: Print Supplier Balance Confirmation",
      "role": "Accounts Payable Accountant",
      "app": "Manage Balance Confirmations - For Suppliers (F2959)",
      "expected": "The Balance confirmation is generated."
    },
    {
      "name": "Invoice Management Reporting: Accounts Payable Overview",
      "role": "Accounts Payable Manager",
      "app": "Accounts Payable Overview (F2917)",
      "expected": "The Accounts Payable Overview is generated."
    },
    {
      "name": "Invoice Management Reporting: Days Payable Outstanding",
      "role": "Accounts Payable Manager",
      "app": "Days Payable Outstanding - Last 12 Months (F1740)",
      "expected": "You reviewed the days payable outstanding."
    },
    {
      "name": "Invoice Management Reporting: Overdue Payables",
      "role": "Accounts Payable Manager",
      "app": "Overdue Payables - Today (F1746)",
      "expected": "You listed Overdue Payables."
    },
    {
      "name": "Invoice Management Reporting: Future Payables",
      "role": "Accounts Payable Manager",
      "app": "Future Payables - Today (F1743)",
      "expected": "You listed Future Payables."
    },
    {
      "name": "Invoice Management Reporting: Cash Discount Forecast",
      "role": "Accounts Payable Manager",
      "app": "Cash Discount Forecast - Available Amount (F1735)",
      "expected": "You reviewed potential discount opportunities."
    },
    {
      "name": "Invoice Management Reporting: Cash Discount Utilization",
      "role": "Accounts Payable Manager",
      "app": "Cash Discount Utilization - Today (F1736)",
      "expected": "You reviewed discount utilization."
    },
    {
      "name": "Invoice Management Reporting: Invoice Processing Analysis",
      "role": "Accounts Payable Manager",
      "app": "Invoice Processing Analysis - Today (F1745)",
      "expected": "You analyzed invoice processing throughput and bottlenecks."
    },
    {
      "name": "Invoice Management Reporting: Invoice Processing Time",
      "role": "Accounts Payable Manager",
      "app": "Invoice Processing Time - Today (F1745)",
      "expected": "You viewed the invoice processing analysis report."
    },
    {
      "name": "Invoice Management Reporting: Aging Analysis",
      "role": "Accounts Payable Manager",
      "app": "Aging Analysis - Payable Amount (F1733)",
      "expected": "You reviewed payables aging."
    },
    {
      "name": "Invoice Management Reporting: Aging Report for Accounts Payable",
      "role": "Accounts Payable Manager",
      "app": "Aging Report for Accounts Payable (F4401)",
      "expected": "You viewed the aging report."
    },
    {
      "name": "Invoice Management Reporting: Automatic and Manual Payments Analysis",
      "role": "Accounts Payable Manager",
      "app": "Automatic and Manual Payments - Payments for Last Year (F1749)",
      "expected": "You analyzed automatic and manual payments."
    },
    {
      "name": "Invoice Management Reporting: Supplier Payments Analysis",
      "role": "Accounts Payable Manager",
      "app": "Supplier Payment Analysis - Open Payments (F1750)",
      "expected": "You analyzed open or unapplied supplier payments."
    },
    {
      "name": "Invoice Management Reporting: Display Item Change Log",
      "role": "Accounts Payable Manager",
      "app": "Display Item Change Log - Supplier (F7795)",
      "expected": "The logged changes for journal entries are displayed."
    },
    {
      "name": "eDocument Cockpit",
      "role": "Billing Clerk",
      "app": "eDocument Cockpit (EDOC_COCKPIT)",
      "expected": "You maintained the eDocument status."
    },
    {
      "name": "Generic Withholding Tax Report",
      "role": "Accounts Payable Manager for Malaysia",
      "app": "Report Generic Withholding Tax - 马来西亚 (S_P00_07000134)",
      "expected": "The Generic Withholding Tax Reporting view displays."
    }
  ],
  "master_data": [],
  "succeeding_processes": [],
  "decisions": [],
  "sscui_refs": [],
  "release": "S/4HANA Cloud Public Edition 2608 — MY",
  "source_note": "Generated from J60_S4CLD2608_BPD_EN_MY.xlsx (+ .docx) · SAP content release 2608 · 79 steps"
};

export default content;
